openshift/api

- route/v1/types.go
We have lost this whole enum when moving to `openshift/api`.
Fixes https://github.com/openshift/api/issues/26
> Route: Fix InsecureEdgeTerminationPolicy enum

- servicecertsigner/v1alpha1/register.go
When an API has a client, you need to register the metav1 with the types or the client can't send.
@sttts seems like the client-generation should handle this for me in the client scheme, doesn't it?  It's directly related to the client, not to the actual types I manage.
> fix registration for served API

- .gitattributes
/assign @deads2k 
This comes handy when reviewing api changes. It's a copy of the attributes we have in origin, just tailored to this project.
> Make github hide generated files in diffs

- image/v1/types.go
Fixes the verb and type for imagestream/secrets
/assign @liggitt
> list doesn't make sense for subresources

- template/v1/register.go
Templates should not be registering List as part of their API group.  Lists are always v1.
/assign @liggitt
> fix type registration for templates

- build/v1/consts.go
for https://github.com/openshift/origin/pull/20297
ptal @openshift/sig-developer-experience , @openshift/api-review
> add OOMKilled failure reason to build

- apps/v1/consts.go
- apps/v1/deprecated_consts.go
This adds missing consts and vars. The name of consts are harmonized to match the values. 
/cc @openshift/api-review
> apps: add missing consts and vars

- install.go
adds a convenience method for installing kube types that we already depend upon.  This gives an easy way to load the entire external API.
used in https://github.com/openshift/library-go/pull/33
/assign @tnozicka 
@smarterclayton do you prefer library-go?  I could be more complete there (other types we rely upon), but this seems like a natural spot.
> add method for install kube types

- operator/v1alpha1/types.go
- operator/v1alpha1/types_swagger_doc_generated.go
This field will allow admins to override the default imagePullPolicy for operator controlled pod templates.
/cc @deads2k 
/cc @sttts
> operator: add imagePullPolicy to allow override the operator image pull policy

- operator/v1alpha1/types.go
This allows for an easy transition from one to the other and the conditions themselves make sense
> add status conditions to match CVO ClusterOperator

- openshiftcontrolplane/v1/types.go
VXLAN is "VXLAN", so the initial-lowercase version of `NetworkControllerConfig.VXLANPort` should be `vxlanPort`, not `vxLANPort` (which then also makes it consistent with the corresponding network.openshift.io type).
Nothing is using the json/yaml form yet so there are no repo synchronization issues, assuming this merges soon.
> Fix capitalization of vxlanPort

- openshiftcontrolplane/v1/types.go
- openshiftcontrolplane/v1/types_swagger_doc_generated.go
gives us a place to update the controller config such that we can trigger a controller manager rollout when the internal registryhostname changes, and sets us up to later implement https://jira.coreos.com/browse/DEVEXP-190
> add internal registry hostname to serviceaccount controller config

- openshiftcontrolplane/v1/types.go
- openshiftcontrolplane/v1/zz_generated.deepcopy.go
switches the on disk format back the old selector so that https://github.com/openshift/origin/pull/21429 can land to unstick the rebase.
The change to the new selector was correct, but the receiving code isn't ready yet.
/assign @bparees @adambkaplan
> switch build config format back to old style selector

- config/v1/register.go
The metav1 types need to be added to the scheme for the generated clients to function.
/assign @bparees @juanvallejo
> add metav1 to config to allow working client

- operator/v1/types.go
- operator/v1/types_swagger_doc_generated.go
We need to know when we have observed a particular generation of configuration.
> add observed generation to operator v1

- config/v1/types_ingress.go
* `config/v1/types_ingress.go` (`IngressSpec`): Add `Domain` field.
Related to [NE-100](https://jira.coreos.com/browse/NE-100).
> Add ingress domain

- config/v1/types.go
- config/v1/types_swagger_doc_generated.go
Cluster admin provided ConfigMaps and other entities must to reside
in the `openshift-config` namespace.
> config: Remove Namespace for Config References

- config/v1/types_dns.go
Add base domain to the DNS config type. This value is useful to any component
which implements DNS management for the cluster. For example,
cluster-ingress-operator manages wildcard DNS records for routing within the
base domain.
/cc @openshift/sig-network-edge @derekwaynecarr @deads2k @rajatchopra @crawford @smarterclayton
> Add base domain to DNS config

- config/v1/types_infrastructure.go
Add a CloudProvider field to the infra config. This value is needed by at least:
* kubelet
* kube-controller-manager
* kube-apiserver
* openshift-ingress-operator
This change does not intend to address the cloud provider configuration file
API.
/cc @openshift/sig-network-edge @derekwaynecarr @deads2k @rajatchopra @flaper87 @smarterclayton
> Add cloud provider name to infra config

- config/v1/types_infrastructure.go
Rename the Infrastructure CloudProvider field to Platform in an effort to more
clearly establish the value is not directly mapped to Kubernetes cloud provider
constants. Kubernetes cloud provider names may be derived from the value.
/cc @openshift/sig-network-edge @openshift/installer @derekwaynecarr @deads2k @rajatchopra @flaper87 @smarterclayton @abhinavdahiya @staebler
> Rename Infrastructure.CloudProvider to Platform

- config/v1/types.go
- config/v1/types_swagger_doc_generated.go
Spotted by @enj, we were trying to figure out why changes to the authentication config object were not being picked up by its lister.
@deads2k @bparees
> Fix the ConfigMapReference key json

- openshiftcontrolplane/v1/types.go
- openshiftcontrolplane/v1/zz_generated.swagger_doc_generated.go
/oapi should be disabled by default with a backup option to re-enable if absolutely needed.  
/assign @soltysh @sttts
> add option to enable oapi if needed

- operator/v1/types.go
- operator/v1/zz_generated.swagger_doc_generated.go
Logging intent is valuable.  This provides a very coarse grained, "try to log like this" that doesn't map to any "real" logging that we have.  It does not allow targeted logging for particular operands or containers there-in.  
This could be an alternative to detailed logging if we were willing to force detailed logging to make an operator upgradeable=false.  It could be a default if we still want to keep the detailed logging options.  `vmodule` is a super useful thing on the kube binaries and generally packages selection is a handy thing.
@jwforres @derekwaynecarr we've talked about this many times.  I would probably keep both.
> add coarse grained logging desires to operator API

- config/v1/types_build.go
we don't respect the key field anyway so allowing users to specify it is misleading.
> switch build ca ref to configmap ref only (no key)

- config/v1/types_oauth.go
- config/v1/zz_generated.swagger_doc_generated.go
This field is only necessary if we plan on supporting 3.11 to 4.0
upgrades.  Since that is currently not the case, it should be
removed from the top level config.  Note that this does not remove
any of the wiring in osin that is required to support the legacy
path.  Thus if we ever decide to support 3.11 to 4.0 upgrades, we
will add this field back and rewire it through the operator.
Signed-off-by: Monis Khan <mkhan@redhat.com>
@openshift/sig-auth @openshift/api-reviewers
> Remove useUsernameIdentity from KeystoneIdentityProvider

- config/v1/types_cluster_version.go
- config/v1/zz_generated.swagger_doc_generated.go
We consistently use the "release image" terminology in our commands
and design docs when we describe the artifact that carries our manifests
in an update. Payload predates that term (from Omaha) and general
consensus is that we have no plans to deliver our updates in any form
other than as an OCI compatible image.
Update the cluster version object to make it clear that an API consumer
must interpret the payload as a standard Docker image, as they already
do.
> clusterversion: Rename 'Payload' to 'Image'

- annotations/annotations.go
We can't remove these, but they are all examples of "global" annotations that never actually because global. Some were supposed to be temporary while reaching agreement upstream (never happened) and most were related to templates and never used for anything else.
I've added a comment telling people never to add something here. They may think its a global thing, but it isn't.  Use the group they're associated with.
/assign @smarterclayton
> move annotation constants into api

- config/v1/types_infrastructure.go
- config/v1/zz_generated.swagger_doc_generated.go
Expand the list of constants, clarify that unsupported platforms
must be handled as None, and improve godoc. These are not supported
platforms, these are the constants that will be returned.
> infra: Add more constants for platforms and update godoc

- config/v1/types_infrastructure.go
- config/v1/zz_generated.swagger_doc_generated.go
- the etcd members on master machines use the `etcd discovery domain` to bootstrap the etcd cluster.
- `apiserver url` Machine Config Operator currently programs the kubelets on machines to contact `https://<cluster_name>-api.<base_domain>:6443`.
To move the Machine Config Operator to use these global configs, it requires `cluster_name` while `base_domain` is already present in `DNS`. But adding `cluster_name` to
these global configs is not ideal, so `apiserver url` is chosen, which is available at install-time.
/cc @smarterclayton @deads2k
> config/v1: add `etcd discovery domain` and `apiserver url` to Infrastructure status.

- config/v1/types_cluster_operator.go
We cannot gate upgrading on available, failing, and progressing because if any of those conditions are "wrong", we may need to change the version in order to get them working.  This introduces a new condition that indicates whether or not the operator can accept a payload change.
@bparees 
/assign @smarterclayton
> add clusteroperator Upgradeable conditions

- operator/v1/types.go
This PR will make CRD generation more efficient when using a tool such as [sigs.k8s.io/controller-tools/cmd/crd](https://github.com/kubernetes-sigs/controller-tools/tree/master/cmd/crd).  The tool marks anything w/out `optional` comment as `required`, and thus validation fails unless all required fields are set.
This PR does not address fields of individual operators
(ex:  KubeAPIServerSpec , ForceRedeploymentReason) 
Also, This PR does not modify any `Status` fields, because with status we shouldn't generate anything further than 
```console
status:
type: object
```
since the operator populates that directly.  However,  atm the CRD generator does generate all the status fields, so that should be modified, unless I'm mistaken about that.
@damemi @sttts @enj
> Modify operator fields to be optional

- config/v1/types.go
- config/v1/types_apiserver.go
- config/v1/types_authentication.go
- config/v1/types_build.go
- config/v1/types_console.go
- config/v1/types_dns.go
- config/v1/types_features.go
- config/v1/types_image.go
- config/v1/types_infrastructure.go
- config/v1/types_ingress.go
- config/v1/types_network.go
- config/v1/types_oauth.go
- config/v1/types_project.go
- config/v1/types_proxy.go
- config/v1/types_scheduling.go
- operator/v1/types.go
- operator/v1/types_authentication.go
- operator/v1/types_console.go
- operator/v1/types_etcd.go
- operator/v1/types_kubeapiserver.go
- operator/v1/types_kubecontrollermanager.go
- operator/v1/types_openshiftapiserver.go
- operator/v1/types_openshiftcontrollermanager.go
- operator/v1/types_scheduler.go
- operator/v1/types_serviceca.go
- operator/v1/types_servicecatalogapiserver.go
- operator/v1/types_servicecatalogcontrollermanager.go
This updates the `omitempty`, `// +optional`, `// +nullable` (soon a new tag for CRD validation schema generation) tags on all config/v1 and operator/v1 types which either belong to the master team or are uncontroversial. The others are pushed into separate PRs for the respective teams.
This were the rules:
- no `omitempty` for non-pointer structs
- added `// +optional` where we had `omitempty`
- added `// +nullable` where we have `// +optional`, but due to overrides of `JSONMarshal` we cannot apply omitempty.
Otherwise we get invalid `null` values during serialization.
> operator/v1: add omitempty where applicable

- config/v1/types.go
- config/v1/types_apiserver.go
- config/v1/types_authentication.go
- config/v1/types_build.go
- config/v1/types_cluster_operator.go
- config/v1/types_cluster_version.go
- config/v1/types_console.go
- config/v1/types_dns.go
- config/v1/types_features.go
- config/v1/types_image.go
- config/v1/types_infrastructure.go
- config/v1/types_ingress.go
- config/v1/types_network.go
- config/v1/types_oauth.go
- config/v1/types_project.go
- config/v1/types_proxy.go
- config/v1/types_scheduling.go
- operator/v1/types.go
- operator/v1/types_authentication.go
- operator/v1/types_console.go
- operator/v1/types_etcd.go
- operator/v1/types_kubeapiserver.go
- operator/v1/types_kubecontrollermanager.go
- operator/v1/types_openshiftapiserver.go
- operator/v1/types_openshiftcontrollermanager.go
- operator/v1/types_scheduler.go
- operator/v1/types_serviceca.go
- operator/v1/types_servicecatalogapiserver.go
- operator/v1/types_servicecatalogcontrollermanager.go
Second PR with changes which
- **do not change serialization behavour**
- but where the API owners should check (independently from the PR) whether they really means what they specified (e.g. optional, but no pointer to structs).
This updates the `omitempty`, `// +optional`, `// +nullable` (soon a new tag for CRD validation schema generation) tags on all config/v1 and operator/v1 types which either belong to the master team or are uncontroversial. The others are pushed into separate PRs for the respective teams.
This were the rules:
- no `omitempty` for non-pointer structs
- added `// +optional` where we had `omitempty`
- added `// +nullable` where we have `// +optional`, but due to overrides of `JSONMarshal` we cannot apply omitempty.
> config/operator: fix omitempty, +optional, +nullable without behaviour change

- config/v1/types_cluster_version.go
- operator/v1/types_servicecatalogcontrollermanager.go
3rd PR in a row to fix tags.
This one changes behaviour, i.e. it avoid `null` values in serialization and instead omits the fields.
> config/v1: avoid null values for pointers and slices

- operator/v1/types.go
The `managementState` should not be `+optional` is there are only 3 supported values and an empty string is ambiguous.
Once https://github.com/openshift/kubernetes-sigs-controller-tools/pull/4 will land, we can restrict allowed values for each individual operator. 
/cc @sttts 
/cc @deads2k 
/cc @enj
> operator/v1: remove optional from managementState

- config/v1/types_network.go
Fix network status: the installer writes null values for the slices and CR creation fails.
> config: add nullable to NetworkStatus

- config/v1/types_network.go
This changes it so that a network config with no status marshals to:
status: {}
rather than
status:
clusterNetwork: null
clusterNetworkMTU: 0
networkType: ""
serviceNetwork: null
Replaces #237. We will need to pull this update into the installer and the network operator, and then should not need https://github.com/openshift/cluster-config-operator/pull/23 because the existing CRD allows all of the status fields to be missing. I don't think anything besides the installer and CNO marshals this type, so nothing else needs to be updated urgently.
I felt a little bit weird about marking an int32 field as `omitempty`, but there's plenty of precedent (eg, `DeploymentStatus` and `DaemonSetStatus`), and `0` is not a valid value for the field.
@sttts
> Make config.NetworkStatus fields omitempty

- config/v1/types_features.go
This reflects a change in values the operators should respect instead of plumbing it through patches in kube.
/assign @sjenning 
@mfojtik we need a bugzilla to plumb these in our operators.
> update feature gates to match desired values

- operator/v1/types_console.go
cc @openshift/api-reviewers 
fyi @spadgett @zherman0 @rhamilto 
related to:
https://github.com/openshift/console/pull/1233
https://github.com/openshift/console-operator/pull/152
to follow-up:
> Add Azure to brand options for console

- config/v1/types_console.go
Add pattern match for urls created for logoutRedirect (type ConsoleAuthentication).
Example URLs:
1) https://redhat.com/logout.html (valid)
2) https://localhost/logout.php (valid)
3) redhat.com/logout.html (invalid, no https)
> Add pattern check for ConsoleAuthentication

- operator/v1/types.go
Status is unset until an operator is running. Therefore we should not serialize those values.
> operator/v1: mark all status fields omitempty and optional

- config/v1/types_scheduling.go
- config/v1/zz_generated.swagger_doc_generated.go
Adding a default node selector to make sure so that we can have this field observed in apiserver config.
https://github.com/openshift/cluster-kube-apiserver-operator/blob/8e2fb021e10d6d46ffee299cb53863a775957998/bindata/v3.11.0/kube-apiserver/defaultconfig.yaml#L92
> Add default project nodeselector

- build/v1/consts.go
New reason code indicating a build failed due to its pod being evicted.
/assign @smarterclayton 
/cc @bparees
> Bug 1689061: Add BuildPodEvicted Status Reason

- build/v1/consts.go
New reason code indicating a build failed due to its pod being evicted.
> [3.11] Bug 1690066: Add BuildPodEvicted Status Reason

- operator/v1/types.go
Without parenthesis the regex matches `Manageddddd` and `FFForce`.
> operator/v1: fix amangementState regex

- quota/v1/generated.proto
- quota/v1/types.go
Prevent this error:
```
❯ oc create clusterquota for-user-3 \                                                                                                                                                                                                                                                                                                                                    ✘
--project-annotation-selector openshift.io/requester=foo \
--hard pods=10 \
--hard secrets=20
The ClusterResourceQuota "for-user-3" is invalid: []: Invalid value: map[string]interface {}{"kind":"ClusterResourceQuota", "apiVersion":"quota.openshift.io/v1", "metadata":map[string]interface {}{"uid":"1a4f3b42-5152-11e9-a8b1-0e719a5075b6", "name":"for-user-3", "creationTimestamp":"2019-03-28T12:07:48Z", …
```
> quota: make namespaces and labelselector optional and nullable

- config/v1/types_infrastructure.go
- config/v1/zz_generated.swagger_doc_generated.go
Picking up where @fabianofranz  had to leave off in https://github.com/openshift/api/pull/231.
Adding InfrastructureName will give components the information they need to tag cloud resources consistently. (kubernetes.io/cluster/[infraname] = owned)
The controversial arbitrary AWS tagging is removed based on the comments in that PR.
I was going to move this back to Spec because it does not feel like Status to me, but I saw PlatformType is already Status and thus I think this ship has already sailed. 
CC @abhinavdahiya @wking @derekwaynecarr @smarterclayton
> Add InfrastructureName.

- route/OWNERS
route/ is owned by @openshift/sig-network-edge not sig-network
(copied contents from cluster-ingress-operator, minus ramr who's gone now, right?)
> fix route/OWNERS

- operator/v1/types_ingress.go
- operator/v1/zz_generated.deepcopy.go
- operator/v1/zz_generated.swagger_doc_generated.go
Expose configuration for ingresscontroller deployment tolerations.
/cc @openshift/sig-network-edge @smarterclayton @mcurry-rh @thoraxe
> operator/ingress: add tolerations

- operator/v1/types.go
- operator/v1/zz_generated.swagger_doc_generated.go
This allows an operator to look up the desired level and log at that level.  We will plumb this into the installer and pruner pods too.  We can be dynamic to avoid conflicting with the CVO deployment values
/assign @mfojtik 
@derekwaynecarr @smarterclayton as discussed.
@sjenning it's getting better....
> add log level for operator

- config/v1/types_feature.go
Add CSIBlockVolume and BlockVolume feature gates to the API.  Requesting to add this for support in 4.1 in order to enable planned presentations for RH Summit.  Let me know if there is a special feature exception process I need to follow.
> Enable BlockVolume support tech preview for 4.1

- operator/v1/types_serviceca.go
- operator/v1/zz_generated.swagger_doc_generated.go
This should resolve: https://bugzilla.redhat.com/show_bug.cgi?id=1683055
testing now
> bug 1683055: Add spec and status comments/description for serviceca operator type

- Dockerfile.build
- Makefile
Optionally use a container to generate the api due to golang 1.11 gofmt changes.
> makefile: add generator using a container

- config/v1/types_feature.go
As of now even though following are beta upstream, I don't see much value in enabling the following features.
- `ResourceQuotaScopeSelectors` will be GA in 1.15. In the current state, it's not quite useful for us.
- `TaintNodesByCondition` has a 5%(approximate number) chance that node controller and kubelet will race. There are folks who started using this in upstream but this is something that needs some thorough discussion.
- `TaintBasedEvictions` is something that we wanted to use internally for draining but we haven't started using it. So, wanted to postpone it to next release.
/cc @sjenning @derekwaynecarr
> Remove unnecessary scheduling features

- security/v1/generated.proto
- security/v1/types.go
I'm placing +nullable wherever there's optional, we'll start there.  
Need this for:
https://github.com/openshift/cluster-config-operator/pull/41
Bug 1698625
> add nullable tags to SCCs

- config/v1/types_feature.go
In case, we choose to go ahead with taintNodesByCondition because we don't want to touch `ScheduleDSPods`
> Enable taint nodes by condition

- config/v1/types_cluster_version.go
- config/v1/zz_generated.swagger_doc_generated.go
Administrators will need a knob to override upgrades where the payload
is not signed correctly, and future code will guard against more scenarios.
Add a verified tag to history to convey whether we checked the update.
This will be set on upgrades if the payload was verified before update.
/hold
Waiting on openshift/cluster-version-operator#170. Requried for GA
> Update ClusterVersion to have a 'force' update flag and track verified

- operator/v1/types_etcd.go
- operator/v1/zz_generated.swagger_doc_generated.go
The field is duplicated on etcd, which causes origin openapi gen
to fail because of the inline field.
> ForceRedeploymentReason is now duplicated, causes openapi failure

- operator/v1/types_serviceca.go
The order of comments _I believe_ needs to be 
```
// description
// +required|optional
```
and not the other way around 
_sigh_ 
bug 1683055
> fix order of comments in serviceca operator type

- operator/v1/types_network.go
- operator/v1/zz_generated.swagger_doc_generated.go
The objects obviously exist within a namespace and authorization for
attaching additional networks to pods is based on namespace isolation
in Multus. Therefore additional networks that are created at install
time may need to be created in different namespaces.
Related: https://bugzilla.redhat.com/show_bug.cgi?id=1679946
@danwinship @squeed @s1061123 @dougbtv
> network: add 'Namespace' field for AdditionalNetworks

- security/v1/generated.proto
- security/v1/types.go
@deads I'll fix vendor in cluster-config-op when this merges
@enj these were causing validation errors 
`openshift_apiserver.go:609] unable to create default security context constraint`
```
priority in body must be of type integer: "null"
defaultAddCapabilities in body must be of type array: "null"
allowedCapabilities in body must be of type array: "null"
```
> add more nullable tags for SCCs take 3

- config/v1/types_infrastructure.go
- config/v1/zz_generated.swagger_doc_generated.go
The kubelet ([via the machine-config operator][1]) and [Kubernetes API-server operator][2] need the internal API URI.  [The console operator][3] and [authentication operator][4] need the external URI. Since the `api-int` split (e.g. openshift/installer@13e4b702f7, openshift/installer#1601), those are two different things, so we need two different properties.
I've deprecated the old property because it was ambiguous.  We can drop it if/when we ever cut a v2 of this type.
I've avoided leading with `External` or `Internal` so these properties will all alphabetize together when rendering YAML, etc.
I've avoided `Public`, because that is often used in a public/private` dichotomy for security.  The split was motivated by separating X.509 chains of trust, but the URIs themselves are not …
> config/v1/types_infrastructure: Split apiServerURL intro external/internal

- Dockerfile.build
- hack/update-protobuf.sh
The first commit in this PR updates the base image of `Dockerfile.build` from fedora:28 to fedora:29.
Currently with the f28 base, `make generate-with-container` fails with this error:
`go/src/golang.org/x/tools/internal/lsp/source/symbols.go:226:18: ti.EmbeddedType undefined (type *types.Interface has no field or method EmbeddedType)`
Updating to f29 fixes that issue.
Additionally, Fedora 28 EOLs at the end of this month.
The second commit adds an `exit 1` to `hack/update-protobuf.sh` to bail out if the protoc version is not correct. Previously it only showed the message in terminal and continued generating anyway.
> Update Dockerfile.build to fedora:29 base

- security/v1/generated.proto
- security/v1/types.go
These should be set for CRD generators (see https://github.com/openshift/cluster-config-operator/pull/53)
> Add missing kubebuilder tag for SecurityContextConstraint

- build/v1/generated.proto
- build/v1/types.go
- build/v1/zz_generated.swagger_doc_generated.go
In 3.11 and above, only the 5 most recent builds of each category
are retained.
Partially fixes [bug 1693685](https://bugzilla.redhat.com/show_bug.cgi?id=1693685).
> Bug 1693685: Fixing build retention API doc

- operator/v1/types.go
- operator/v1/zz_generated.swagger_doc_generated.go
This came from https://github.com/openshift/library-go/pull/384
Basically, today we don't have great history of why the revision N happened. We report the reason via events which are TTL or to the operator logs (kind of TTL as well).
We should persist the reason of why revision N happened inside the installer pod. The linked PR does that via pod annotation. The reason can be just message or a JSON patch of config that cause the change.
The installer pods are pruned, but we keep several revisions around, which should be enough for debugging.
The field in this PR is required to share the reason between the revision controller and the installer controller.
/cc @deads2k 
/cc @sttts 
/cc @openshift/sig-master
> operator/v1: add latestAvailableRevisionReason

- operator/v1/types_ingress.go
Add kubebuilder markers to support upstream controller-runtime
generation tooling.
> operator/ingress: add kubebuilder markers

- operator/v1/types.go
Move the kubebuilder validation marker location for ManagementState
to the type definition where it belongs.
Fixes this error with [controller-tools@v0.2.0-beta.1](https://github.com/kubernetes-sigs/controller-tools/tree/v0.2.0-beta.1):
```
$ GOFLAGS=-mod=vendor go run sigs.k8s.io/controller-tools/cmd/controller-gen crd:trivialVersions=true paths=./vendor/github.com/openshift/api/operator/v1
/Users/dmace/Projects/ingress-operator/vendor/github.com/openshift/api/operator/v1/types.go:49:2: must apply pattern to a string
Error: not all generators ran succesfully
```
cc @deads2k @sttts @damemi @openshift/sig-network-edge
> operator: fix kubebuilder validation marker location

- security/v1/consts.go
These are the ones that we use today.
> add annotations uses by oas and ocm to communicate about scc

- unidiling/v1alpha1/types.go
These are the current APIs used by the openshift-controller-manager, oc, and the proxier.
> add unidling APIs

- build/v1/consts.go
These represent the current state of API annotations from builds.
> add more build constants that are API

- operator/v1/types_dns.go
Uses the new `scope` marker introduced in https://github.com/kubernetes-sigs/controller-tools/pull/220
> operator/dns: add kubebuilder tags

- build/v1/consts.go
Found more hidden APIs in the buildutil packages that clients must know to properly have their work pass through the controller.
/hold 
holding for a fake bump
/assign @adambkaplan
> add more of the build API surface area

- image/v1/consts.go
this is used to interlock between controller and API.  It's a current API contract.
> add image signature constant

- authorization/v1/types.go
These are used in e2e test and other code that use client go and deal with (cluster) role bindings.
/cc @deads2k
> auth: add UserKind and GroupKind consts

- authorization/v1/types.go
Part of existing internal API. Moving this to external api means we can make authorized in Origin not depend on openshift internal APIs.
/cc @deads2k
> auth: add scopes key

- config/v1/types_proxy.go
- config/v1/zz_generated.swagger_doc_generated.go
Comments regarding behavior of wildcard characters in noProxy were added prematurely. The behavior is based on 3.11 docs, but perhaps we want a different standard. Remove them until behavior is decided.
/cc @abhinavdahiya @staebler @danehans
> Remove wildcard comments from proxy.

- config/v1/types_console.go
- config/v1/zz_generated.swagger_doc_generated.go
- operator/v1/types_console.go
- operator/v1/zz_generated.swagger_doc_generated.go
Updates the console API resources documentation.  For the most part, this covers generic fields such as `spec` and `status`.
/assign @spadgett
> Update comments/docs on console resources

- operator/v1alpha1/register.go
Add the new api definition from https://github.com/openshift/api/pull/354 to register.go.
Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>
> Add ImageContentSourcePolicy to register.go

- operator/v1/doc.go
With the new version of the kubebuilder CRD generator, there is the option to set a default "required" status for fields at the package level (see https://github.com/kubernetes-sigs/controller-tools/pull/211). We have a couple generators we currently use which were specifically patched to assume everything is optional unless explicitly marked as required (this was necessary because the old kubebuilder generator did the opposite). However with this new functionality we can move toward using the upstream tool by simply setting the `+kubebuilder:validation:Optional` package-level marker.
> Set Operator API to default Optional

- config/v1/types_apiserver.go
- config/v1/zz_generated.deepcopy.go
- config/v1/zz_generated.swagger_doc_generated.go
Adds a field that allows setting additional CORSAllowedOrigins on top of the cluster-default ones.
/cc @enj
> config: Add ExtraCORSAllowedOrigins to APIServer type 

- config/v1/types_apiserver.go
- config/v1/zz_generated.swagger_doc_generated.go
The missing quotes in `json` tag caused it to be ignored.
> APIServer: fix first-letter case of AdditionalCORSAllowedOrigins

- config/v1/types_apiserver.go
- config/v1/types_authentication.go
- config/v1/types_build.go
- config/v1/types_cluster_operator.go
- config/v1/types_cluster_version.go
- config/v1/types_console.go
- config/v1/types_dns.go
- config/v1/types_feature.go
- config/v1/types_image.go
- config/v1/types_infrastructure.go
- config/v1/types_ingress.go
- config/v1/types_network.go
- config/v1/types_oauth.go
- config/v1/types_project.go
- config/v1/types_proxy.go
- config/v1/types_scheduling.go
- operator/v1/types.go
- operator/v1/types_authentication.go
- operator/v1/types_console.go
- operator/v1/types_etcd.go
- operator/v1/types_kubeapiserver.go
- operator/v1/types_kubecontrollermanager.go
- operator/v1/types_openshiftapiserver.go
- operator/v1/types_openshiftcontrollermanager.go
- operator/v1/types_scheduler.go
- operator/v1/types_serviceca.go
- operator/v1/types_servicecatalogapiserver.go
- operator/v1/types_servicecatalogcontrollermanager.go
- operator/v1alpha1/types_image_content_source_policy.go
We added the `+required` tag in our original fork of the upstream CRD generator, because in their version everything was required. Now the CRD generator has `// +kubebuilder:validation:Required` as an available tag
> Update old +required tags with +kubebuilder:validation:Required

- config/v1/types_feature.go
`CSIBlockVolume` support was enabled in 4.1 via this PR: https://github.com/openshift/api/pull/278
This feature is alpha in k8s v1.13 (Openshift 4.1), however, the feature turned beta in v1.14 (which 4.2 is based on).
Since we're looking into making this feature generally available for Openshift 4.2, I believe we should remove this line from the tech preview list of features.
CC @j-griffith, @humblec, @jarrpa, @openshift/storage
> Remove CSIBlockVolume from tech preview in 4.2

- config/v1/types_project.go
Breaks CI in https://github.com/openshift/cluster-config-operator/pull/70:
```
E0716 17:39:25.132096       1 task.go:77] error running apply for project "cluster" (22 of 426): Project.config.openshift.io "cluster" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"config.openshift.io/v1", "kind":"Project", "metadata":map[string]interface {}{"annotations":map[string]interface {}{"release.openshift.io/create-only":"true"}, "creationTimestamp":"2019-07-16T17:39:25Z", "generation":1, "name":"cluster", "uid":"a73d4dc7-a7f0-11e9-ba6c-1283e1202cf4"}, "spec":map[string]interface {}{}}: validation failure list:
spec.projectRequestMessage in body is required
```
> Make ProjectRequestMessage optional

- console/v1/types_console_link.go
The imageURL is not required, per [this discussion](https://github.com/openshift/console-operator/pull/255#discussion_r303939630).
/assign @spadgett 
@bparees (for approval)
> Make imageURL property of console link optional

- operator/v1/types_network.go
- operator/v1/zz_generated.deepcopy.go
- operator/v1/zz_generated.swagger_doc_generated.go
This is an openshift-sdn only feature.
Implementation PR: https://github.com/openshift/cluster-network-operator/pull/214
> operator/network: add EnableUnidling flag.

- config/v1/types_proxy.go
- config/v1/zz_generated.deepcopy.go
- config/v1/zz_generated.swagger_doc_generated.go
Adds `TrustedCA` to the proxy.spec for MITM HTTPS/TLS proxy support.
@bparees @derekwaynecarr @mrunalp PTAL.
> Add Trusted CA to Proxy API type

- config/v1/types_dns.go
- config/v1/zz_generated.swagger_doc_generated.go
DNS configuration is currently immutabler. Update the docs to reflect that.
> Bug 1729310: config/dns: clarify immutable status of DNS configuration

- config/v1/types_authentication.go
This would fix errors such as 
```
E0723 20:07:40.063285       1 task.go:77] error running apply for authentication "cluster" (12 of 429): Authentication.config.openshift.io "cluster" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"config.openshift.io/v1", "kind":"Authentication", "metadata":map[string]interface {}{"annotations":map[string]interface {}{"release.openshift.io/create-only":"true"}, "creationTimestamp":"2019-07-23T20:07:40Z", "generation":1, "name":"cluster", "uid":"85ec4bdd-ad85-11e9-97b9-0a76db41383e"}, "spec":map[string]interface {}{}}: validation failure list:
spec.type in body is required
```
> Set Authentication.config spec to optional

- config/v1/doc.go
This adds the package-level `optional` tag, defaulting every field to `optional` unless explicitly set with `+kubebuilder:validation:Required`
Note that this will make *all* fields optional, and component owners should take care to verify that their fields are appropriately marked. See https://jira.coreos.com/browse/MSTR-790
> Make config/v1 package default to optional in kubebuilder

- config/v1/types_operatorhub.go
- config/v1/zz_generated.swagger_doc_generated.go
- Add an option `disableAllDefaultSources` that allows a user to disable all default hub sources. We are using this flag instead of a special key (example: `HubSource{name: “*”, disabled: true}`) in `sources` to isolate the API from future changes in the direction and usage of `HubSources` in general.
- Revert `omitempty` removal from Status json tag
- Add json tag to embedded HubSource to satisfy openAPIValidation generation
- Ran `make generate-with-container`
> config/v1: add disable all option to operatorhub API

- apps/v1/generated.pb.go
- authorization/v1/generated.pb.go
- build/v1/generated.pb.go
- config/v1/types_build.go
- config/v1/zz_generated.swagger_doc_generated.go
- image/v1/generated.pb.go
- network/v1/generated.pb.go
- oauth/v1/generated.pb.go
- project/v1/generated.pb.go
- quota/v1/generated.pb.go
- route/v1/generated.pb.go
- security/v1/generated.pb.go
- template/v1/generated.pb.go
- user/v1/generated.pb.go
This fixes the description that appears in the OpenShift web console.
Also adding a deprecation notice for `AdditionalTrustedCA` - this was never used in 4.1 but technically was not removed from the API.
> Bug 1732144: Fix description of cluster build config

- operator/v1/types_network.go
- operator/v1/zz_generated.swagger_doc_generated.go
Trying to apply OpenStack Octavia to OpenShift networking models we
realized that the subnet for OpenShift Services created in OpenStack
needs to be twice the size of the subnet used by OpenShift, as Octavia
uses 2 IP's per loadbalancer - VIP (i.e. the one assigned to a Service
by OpenShift) and VRRP that is assigned by Neutron.
To address this OpenStackServiceNetwork setting is added to KuryrConfig
to serve as this broader OpenStack network CIDR. If not set
cluster-network-operator will set it to ServiceNetwork expanded by one
bit.
> Bug 1743302: Add KuryrConfig.OpenStackServiceNetwork for CNO

- config/v1/types_image.go
- config/v1/zz_generated.swagger_doc_generated.go
also fixes the casing of the field names in the godoc.
> include builds in list of image pulls impacted by image config resource

- operator/v1/types_ingress.go
* `operator/v1/types_ingress.go`: Fix the kubebuilder marker for the IngressController resource's scale subresource's `labelSelectorPath` field.
> Bug 1749581: operator/ingress: Fix scale kubebuilder marker

- config/v1/types_network.go
- config/v1/zz_generated.swagger_doc_generated.go
In https://github.com/openshift/cluster-kube-apiserver-operator/pull/564 we changed this (because it was a bad idea).
> config/network: update docs to reflect externalip default-deny

- route/v1/types.go
Add omitempty to the json struct tag to avoid emitting empty subdomain
strings when the new optional subdomain attribute is not set.
Fixes #404
> route/v1: add omitempty to subdomain struct tag

- operator/v1/types_ingress.go
The `+nullable` markers removed in this commit were never actually used
in the CRD we publish (See the history of [1] for evidence). Use of these
markers was actually a mistake (`omitempty` is sufficient).
[1] https://github.com/openshift/cluster-ingress-operator/blob/master/manifests/00-custom-resource-definition.yaml
@sttts @deads2k @damemi @Miciah
> operator/ingress: remove unnecessary +nullable markers

- operator/v1/types_ingress.go
Make the `type` field of the endpoint publishing strategy for an IngressController resource a required field.
The `type` field is a union discriminator field, and the KEP for union types [states](https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20190325-unions.md#go-tags) that a union discriminator field "CAN be optional".  The IngressController resource's `spec.endpointPublishingStrategy` field is optional, so if it is specified, then it is reasonable to expect an explicit value be specified for `spec.endpointPublishingStrategy.type`, and the ingress operator will always set an explicit value for the `status.endpointPublishingStrategy.type` field.
The ingress operator currently has a CRD that was generated using controller-tools v0.2.0-beta.1, which ignores …
> operator/ingress: Delete +optional marker on type

- config/v1/types_network.go
- operator/v1/types_network.go
cluster-config-operator generates CRDs for the config types, but it doesn't enforce that `uint32` fields have non-negative values, which can cause problems by letting people create objects that can't be unmarshaled into their corresponding golang types (https://github.com/openshift/cluster-network-operator/issues/69).
I filed https://github.com/openshift/crd-schema-gen/issues/9 about doing this automatically so this may become unnecessary eventually.
> add kubebuilder annotations for network types

- operator/v1/types_ingress.go
The `.spec.endpointPublishingStrategy.type` is intended to be required (and
that's how the field is persisted in 4.1). In the operator.openshift.io group,
fields are optional by default[1]. Use an explicit marker to maintain
compatibility.
[1] https://github.com/openshift/api/blob/master/operator/v1/doc.go
> operator/ingress: make .spec.endpointPublishingStrategy.type required

- operator/v1/types_dns.go
These fields should be required. We've been persisting them as required[1],
and metadata should reflect that.
[1] https://github.com/openshift/cluster-dns-operator/blob/release-4.2/manifests/0000_70_dns-operator_00-custom-resource-definition.yaml
> operator/dns: fix openapi spec for required fields

- config/v1/types_infrastructure.go
- config/v1/zz_generated.swagger_doc_generated.go
The newtork resources like Virtual Network and Subnets are created currently for each cluster in the cluster's resource group.
To support reusing exisitng Virtual network and Subnets for OpenShift clusters, the cluster uses pre-existing ones in a separate resource group.
`networkResourceGroupName` is the resource group that contains the Virtual network and subnets for the cluster.
The resource group for network resources is the same as cluster unless specifically specified, therefore, this field is optional.
This is based on work in PR https://github.com/openshift/installer/pull/2441
A consumer of the field is https://github.com/openshift/cloud-credential-operator/pull/122
> config/v1: add networkResourceGroupName for azure platform

- console/v1/types_console_link.go
- console/v1/types_console_notification.go
One more update for this,  the `+kubebuilder` tag needs to be on the type itself.
- Related to https://github.com/openshift/cluster-config-operator/pull/101 which fixes a codegen issue that will enable:
/cc @spadgett @bparees 
/assign @damemi
> kubebuilder tag needs to be on the type itself

- config/v1/types_feature.go
Allows masters to host end-user workloads on clouds by making masters able to be targeted by service load balancers. Disabling the legacy gate disables the logic that excluded them previously.
See https://github.com/kubernetes/enhancements/blob/master/keps/sig-architecture/2019-07-16-node-role-label-use.md
and the [compact clusters proposal](https://github.com/openshift/enhancements/pull/48) for more context.
> featuregates: Disable legacy node role exclusion for masters

- config/v1/types_feature.go
Talked to @sjenning about why LocalStorageCapacityIsolation is disabled. It was disabled for something to do with the Online use case, but we can re-enable it again.
ref: https://bugzilla.redhat.com/show_bug.cgi?id=1758434
> Bug 1758434: re-enable LocalStorageCapacityIsolation

- config/v1/types_infrastructure.go
- config/v1/zz_generated.swagger_doc_generated.go
A recent PR (#348) added the BareMetalPlatformStatus.  Add a reference
to a document that helps explain the networking architecture for the
"baremetal" platform and how these IP addresses are used.
> Add a link to baremetal networking architecture.

- console/v1/0000_10_config-operator_01_consoleyamlsample.crd.yaml
We are missing one of our extension CRDs from the generated set in `/console` subdirectory.
/cc @spadgett @bparees 
@damemi
> Generate consoleyamlsamples.console.openshift.io CRD

- Makefile
- hack/verify-crds.sh
This simply loops through the CRD yamls and uses `yq` (checked and downloaded the same way as in our `update-codegen` make targets) to see if any value is set for `metadata.description`. `yq` returns "null" if the value does not exist
> Add check to verify no metadata descriptions in CRDs

- console/v1/0000_10_consoleyamlsample.crd.yaml
- hack/verify-crds.sh
As requested in https://github.com/openshift/api/pull/490
This also adds pruning to the one console crd that was missing it, and makes a minor tweak to the verify script to print all failing CRDs before returning an error
> Add check in hack/verify-crds that pruning is enabled

- operator/v1/0000_70_console-operator.crd.yaml
Following #475, generating the `console-operator` CRD.
/cc @spadgett @jhadvig 
/cc @damemi looks like you owned review of the last one!
I do not have the line:
```
// +kubebuilder:validation:PreserveUnknownFields
```
So I am not sure why `preserveUnknownFields: false` is not in the YAML.  
Todo after merge:
> Add console-operator CRD and generate from types

- operator/v1/0000_70_console-operator.crd.yaml
- operator/v1/types_console.go
Add validation patterns to console operator structs to reflect in generated console operator CRD.
This gets us to the point that this resources is consumable. 
Follows #486. 
/cc @spadgett @damemi @bparees 
[Original CRD](https://github.com/openshift/console-operator/blob/master/manifests/00-crd-operator-config.yaml) from `console-operator` repo:
```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
name: consoles.operator.openshift.io
spec:
scope: Cluster
group: operator.openshift.io
names:
kind: Console
listKind: ConsoleList
plural: consoles
singular: console
subresources:
status: {}
versions:
- name: v1
served: true
storage: true
validation:
openAPIV3Schema:
properties:
spec:
properties:
managementState:
pattern: ^(Managed|Unmanaged|Removed|Forced)$ …
```
> Add validation patterns to console-operator structs

- operator/v1/0000_40_kube-storage-version-migrator-operator_00_config.crd.yaml
Add CRD resource definition for KubeStorageVersionMigrator types.
> add KubeStorageVersionMigrator crd.yaml

- operator/v1/types_network.go
- operator/v1/zz_generated.deepcopy.go
- operator/v1/zz_generated.swagger_doc_generated.go
This commit adds several settings to KuryrConfig structure that might be
useful for the user to fine-tune his cluster. In particular:
* EnableDebug - ability to enable debug logs on kuryr-kubernetes that
might be useful to debug complex issues.
* EnablePortPoolsPrepopulation, PoolMaxPorts, PoolMinPorts, PoolBatchPorts -
settings related to port pools feature. It might be useful to
fine-tune those values depending on how the OpenShift cluster is used.
> Add useful Kuryr settings

- console/v1/0000_10_consoleyamlsample.crd.yaml
- console/v1/types_console_yaml_sample.go
- console/v1/zz_generated.swagger_doc_generated.go
- operator/v1/0000_70_cluster-network-operator_01_crd.yaml
- Fix missing targetResource for consoleyamlsample
- regen CRDs
/assign @spadgett @bparees 
/cc @soltysh @dulek  
fyi the `cluster-network-operator` CRD also updated from `make update-codegen-crds`.
> Bug 1767926: Fix targetResource in ConsoleYAMLSample CRD

- console/v1/0000_10_consoleyamlsample.crd.yaml
- console/v1/types_console_yaml_sample.go
- console/v1/zz_generated.swagger_doc_generated.go
Snippets let you insert a partial YAML definition at the user's cursor in the console YAML editor.
/assign @bparees @benjaminapetersen 
cc @andrewballantyne @christianvogt @sspeiche
> Bug 1768542: Add `snippet` flag to ConsoleYAMLSample CRD

- config/v1/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
- config/v1/types_cluster_operator.go
- config/v1/zz_generated.swagger_doc_generated.go
The abbreviated wording was originally from 898d7e3b7c (#127).  But using the full name in these docs gives readers one less abbreviation to recognize.
> config/v1/types_cluster_operator: "the kube ecosystem" -> "the Kubernetes ecosystem"

- config/v1/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
- config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
- config/v1/types_cluster_operator.go
- config/v1/zz_generated.swagger_doc_generated.go
Leaning heavily on [the CVO docs][1].
[1]: https://github.com/openshift/cluster-version-operator/blob/cd332aa6ceb924fd49f7be7aeffce815dc81d663/docs/dev/clusteroperator.md#what-should-an-operator-report-with-clusteroperator-custom-resource
> config/v1/types_cluster_operator: ClusterOperatorStatus doc wordsmithing

- Makefile
Add "verify-codegen-crds" as a dependency to the "verify" target, and "update-codegen-crds" to the "update" target
> Bug 1767954: Add CRDs to update and verify targets

- config/v1/types_feature.go
ExperimentalCriticalPodAnnotation is not used anymore within Kubernetes 1.16. On Windows, this is reported to cause the Kubelet to exit.
@deads2k @sjenning @ravisantoshgudimetla
> Remove ExperimentalCriticalPodAnnotation from featureflags

- config/v1/types_feature.go
Removes `TLSSecurityProfile` references in `config/v1/types_feature.go` since the feature is not being gated.
/assign @deads2k 
/cc @suhanime
> Removes TLSSecurityProfile from feature gate

- config/v1/types_feature.go
This adds the SCTPSupport to the enabled-by-default feature gate flags.
> Enable SCTP feature gate

- samples/v1/0000_10_samplesconfig.crd.yaml
/assign @bparees 
/assign @adambkaplan 
forgot to include https://github.com/openshift/cluster-samples-operator/blob/master/manifests/00-crd.yaml#L14-L15 when moving the samples operator config crd to openshift/api
> add status subresource to samples config crd

- samples/v1/generated.proto
- samples/v1/types_config.go
It looks like this is needed to get rid of this error when using ./hack/update-generated-openapi.sh in openshift-apiserver:
```
E1119 16:24:32.064438   72895 openapi.go:304] Error when generating: managementState, ManagementState github.com/openshift/api/operator/v1.ManagementState
2019/11/19 16:24:32 OpenAPI code generation error: Failed executing generator: some packages had errors:
Tags in comment and struct should match for member (ManagementState) of (github.com/openshift/api/samples/v1.ConfigStatus) (type!=)
```
I dunno how this got broken, since I was not updating kube-openapi generator in here: https://github.com/openshift/openshift-apiserver/pull/44
More reading:
https://github.com/kubernetes/kube-openapi/blob/30be4d16710ac61bce31eb28a01054596fe6a9f1/pkg/generators/openapi.go#L48 …
> samples: add pathMergeKey and pathStrategy tags

- config/v1/types_cluster_operator.go
And drop the earlier, orphaned comment block.  Both of these issues slipped through my earlier 40c55f8085 (#501).
Oops, @soltysh, sorry I missed these.  Can you take another look?
/assign @soltysh
> config/v1/types_cluster_operator: Fix "Degraded indicated" -> "Degraded indicates"

- config/v1/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
- config/v1/types_cluster_operator.go
- config/v1/zz_generated.swagger_doc_generated.go
The typo was originally from 898d7e3b7c (#127).  The "any operator" bit explains why we don't want, for example, ingress-operator specific config in here.  The later `ClusterOperatorSpec` comment goes into more detail on that with its `pause` hypothetical, but a bit of extra hinting can't hurt ;).
> config/v1/types_cluster_operator: Fix "spec hold the" typo

- image/v1/generated.proto
- image/v1/types.go
- image/v1/zz_generated.swagger_doc_generated.go
End users should have a bit more info about the core image types.
Describe behavior, intended use, target audience, and some details
of API interactions.
> image: Improve godoc for image types

- imageregistry/v1/00-crd.yaml
- imageregistry/v1/types.go
This patch adds validation to the Azure's container name as already done by the type and crd on image registry operator.
I have missed these changes when I initially migrated `type` and `crd` from the operator.
> Bug 1769008: Adding missing Azure container name validation.

- go.mod
- vendor/modules.txt
replace stanzas prevent normal `go mod` vendor of require to match and that in turn impacts transitive dependency calculations downstream.
> Fix replace for go mod

- config/v1/types_feature.go
- config/v1/types_features_test.go
featuregates were vulnerable to mismatches where an intent to include features on top of default required a fully copy that runs out of date. This allows someone to describe their deltas from the default which is much easier to get right.
> prevent mismatched featuregates

- config/v1/types_feature.go
- config/v1/types_features_test.go
1.17 adds dual-stack support if you specify multiple flags for
the CIDR ranges. Since dual stack support requires config generation
enabling the feature gate does not change default behavior of the
platform.
Will enable further development and testing.
> feature: Enable the IPv6DualStack feature gate by default

- imageregistry/v1/00-crd.yaml
- imageregistry/v1/types.go
- imageregistry/v1/zz_generated.swagger_doc_generated.go
To allow us to define a rollout strategy for the image registry deployment, we create an additional parameter in ImageRegistrySpec.
> Add rolloutStategy parameter to ImageRegistrySpec

- imageregistry/v1/00-crd.yaml
- imageregistry/v1/types.go
- operator/v1/0000_80_csi_snapshot_controller_operator_01_crd.yaml
Add `omitempty` tag so empty values are not validated by the regex.
> Fix image registry's rollout parameter

- go.mod
- go.sum
- operator/v1/0000_50_cluster-authentication-operator_01_config.crd.yaml
- operator/v1/types_authentication.go
- operator/v1/zz_generated.swagger_doc_generated.go
the new field indicates whether CAS is managing OAuth related APIs. Setting this field to true will cause OAS-O to step down
required to implement https://github.com/openshift/cluster-openshift-apiserver-operator/pull/294
> adds a new ManagingOAuthAPIServer field to authentication's operator status field

- operator/v1/0000_50_ingress-operator_00-custom-resource-definition.yaml
- operator/v1/types_ingress.go
- operator/v1/zz_generated.swagger_doc_generated.go
Follow-up to #559.
* `operator/v1/types_ingress.go` (`IngressControllerSpec`): Change "The empty" to "If empty".
(`RouteAdmissionPolicy`): Capitalize the first word of the description for "InterNamespaceAllowed".
* `operator/v1/0000_50_ingress-operator_00-custom-resource-definition.yaml`:
> operator/ingress: Fix route admission godoc typos

- config/v1/0000_10_config-operator_01_image.crd.yaml
- config/v1/types_image.go
- config/v1/zz_generated.swagger_doc_generated.go
* Update godoc for image config API to be more descriptive and inclusive.
> Clarify image config doc

- build/v1/generated.proto
- build/v1/types.go
- build/v1/zz_generated.swagger_doc_generated.go
@openshift/openshift-team-developer-experience @akram @siamaksade FYI
/assign @bparees 
(@adambkaplan is not in the OWNERS files that I see)
> Bug 1785289: add deprecaction notice for build pipeline strategy

- README.md
Adds information, links, and steps to set up and use the crd schema generator
Fixes #572 
/cc @dhellmann
> Bug 1798482: Add CRD generator documentation to Readme

- config/v1/types_feature.go
- config/v1/types_features_test.go
We are not going to ship dual stack support in 4.4 and enabling this flag bricks the clusters as the service object ip family field is being defaulted (operators with old clients are affected).
> Bug 1794376: config: disable IPv6DualStack feature flag

- config/v1/0000_10_config-operator_01_apiserver.crd.yaml
- config/v1/types_tlssecurityprofile.go
- operator/v1/0000_50_ingress-operator_00-custom-resource-definition.yaml
- operator/v1/types_ingress.go
Add enum validations to types which should have them.
cc @Miciah @damemi @sttts @deads2k
> Bug 1801543: Add missing enum validations

- config/v1/types_operatorhub.go
The OperatorHub type definition is missing an additional `+genclient` marker comment required for Kubernetes client generation. As a result, the generated client is not available in `openshift/client-go`.
> Bug 1816483: fix(codegen): add missing client tag to operatorhub config type

- route/v1/types.go
These are written out as "empty" values, which means that tools like ArgoCD
fail to synchronise the state of the resource because they're comparing fields against the GitOps resource.
> Add omitempty tags to Route resources.

- config/v1/0000_10_config-operator_01_authentication.crd.yaml
- config/v1/types_authentication.go
- config/v1/zz_generated.swagger_doc_generated.go
The default for Authentication.ServiceAccountIssuer is updated to point to the internal dns name of the kube apiserver to ensure compatibility with the ServiceAccountIssuerDiscovery feature added in kube 1.18.
/cc @sttts @stlaz
> Bug 1819246: Fix the default for Authentication.ServiceAccountIssuer

- config/v1/types_feature.go
- config/v1/types_features_test.go
This is a new feature for kube-apiserver.  We want soak time.  If it performs well, we may well keep this on.
/hold
holding for proof
> enable priority and fairness for kube-apiserver

- config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
- config/v1/types_infrastructure.go
There are various platform specific status fields for infrastructure. And all of these not not user modifyable.
These fields are setup at the install-time and never changed.
```
aws:
description: AWS contains settings specific to the Amazon Web Services
infrastructure provider.
type: object
properties:
region:
description: region holds the default AWS region for new AWS
resources created by the cluster.
type: string
azure:
description: Azure contains settings specific to the Azure infrastructure
provider.
type: object
properties:
networkResourceGroupName:
description: networkResourceGroupName is the Resource Group
for network resources like the Virtual Network and Subnets
used by the cluster. If empty, the value is same as ResourceGroupName.
type: string
resourceGroupName:
description: …
```
> config/v1: add status subresource for infrstrastructure

- config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
- config/v1/types_infrastructure.go
- config/v1/zz_generated.swagger_doc_generated.go
depends on #599 please review that first.
The cloudConfig is generated by the stitching together the user specifed config and the other platform spec in the infrstructure object.
>  config/v1/types_infrastructure.go: add kube cloud config to status

- build/v1/types.go
The lack of omitempty makes them appear as `null`, which is annoying, e.G.:
```
$ k get build -n ci-op-si6igpvd src -o yaml|grep null
nodeSelector: null
- as: null
```
> Bug 1826523: Builds: Make a bunch of fields omitempty

- README.md
These live in build-machinery-go now
> Replace library-go references with build-machinery-go for CRD gen readme

- config/v1/0000_10_config-operator_01_oauth.crd.yaml
- config/v1/types_oauth.go
- config/v1/zz_generated.swagger_doc_generated.go
Adding this field to the API while we were not ready to wire code support for it was a mistake.
/assign @marun
> Bug 1816991: Mark accessTokenInactivitiyTimeoutSecounds deprecated

- operatoringress/v1/0000_50_dns-record.yaml
- operatoringress/v1/types.go
- operatoringress/v1/zz_generated.swagger_doc_generated.go
* `operatoringress/v1/types.go` (`DNSRecordStatus`): Add `ObservedGeneration` field.
* `operatoringress/v1/0000_50_dns-record.yaml`: Regenerate.
> Bug 1809354: operatoringress/dnsrecord: Add observedGeneration

- config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
- config/v1/types_infrastructure.go
- config/v1/zz_generated.swagger_doc_generated.go
Add the `.status.azure.cloudName` field to the Infrastructure type in config. This field informs in which Azure cloud environment the cluster is installed and consequently which Azure API endpoint should be used when communicating via the Azure SDK.
See https://github.com/openshift/enhancements/pull/321
https://issues.redhat.com/browse/CORS-1441
> config: support for other Azure cloud environments

- OWNERS
Prow auto-assigns PR reviewers _only_ out of `reviewers`, not out of `approvers`. This means that if you don't redundantly list the `approvers` in the `reviewers` section, no approver will ever be assigned to do reviews, which was probably not the intent here...
Not sure who the right person to assign this to is so I'll let one of the reviewers figure it out. :slightly_smiling_face:
> add approvers to reviewers

- config/v1/types_feature.go
We cannot yet enable the `IPv6DualStack` feature gate because it's still broken upstream but we'll need it for dual-stack development/testing. This would be expected to go away in 4.6 when we enable the feature gate by default.
I just copied the "CANNOT BE UNDONE, and PREVENTS UPGRADES" text from one of the other unsupported feature sets; AFAICT that it not actually implemented for other unsupported feature sets either.
> config: add an IPv6DualStackNoUpgrade feature set

- imageregistry/v1/00-crd.yaml
- imageregistry/v1/01-crd.yaml
- imageregistry/v1/types.go
- imageregistry/v1/types_imagepruner.go
Adding a Format tag to validate "metav1.Duration" types on Image
Registry types.
> Bug 1833245: Validating duration fields on image registry types

- config/v1/0000_10_config-operator_01_network.crd.yaml
- config/v1/types_network.go
- config/v1/zz_generated.swagger_doc_generated.go
This enables the specification and configuration of a custom
service node port range for a cluster.
> config/network: Add a service node port range parameter to the network spec

- openshiftcontrolplane/v1/types.go
- openshiftcontrolplane/v1/zz_generated.deepcopy.go
- openshiftcontrolplane/v1/zz_generated.swagger_doc_generated.go
We need to update openshiftcontrolplane/v1/BuildOverridesConfig/ForcePull to be in line with  config/v1/BuildOverrides/ForcePull addition from https://github.com/openshift/api/pull/673 since it gets a copy of that value at https://github.com/openshift/openshift-controller-manager/blob/master/pkg/cmd/controller/build.go#L76 and we need to still be able to see if it was set by an administrator or not.
This seems to be leftover code from 3.x as having a node cache on 4.x is not currently supported, and it seems that the only place this code is used within OpenShift is in the openshift-controller-manager, so it should be pretty safe to update and not break everything.  
https://issues.redhat.com/browse/BUILD-96
> Updating ForcePull in controlplane to be a pointer

- config/v1/types_oauth.go
- osin/v1/types.go
When authorize token max age and access token max fields are using the default values, they will still be transmitted over the wire. This PR intends to change that by using `omitempty` tags.
> Add omitempty tags to oauth and osin config optional fields

- operator/v1/types_network.go
- operator/v1/zz_generated.deepcopy.go
- operator/v1/zz_generated.swagger_doc_generated.go
the vxlan port that was used when we started working on the windows/linux hybrid
networking solution (4789) is required to be left open by some of our supported
platforms. Make the VXLAN port configurable so that it can be set and will no longer
interfere with enabling cloud platforms
> adding HybridOverlayVXLANPort to HybridOverlayConfig stuct

- hack/update-protobuf.sh
We have higher versions of protobuf available.
This patch avoids build issue with higher versions like 3.11.
Signed-off-by: Douglas Schilling Landgraf <dougsland@redhat.com>
> hack: fix protobuf validation

- config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
- config/v1/types_infrastructure.go
- config/v1/zz_generated.swagger_doc_generated.go
- operator/v1/0000_70_cluster-network-operator_01_crd.yaml
In 4.6, this field is no longer set or honored.
See also:
https://github.com/openshift/machine-config-operator/commit/c4bf4e43ca809c3bc346d9bb490ccf33567b18fb
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1846330
Signed-off-by: Douglas Schilling Landgraf <dougsland@redhat.com>
> ovirt: add a comment about DNS VIP field

- go.mod
- go.sum
- vendor/github.com/openshift/build-machinery-go/go.mod
- vendor/github.com/openshift/build-machinery-go/make/operator.example.mk.help.log
- vendor/github.com/openshift/build-machinery-go/make/targets/openshift/crd-schema-gen.mk
- vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/telepresence.mk
- vendor/github.com/openshift/build-machinery-go/scripts/run-telepresence.sh
- vendor/modules.txt
The verify-codegen-crds script was only checking against files that end in `.crd.yaml`.
This bump loosens it to just `crd.yaml`
> bump(build-machinery-go): Loosen CRD extension check for codegen-verify

- config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
- config/v1/types_infrastructure.go
- config/v1/zz_generated.swagger_doc_generated.go
#https://github.com/openshift/cluster-kube-apiserver-operator/pull/855#
> port details for APIServerURL

- operatorcontrolplane/v1alpha1/0000_10-pod-network-connectivity-check.crd.yaml
- operatorcontrolplane/v1alpha1/types_conditioncheck.go
- operatorcontrolplane/v1alpha1/zz_generated.deepcopy.go
- operatorcontrolplane/v1alpha1/zz_generated.swagger_doc_generated.go
Keeps a list of important success/failure log entries related to an outage associated with the outage itself to provide context when reviewing the logs long after the original entries have been rotated out.
Example:
```yaml
status:
outages:
- end: "2020-07-14T02:12:40Z"
start: "2020-07-14T01:23:03Z"
logs:
- latency: 113.463µs
message: 'tcp connection to 10.128.0.38:8443 succeeded'
reason: TCPConnect
success: true
time: "2020-07-14T02:12:40Z"
- latency: 858.991937ms
message: 'dial tcp 10.128.0.38:8443: connect: no route to host'
reason: TCPConnectError
success: false
time: "2020-07-14T01:23:03Z"
```
> v1alpha1/podnetworkconnectivitychecks: add logs to outages

- config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
- config/v1/types_infrastructure.go
- config/v1/zz_generated.swagger_doc_generated.go
We've declared the default ports for apiServerURL since afb690a81c (#646).  Echo that for `apiServerInternalURL`.  We don't have to call this out explicitly, since [the IANA URI scheme registry][1] links out to RFC 7230 for [http][2] and [https][3], which have:
> If the port subcomponent is empty or not given, TCP port 80 (the reserved port for WWW services) is the default.
and:
> All of the requirements listed above for the "http" scheme are also requirements for the "https" scheme, except that TCP port 443 is the default if the port subcomponent is empty or not given...
respectively.  But echoing those defaults locally doesn't hurt.
Autogenerated bumps via:
```console
$ hack/update-swagger-docs.sh
$ make update-codegen-crds
```
[1]: …
> config/v1/types_infrastructure: Default ports for apiServerInternalURL too

- operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
- operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-merge-patch
- operator/v1/types_csi_cluster_driver.go
Fix a typo in ebs csi driver name. 
cc @openshift/sig-storage @deads2k @sttts
> Fix typo in ebs csi driver name

- operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
- operator/v1/types_ingress.go
Adds constants for supported load balancer provider types.
In support of [NE-138](https://issues.redhat.com/browse/NE-138).
/assign @knobunc 
/cc @sttts @deads2k @frobware
> Adds LB provider constants to operator/ingress API

- imageregistry/v1/01-crd.yaml
- imageregistry/v1/types_imagepruner.go
- imageregistry/v1/zz_generated.swagger_doc_generated.go
Invalid image references in pods/builds/etc cause the image pruner to abort its job. This is the safest approach because even if the pruner has bugs, it won't delete anything that is in use. But as there is no validation for image references, some clusters have invalid references because of their users mistakes and the pruner should ignore them.
The default value for `ignoreInvalidRefs` is `false` to maintain backward compatibility. But the operator will bootstrap the configuration object with `ignoreInvalidRefs: true`. So new clusters will have `ignoreInvalidRefs: true`, upgraded from 4.5 clusters will have `ignoreInvalidRefs: false`.
> IR-119: Add IgnoreInvalidRefs for image pruner

- operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
- operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml-merge-patch
- operator/v1/types_ingress.go
- operator/v1/zz_generated.swagger_doc_generated.go
Relax validation on `spec.logging.access.httpCaptureCookies` to allow the `name` and `namePrefix` subfields to be empty.
* `operator/v1/types_ingress.go` (`IngressControllerCaptureHTTPCookie`): Relax validation by allowing `Name` and `NamePrefix` to be empty.
* `operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml-merge-patch`: Delete validation added in #687.
* `operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml`:
----
Turns out what worked with `oc` commands does not work with client-go.  Specifying `matchType: Exact` and `name: foo` worked with `oc apply` but failed when updating using client-go:
IngressController.operator.openshift.io "cookiecapture" is invalid: …
> operator/ingress: Fix up HTTP cookie capture API

- config/v1/0000_10_config-operator_01_network.crd.yaml
- config/v1/types_network.go
- config/v1/zz_generated.swagger_doc_generated.go
- operator/v1/0000_70_cluster-network-operator_01_crd.yaml
- operator/v1/types_network.go
- operator/v1/zz_generated.swagger_doc_generated.go
For plugins like which don't use the hostPrefix for anything, it does not
make sense to force customers to set specific values just to pass validation.
These plugins should be able to unset (0) the hostPrefix and not have to worry
about it. This patch makes hostPrefix optional. However note that if the
hostPrefix is set, the validation will happen and for the plugins like
OpenShiftSDN and OVNKubernetes which require hostPrefix, the validation
will happen irrespective of whether it is set or not.
Signed-off-by: Surya Seetharaman <suryaseetharaman.9@gmail.com>
> Bug 1852112: Make hostPrefix optional for the sake of non-(sdn/ovn) plugins

- imageregistry/v1/00-crd.yaml
- imageregistry/v1/types.go
- imageregistry/v1/zz_generated.swagger_doc_generated.go
ManagementState indicates if the operartor should or not manage the underlying storage. If "Unmanaged" operator won't attempt to remove the storage when its state is set to "Removed".
> Bug 1833109: Adding ManagementState property to storage

- operatorcontrolplane/v1alpha1/0000_10-pod-network-connectivity-check.crd.yaml
This is matches https://github.com/openshift/enhancements/pull/414 and doesn't change existing behavior
tagging based on previous one.
> bug 1871890: add current profile annotations to CVO manifests

- imageregistry/v1/00-crd.yaml
- imageregistry/v1/01-crd.yaml
Some of our types now inherit the Default directive. This directive is incompatible with v1beta1. This PR migrates imageregistry CRDs to v1 instead. The error we are seeing without this migration:
`cannot set default values in apiextensions.k8s.io/v1beta1 CRDs, must use apiextensions.k8s.io/v1`
Default directive was introduced through https://github.com/openshift/api/commit/e9ece8d38ce61a4358550ade3ce33e6baf055f76
> Bug 1808118: Migrating imageregistry to extensions v1

- imageregistry/v1/00-crd.yaml
- imageregistry/v1/types.go
Logging has been deprecated in favour of LogLevel, therefore this field
is now optional and should so be updated on api accordingly.
> Bug 1808118: Making logging parameter optional

- operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
This got broken while moving to v1.
> Bug 1874613: operator/v1: fix scope of ingresscontrollers to be namespaced

- imageregistry/v1/01-crd.yaml
- imageregistry/v1/types_imagepruner.go
- imageregistry/v1/zz_generated.swagger_doc_generated.go
Today there is no way to change the log level of the pruner. It makes it harder to investigate the pruner problems.
> Bug 1879592: Add logLevel to imagepruners.imageregistry.operator.openshift.io

- operatorcontrolplane/v1alpha1/0000_10-pod-network-connectivity-check.crd.yaml
As v1beta1 CRD without `preserveUnknownFields: false` the CRD was not structural and hence `oc explain` did not work.
> Bug 1880786: operatorcontrolplane: make structural

- go.mod
- vendor/modules.txt
Attempting to run `make update` for golang 1.15 resulted in the following error:
```
<snip>
hack/update-protobuf.sh
without -mod=vendor, directory /home/maru/src/mocp/lib/api/vendor/k8s.io/code-generator/cmd/go-to-protobuf has no package path
make: *** [Makefile:50: update-scripts] Error 1
```
Updating the golang version in go.mod and updating the vendoring seems to resolve this.
> Bug 1878163: Update vendoring for golang 1.15

- operator/v1/0000_50_service-ca-operator_02_crd.yaml
these got accidentally removed back in https://github.com/openshift/api/commit/fdbff4bcb56c5263cc7b8a740a3684ca9f4ba116
(+ adding listKind which was not present previoously)
> Bug 1873043: bring back service-ca crd names

- imageregistry/v1/00-crd.yaml
- imageregistry/v1/01-crd.yaml
- operator/v1/0000_10_config-operator_01_config.crd.yaml
- operator/v1/0000_20_etcd-operator_01.crd.yaml
- operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml
- operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml
- operator/v1/0000_25_kube-scheduler-operator_01_config.crd.yaml
- operator/v1/0000_30_openshift-apiserver-operator_01_config.crd.yaml
- operator/v1/0000_40_cloud-credential-operator_00_config.crd.yaml
- operator/v1/0000_40_kube-storage-version-migrator-operator_00_config.crd.yaml
- operator/v1/0000_50_cluster-authentication-operator_01_config.crd.yaml
- operator/v1/0000_50_cluster-openshift-controller-manager-operator_02_config.crd.yaml
- operator/v1/0000_50_cluster_storage_operator_01_crd.yaml
- operator/v1/0000_50_service-ca-operator_02_crd.yaml
- operator/v1/0000_70_cluster-network-operator_01_crd.yaml
- operator/v1/0000_70_console-operator.crd.yaml
- operator/v1/0000_80_csi_snapshot_controller_operator_01_crd.yaml
- operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
- operator/v1/types.go
- operator/v1/zz_generated.swagger_doc_generated.go
As it is stated on OperatorSpec.LogLevel documentation valid values for the type LogLevel are Normal, Debug, Trace and TraceAll. Adding pattern validation for the LogLevel type seems to make sense.
This affected multiple CRDs, not sure if we can simply enforce this here or what would be the right approach to make sure all other operators comply with them. Other than that I am not sure these validations were omitted on purpose due some unknown reason.
> Bug 1878040: Validations for LogLevel fields

- operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
Restore the IngressController CRD's "scale" subresource.
#720 inadvertently deleted the "scale" subresource.
* `operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml`: Add `spec.versions[].subresources.scale`.
> Bug 1883701: operator/ingress: Restore scale subresource

- operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
- operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
- operator/v1/types_csi_cluster_driver.go
In OpenShift 4.7 we start using Cinder CSI driver, so we have to register the component along with the other CSI drivers.
> Storage: register Cinder CSI driver

- operator/v1/0000_70_cluster-network-operator_01_crd.yaml
- operator/v1/types_network.go
- operator/v1/zz_generated.swagger_doc_generated.go
In older releases, it was sometimes necessary for users to tweak kube-proxy's `iptablesSyncPeriod` to strike the right balance between "recovering from errors promptly" and "not causing errors constantly and totally breaking everything". With the rewrite of iptables monitoring in kube 1.18 this is no longer necessary, and modifying `iptablesSyncPeriod` is no longer particularly useful, so this updates the API docs to indicate that. (I've filed an openshift-docs PR too.)
In theory this could be backported as far as 4.3 but it's probably not worth bothering.
/cc @juanluisvaladas 
/assign @knobunc
> Bug 1880856: operator/network: update docs on iptablesSyncPeriod

- route/v1/generated.proto
- route/v1/types.go
- route/v1/zz_generated.swagger_doc_generated.go
Without this PR, finding out the possible values requires to check on the docs:
```
$ k explain route.spec.tls.termination
KIND:     Route
VERSION:  route.openshift.io/v1
FIELD:    termination <string>
DESCRIPTION:
termination indicates termination type.
```
After this PR, a list of possible values and a brief explanation will be in the `kubectl describe` output
> Route: Document possible values for spec.tls.termination

- config/v1/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
- config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
- config/v1/types_cluster_operator.go
- config/v1/zz_generated.swagger_doc_generated.go
@deads2k  has been making the rounds asking for newline rendering, e.g. in openshift/installer#4242.  Regardless of how that particular effort works out, make it clear to both ClusterOperator readers and writers that LF characters may be part of the message string (for example, HTML renderings should replace them with `<br/>`).
I'd personally prefer leaning on an existing markup language like "message strings are Markdown", although this LF rule will exclude Markdown going forward, because [the Markdown spec has][2]:
> A paragraph is simply one or more consecutive lines of text, separated by one or more blank lines. (A blank line is any line that looks like a blank line — a line containing nothing but spaces or tabs is considered blank.) Normal paragraphs should not be indented with …
> config/v1/types_cluster_operator: Document newline inclusion

- network/v1/001-clusternetwork-crd.yaml
- network/v1/002-hostsubnet-crd.yaml
- network/v1/003-netnamespace-crd.yaml
- network/v1/004-egressnetworkpolicy-crd.yaml
When running CRD validation against all CRDs (https://github.com/openshift/api/pull/743), these 4 fail due to not having a structural schema with pruning enabled. This switch to v1 will be required by k8s 1.22
> Bug 1881636: Switch networking CRDs to apiextensions/v1

- Makefile
- hack/verify-crds.sh
As noticed in https://github.com/openshift/api/pull/741, we currently need to manually add new groups to this list or they'll miss verification. This checks against all CRDs in all directories
> Run verify-crds.sh against all CRDs

- operator/v1/0000_40_cloud-credential-operator_00_config.crd.yaml
This is matches openshift/enhancements#414 and doesn't change existing behavior
---
It was missing in the original PR https://github.com/openshift/api/pull/722 and is required for https://github.com/openshift/cloud-credential-operator/pull/261
> add current profile annotations to CVO manifests

- config/v1/0000_10_config-operator_01_ingress.crd.yaml
- config/v1/types_ingress.go
- config/v1/zz_generated.swagger_doc_generated.go
This relates to https://github.com/openshift/enhancements/pull/432 and [RFE-952](https://issues.redhat.com/browse/RFE-952)
This adds an optional AppsDomain to the Ingress CR to support setting a custom domain (post install) for routes where the Host field is not specified.
> Add optional AppsDomain to Ingress CR

- config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
- config/v1/types_infrastructure.go
- config/v1/zz_generated.swagger_doc_generated.go
From OCP 4.4 onwards, etcd component uses ip addresses to for discovering etcd servers and peers, rendering the etcdDiscoveryDomain unused. Marking it as optional in the api.
> Bug 1813012: etcdDiscoveryDomain is not used to fetch the SRV records

- operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
- operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
- operator/v1/types_csi_cluster_driver.go
In OCP 4.7 we're going to deploy the GCP PD CSI Driver by default.
> Add GCP PD CSI Driver to ClusterCSIDriver's enum

- config/v1/0000_10_config-operator_01_image.crd.yaml
- config/v1/types_image.go
- config/v1/zz_generated.deepcopy.go
- config/v1/zz_generated.swagger_doc_generated.go
Add the containerRuntimeSearchRegistries option to the
image.config.openshift.io CRD so that users can update
the list of registries to be searched when pulling using
short names.
Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>
edit: bparees
api implementation of https://github.com/openshift/enhancements/pull/378
RFE: https://issues.redhat.com/browse/IR-142
> Add ContainerRuntimeSearchRegistries under RegistrySources

- helm/v1beta1/0000_10-helm-chart-repository.crd.yaml
- helm/v1beta1/types_helm.go
The default Red Hat repo is delivered as a part of console operator payload:
https://github.com/openshift/console-operator/blob/master/manifests/01-helm.yaml
and since these resource are monitored by CVO, it is not possible to remove the default
configuration, and many customers are asking for exactly that.
In order to solve the customer request, `disabled` field is added to `HelmChartRepository`.
If set to true, that repo will be ignored/skipped in all relevant Helm operations.
At the same time, other cluster components (e.g. console UI) might use the new flag
to enable/disable some parts of UI.
> Add `disabled` field to `HelmChartRepository`

- apps/v1/generated.proto
- apps/v1/types.go
- build/v1/generated.proto
- build/v1/types.go
- user/v1/generated.proto
- user/v1/types.go
Based on our apiserver we don't require any of these field being set and we correctly try to read the type from other fields, namely:
- `BuildSource` validation (https://github.com/openshift/openshift-apiserver/blob/5ea157ecf46924ff6aa52d0aa6a025c2f57d97fc/pkg/build/apis/build/validation/validation.go#L175-L239) and partial defaulting (https://github.com/openshift/openshift-apiserver/blob/5ea157ecf46924ff6aa52d0aa6a025c2f57d97fc/pkg/build/apis/build/v1/defaults.go#L11-L15)
- `BuildStrategy` validation (https://github.com/openshift/openshift-apiserver/blob/5ea157ecf46924ff6aa52d0aa6a025c2f57d97fc/pkg/build/apis/build/validation/validation.go#L483-L517) and partial defaulting (https://github.com/openshift/openshift-apiserver/blob/5ea157ecf46924ff6aa52d0aa6a025c2f57d97fc/pkg/build/apis/build/ …
> Add missing optional for BuildSourceType, BuildStrategyType and Identities

- operator/v1/0000_70_cluster-network-operator_01_crd.yaml
- operator/v1/types_network.go
- operator/v1/zz_generated.swagger_doc_generated.go
Remove requirement to set "enable" flag.
Signed-off-by: Mark Gray <mark.d.gray@redhat.com>
> types_network: Change API that enables IPsec

- config/v1/0000_10_config-operator_01_image.crd.yaml
- config/v1/types_image.go
The uniqueItems validation is causing a failure when the cluster-config-operator
is rendering the CRD. So remove that validation.
Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>
> Remove uniqueItems validation from containerRuntimeSearchRegistries

- config/v1/types_scheduling.go
Backporting https://github.com/openshift/api/pull/804
> config/v1/scheduling: fix typo in HighNodeUtililzation

- config/v1/0000_10_config-operator_01_scheduler.crd.yaml
v1beta1 does not know `default` keyword
> Bump schedulers.config.openshift.io CRD to v1

- config/v1/types_feature.go
- config/v1/types_features_test.go
This will allow our kube-apiserver to supply selflinks for one extra release in 4.7.  We will merge https://github.com/openshift/api/pull/826 that reverts this change as soon as master opens for 4.8.  We must re-align to upstream because the upstream code will be gone and not available to turn back on.
> Bug 1907373: bring selflinks back for 4.7, they will be removed in 4.8

- config/v1/0000_10_config-operator_01_scheduler.crd.yaml
- config/v1/types_scheduling.go
Since scheduler profiles are still Tech Preview, this shouldn't have a default yet
> Bug 1920619: Remove default Profile for scheduler

- project/v1/generated.proto
- project/v1/types.go
- project/v1/zz_generated.swagger_doc_generated.go
This fixes a typo in ProjectRequest.
So I think this updates fixes this here:
https://docs.openshift.com/container-platform/4.6/rest_api/project_apis/projectrequest-project-openshift-io-v1.html
> Fix typo in ProjectRequest

- config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
- config/v1/types_infrastructure.go
- config/v1/zz_generated.swagger_doc_generated.go
Implements enhancement https://github.com/openshift/enhancements/pull/555
Signed-off-by: Ravid Brown <ravid@redhat.com>
> Add HighAvailabilityMode field to 'infrastructure' CRD

- operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
- operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
- operator/v1/types_csi_cluster_driver.go
This includes the Azure Disk CSI driver in the list of cluster drivers. It's needed to begin introducing the Azure Disk CSI Driver as tech preview.
> Include Azure Disk CSI in CSI Cluster Drivers

- operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
- operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
- operator/v1/types_csi_cluster_driver.go
This change is part of [CNV-9798](https://issues.redhat.com/browse/CNV-9798) - Update CSO to deploy Kubevirt CSI driver operator.
It is needed to enable tenant kubevirt clusters consume PVs from the infra OCP cluster
> Add Kubevirt CSI Driver to ClusterCSIDriver's enum

- build/v1/generated.proto
- build/v1/types.go
- build/v1/zz_generated.swagger_doc_generated.go
Had to look this up in the code, we can't really expect users to do that.
> Buildconfig: Document valid values for spec.triggers.type

- operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
- operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
- operator/v1/types_csi_cluster_driver.go
This is part of the work required to add a CSI driver operator for vSphere (Tech Preview) in OCP 4.8:
https:// issues.redhat.com/browse/STOR-434
> Include vSphere CSI Driver in clustercsidrivers

- config/v1/types_feature.go
- config/v1/types_features_test.go
SCTP is GA in 1.20 and the feature gate is now a no-op.
(FWIW it doesn't matter if this merges before the 1.20 rebase since it was already enabled-by-default in 1.19 anyway.)
/assign @knobunc
> SCTP is GA, so no longer feature-gated

- operatoringress/v1/0000_50_dns-record.yaml
spec.scope could be empty in CRD v1beta1 definitions, but it's required to be either `Cluster` or `Namespaced` in v1. This wasn't caught by CI in my earlier PR (#861) because the ingress operator keeps a copy of this CRD that needs to be manually updated before the changes actually take effect.
The companion PR for this in ingress operator can be found [here](https://github.com/openshift/cluster-ingress-operator/pull/575)
> Bug 1928931: Set spec.scope for DNSRecord CRD

- operator/v1/types_ingress.go
Add `omitempty` to the json options for `HeaderBufferBytes` and `HeaderBufferMaxRewriteBytes`. This is needed when calling the
IngressController's DeepCopy funcs to ensure that empty `HeaderBuffer*` values aren't defaulted to `0`, which violates the enforced minimum integer values (and thus breaks subsequent resource updates).
> operator/ingress: Fix up Tunable Buffer Sizes API

- config/v1/types_feature.go
- config/v1/types_features_test.go
This adds the DownwardAPIHugePages to the enabled-by-default feature gate flags.
Signed-off-by: Billy McFall <22157057+Billy99@users.noreply.github.com>
> Bug 1908068: Enable DownwardAPIHugePages feature gate

- operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
- operator/v1/types_ingress.go
- operator/v1/zz_generated.swagger_doc_generated.go
This PR implements [NE-573](https://issues.redhat.com/browse/NE-573).
* `operator/v1/types_ingress.go` (`HostNetworkStrategy`, `NodePortStrategy`): Add `Protocol` fields with type `IngressControllerProtocol`.
(`IngressControllerProtocol`): New type.  Specify whether PROXY protocol is enabled or not.
* `operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml`:
> operator/ingress: Add PROXY protocol API

- config/v1/types_feature.go
Azure Disk and vSphere CSI drivers are introduced in OCP 4.8 as tech preview and we want to have them explicitly enabled behind TechPreviewNoUpgrade FeatureSet.
Note that these are OCP feature gates, observed only by cluster-storage-operator. I checked that kube-controller-manager and other Kubernetes components ignore them and only log "unrecognized feature gate: CSIDriverAzureDisk".
> Add feature gates for tech preview CSI drivers

- operator/v1/0000_70_cluster-network-operator_01_crd.yaml
- operator/v1/types_network.go
- operator/v1/zz_generated.deepcopy.go
- operator/v1/zz_generated.swagger_doc_generated.go
When using a Provider Network for the Machines
the same MTU is attempted to be used for the
Tenant Networks of the Pods, which can be considered
too big by Neutron. A new option is being included
to allow the user to set the desired MTU for the Pods
Network to avoid such scenario.
> Include MTU option for KuryrConfig

- operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
- operator/v1/types_ingress.go
- operator/v1/zz_generated.deepcopy.go
- operator/v1/zz_generated.swagger_doc_generated.go
Add a `spec.unsupportedConfigOverrides` field to the IngressController API to accommodate unsupported configuration overrides.
This PR resolves [NE-549](https://issues.redhat.com/browse/NE-549).
* `operator/v1/types_ingress.go` (`IngressControllerSpec`): Add an `UnsupportedConfigOverrides` field with type `runtime.RawExtension`.
* `operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml`:
* `operator/v1/zz_generated.deepcopy.go`:
---
This new API field supersedes the feature gate that https://github.com/openshift/api/pull/872 proposed, based on discussion with @deads2k, @derekwaynecarr, and @sgreene570.
> operator/ingress: Add unsupportedConfigOverrides

- route/v1/types.go
This PR implements [NE-574](https://issues.redhat.com/browse/NE-574).
* `route/v1/types.go` (`IngressToRouteIngressClassControllerName`): New const. Define the name of the ingress-to-route controller.  This name can be used for the `spec.controller` field of ingressclasses.
> route: Define the ingress-to-route controller name

- config/v1/types_feature.go
We want to have CSI migration for AWS and Cinder as tech preview in 4.8.
KEP: https://github.com/openshift/enhancements/pull/549/ 
cc @openshift/storage @Danil-Grigorev
> Add CSI migration to TechPreviewNoUpgrade

- cloudnetwork/v1/generated.proto
- cloudnetwork/v1/types.go
The fact that this marker was missing was leading to client-gen not generating any of its managed files, see PR: https://github.com/openshift/client-go/pull/181
I have tested this on a local version of https://github.com/openshift/client-go/pull/181 and it works now. 
/assign @sttts
> Fix: cloud-network-config-controller with genclient marker for client-gen

- config/v1/0000_10_config-operator_01_dns.crd.yaml
- config/v1/0000_10_config-operator_01_ingress.crd.yaml
config/v1/0000_10_config-operator_01_ingress.crd.yaml:
Move the `ingresses.config.openshift.io` CRD to use
`apiextensions.k8s.io/v1` in place of `apiextensions.k8s.io/v1beta`.
config/v1/0000_10_config-operator_01_dns.crd.yaml:
Move the `dnses.config.openshift.io` CRD to use
`apiextensions.k8s.io/v1` in place of `apiextensions.k8s.io/v1beta`.
This commit resolves Bug 1947800.
> Bug 1947800: config/v1: Switch Network Edge CRDs to CRD v1

- operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
- operator/v1/0000_70_dns-operator_00-custom-resource-definition.yaml
- operator/v1/types_dns.go
- operator/v1/types_ingress.go
- operator/v1/zz_generated.swagger_doc_generated.go
Replace "beta.kuberneta.io/os" with "kubernetes.io/os" in the dns/ingress node selector description.
follow-up to  https://github.com/openshift/api/pull/870
@Miciah  Could you please take a look? thanks.
> Bug 1950270: Use "kubernetes.io/os" in the dns/ingress node selector description

- apiserver/v1/types_apirequestcount.go
otherwise genereting OpenAPI fails with: "Tags in comment and struct should match for member (Conditions) of (github.com/openshift/api/apiserver/v1.APIRequestCountStatus)"
> Bug 1948311: APIRequestCountStatus.Conditions makes sure that tags and comments align

- apiserver/v1/apiserver.openshift.io_apirequestcount.yaml
- apiserver/v1/types_apirequestcount.go
trying to address
> 2021-04-19T13:13:50.448284583Z E0419 13:13:50.448191      18 apiaccess_count_controller.go:112] APIRequestCount.apiserver.openshift.io "apiservers.v1.config.openshift.io" is invalid: status.removedInRelease: Invalid value: "": status.removedInRelease in body should match '^[0-9][0-9]*\.[0-9][0-9]*$'
> bug 1949306: make removedInRelease setable to empty string

- operator/v1/0000_70_cluster-network-operator_01_crd.yaml
- operator/v1/types_network.go
- operator/v1/zz_generated.swagger_doc_generated.go
It is unrealistic to expect customers to have more than 10, typically
they should have a LB in to distribute the load anyways.
> Bug 1950590: Cap netflow/sflow/ipfix collectors to 10

- cloudnetwork/v1/001-cloudprivateipconfig.crd.yaml
- cloudnetwork/v1/generated.proto
- cloudnetwork/v1/types.go
This fixes a minor issue with the CRD for cloud private IP configs. The CRD's `spec.names.plural` is currently incorrect and needs updating as the controller fails to find the resource as it currently stands.
/assign @danwinship @sttts
> Bug 1952795: fix plural name for CloudPrivateIPConfig

- config/v1/0000_10_config-operator_01_image.crd.yaml
- operator/v1alpha1/0000_10_config-operator_01_imagecontentsourcepolicy.crd.yaml
CRD v1beta1 is going to be removed, so we need to migrate to v1.
> Bug 1947798: Use CRD v1 for images.config and ICSPs

- config/v1/types_cluster_operator.go
`Available=False` is really bad.  Possibly a page-at-midnight thing.  "Hey, your registry is down, so any new pods based on local images will fail to launch" or "ingress is down, so your users cannot reach you".  If it's not a page-at-midnight thing, it's at least going to be the first batch of things admins should look at when they get [from-the-spout alerts][1].
`Degraded=True` is not great, but you should be able to survive with reduced quality-of-service until an admin wakes up in the morning.
[1]: https://docs.google.com/document/d/199PqyG3UsyXlwieHaqbGiWVa8eMWi8zzAn0YfcApr8Q/mobilebasic#h.rvrk9gcasjzh
> config/v1/types_cluster_operator: Clarify Available and Degraded severity

- apiserver/v1/apiserver.openshift.io_apirequestcount.yaml
the printer columns need updating after updates to the schema.
> bug 1954937: fix the oc get output for apirequestcounts

- operator/v1/0000_70_console-operator.crd.yaml
- operator/v1/types_console.go
- operator/v1/zz_generated.swagger_doc_generated.go
Adding `DEPRECATED: will be removed in 4.10`, although not 100% sure we want to set that expectation, or just add `DEPRECATED` string and remove the logic so when admin user sets the field nothing will happen, maybe just a log msg in the console-operator will appear notifying that the field is deprecated and that he needs to set the desired domain via ingress operator config. 
/assign @spadgett
> Bug 1959696: Deprecate 'ConsoleConfigRoute' struct in console-operator config

- config/v1/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
- config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
Modifications done as per the K8s doc https://kubernetes.io/docs/reference/using-api/deprecation-guide/
Signed-off-by: Lalatendu Mohanty <lmohanty@redhat.com>
> Bug 1947797: Bump ClusterVersion and ClusterOperator CRDs to apiextensions.k8s.io/v1

- operator/v1/0000_70_dns-operator_00-custom-resource-definition.yaml
- operator/v1/types_dns.go
- operator/v1/zz_generated.swagger_doc_generated.go
Update the godoc for the `dnses.operator.openshift.io` resource's `spec.nodePlacement.tolerations` field to state that the DNS operator adds a toleration for the `node-role.kubernetes.io/master` taint, that omitting the toleration would be risky, and that the daemon controller adds some additional tolerations.
* `operator/v1/types_dns.go` (`DNSNodePlacement`): Fix description of the `Tolerations` field.
* `operator/v1/0000_70_dns-operator_00-custom-resource-definition.yaml`:
> Bug 1951853: operator/dns: Describe default toleration

- config/v1/types_cluster_operator.go
Consider these cases:
a. Component A is in a state that allows updates, and nothing in the rest of the cluster would break if A updated.
b. Component A is in a state that allows updates, but component B (which is in-cluster, but not part of A) would break if A updated.
c. Component A would break if it updated.
Operator A should pretty clearly be `Upgradeable=True` for (a) and `Upgradeable=False` for (c).
Before this commit, a narrow reading of the comment would have operator A be `Upgradeable=True` for (b).  This commit moves it to `Upgradeable=False`, based on discussion in openshift/enhancements#762, where it becomes the job of the API-server to set `Upgradeable=False` if updating the API-server would break nodes running old kubelets.  The API-server can say "to unblock minor updates, …
> config/v1/types_cluster_operator: Expand upgradeable inputs to cluster scope

- config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
- config/v1/types_infrastructure.go
- config/v1/zz_generated.swagger_doc_generated.go
- operator/v1/0000_70_dns-operator_00-custom-resource-definition.yaml
Add Azure Stack Hub as a valid Azure cloud environment.
See openshift/enhancements#689
cc @staebler
> config: Azure Stack Hub support

- build/v1/generated.proto
- build/v1/types.go
Need to remove the `+k8s:conversion-gen=false` so that openshift/openshift-apiserver can auto-generate the conversions.
Tested this in the openshift/openshift-apiserver repo locally and it worked.
> removing conversion-gen=false for BuildVolumeSource.Type field

- tls/go.mod
> Add go.mod to tls dir to avoid invalid char errors on vendoring

- operator/v1/0000_70_cluster-network-operator_01_crd.yaml
- operator/v1/types_network.go
- operator/v1/zz_generated.swagger_doc_generated.go
This field is a no-op as of 4.6, but can't be removed for compatibility reasons.
(Replacement for #802)
> Clarify that useExternalOpenvswitch is deprecated and ignored

- operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
- operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
- operator/v1/types_csi_cluster_driver.go
Add AWS EFS CSI driver to ClusterCSIDriver validation. It will be supported in 4.9.
KEP: https://github.com/openshift/enhancements/pull/687/
> Add AWS EFS CSI driver

- config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
- config/v1/types_infrastructure.go
- config/v1/zz_generated.swagger_doc_generated.go
CISInstanceCRN is the Cloud Resource Name (CRN) referencing the instance of IBM Cloud Internet Services that is setup to manage the DNS zone of the cluster's base domain. This can be guaranteed in an IPI/UPI installation since this configuration is a pre-requisite. Components like the Cluster Ingress Operator will use this CRN in API calls to update DNS records.
This PR is required to implement IBMCloud IPI/UPI.
Enhancement doc: openshift/enhancements#773 
Relevant Installer PR: openshift/installer#4923
> Add CISInstanceCRN to IBMCloudPlatformStatus

- operatoringress/v1/0000_50_dns-record.yaml
- operatoringress/v1/types.go
- operatoringress/v1/zz_generated.swagger_doc_generated.go
operatoringress/v1/types.go:
Fix `dnsecord` -> `dnsRecord` in `spec` godoc.
operatoringress/v1/0000_50_dns-record.yaml,
operatoringress/v1/zz_generated.swagger_doc_generated.go:
Regenerate.
> operatoringress: Fix typo in DNSRecord CRD.

- operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
- operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
- operator/v1/types_csi_cluster_driver.go
`make update` etc. is behaving weird for me today ... I think my upgrading controller-gen for v0.5 for tekton has introduced formatting differences.
initially submitting with WIP and with any `make update` changes to see exactly how the verify job fails, and then see if I can split the difference
or I may have to maintain 2 versions of controller-gen
> BUILD-159: add projected share resource csi driver operator to the list managed by the CSO

- config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
- config/v1/types_cluster_version.go
- config/v1/zz_generated.swagger_doc_generated.go
Addressing some of the ambiguities raised in [rhbz#1825396](https://bugzilla.redhat.com/show_bug.cgi?id=1825396).
These docs have not been adjusted since the properties landed in ab4ff93d20 (#293).  The initial cluster-version operator implementation only used them for signature checks, openshift/cluster-version-operator@f8eff25191 (openshift/cluster-version-operator#170).  At that time, `RetrievePayload` would always attempt to verify the proposed release image, including both signature validation and "does this look like a real release image?" checks.  If that verification succeeded, it would set `verified: true`.  If that verification failed, it would look at `force`, and if `force` was true, it would set `verified: false` and proceed with the update, while if `force` was false, it …
> config/v1/types_cluster_version: Update force and verified godocs

- console/v1alpha1/0000_10_consoleplugin.crd.yaml
Adds annotation to include the consoleplugin CRD in the `ibm-cloud-managed` profile
> IBM cloud managed profile: add consoleplugin CRD

- config/v1/types_feature.go
This feature gate is required to enable extenal cloud providers, as we introduce this feature as tech preview in 4.9.
> Add ExternalCloudProvider to TechPreviewNoUpgrade FeatureSet

- console/v1alpha1/0000_10_consoleplugin.crd.yaml
> Bug 1986129: Add missing 'include.release.openshift.io/single-node-developer' annotation to the ConsolePlugin CRD

- config/v1/types_feature.go
This corresponds to https://github.com/openshift/enhancements/pull/683 enhancement.
> Bug 1988308: Add feature for Insights operator pulling SCA certs

- config/v1/types_feature.go
- config/v1/types_features_test.go
This enables PodSecurity admission (https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/2579-psp-replacement) by default.
This depends on admission configuration being merged first: https://github.com/openshift/cluster-kube-apiserver-operator/pull/1217
This can be merged once 4.10 master opens, the earliest.
/hold
> config/v1: add PodSecurity to Default features

- config/v1/types_cluster_operator.go
"administrators should not upgrade" is way too strict.  This commit relaxes that to point out that the message will tell you what's off limits, and the CVO will enforce that (but you can force past the CVO's guard).  The focus on minor updates is from [rhbz#1797624][1].  Subsequently, the CVO grew an internal check that even blocks patch bumps when they are unlikely to succeed in the face of unsupported overrides [rhbz#1822844][2].
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1797624
[2]: https://bugzilla.redhat.com/show_bug.cgi?id=1822844
> config/v1/types_cluster_operator: Tighten up Upgradeable docs

- operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
- operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
- operator/v1/types_csi_cluster_driver.go
The IBM VPC driver will be included in OCP 4.10
> Add IBM VPC CSI driver to clustercsidrivers

- config/v1/types_cluster_operator.go
Builds on #995; consider reviewing that one first.
Some operators have no configured operands (e.g. the bare-metal operator on non-metal platforms, or the image-registry operator when the admins have [configured `managementState:Removed`][1]).  Some operators have many configured operands.  Operators writing ClusterOperator conditions should not limit the conditions to speak about just the operator, or just a particular operand.  Instead, operators should speak about the component as a whole.  Is something about the service that the component provides gone?  If so, `Available=False` (midnight admin page).  Is something about the service that the component provides not hitting its service-level objectives? If so, `Degraded=True` (working-hours admin queue).  Doesn't matter if that thing is …
> config/v1/types_cluster_operator: Explain that conditions cover components

- config/v1/types_feature.go
Add the `CSIDriverSharedResource` feature gate to the tech preview set.
The CSI driver allows Secrets and ConfigMaps to be shared across
namespaces. This driver should only be installed on clusters that opt
into tech preview features.
> Tech Preview Shared Resource CSI Driver

- config/v1/types_feature.go
- openshiftcontrolplane/v1/types.go
- openshiftcontrolplane/v1/zz_generated.deepcopy.go
- openshiftcontrolplane/v1/zz_generated.swagger_doc_generated.go
/assign @adambkaplan 
/assign @bparees 
(given historical involvement in this effort, please feel free to unassign at your discretion)
/assign @deads2k 
(given recent reviews in this space as well as historical involvement in the shared/projected resource space; of course reassign at your discretion)
> BUILD-281:  add feature gate, OCM configuration bit, to enable build csi volume tech preview 

- config/v1/0000_10_config-operator_01_oauth.crd.yaml
- config/v1/types_oauth.go
- config/v1/zz_generated.deepcopy.go
- config/v1/zz_generated.swagger_doc_generated.go
- osin/v1/types.go
- osin/v1/zz_generated.deepcopy.go
This PR adds API to specify which OpenID claims should be used to retrieve the group information
@openshift/openshift-team-auth-maintainers
> AUTH-8: config,oauth: add groups to retrievable OpenIDClaims 

- config/v1/types_cluster_version.go
- sharedresource/v1alpha1/types_shared_configmap.go
- sharedresource/v1alpha1/types_shared_secret.go
These tags have to be added for the `make update` in openshift-apiserver to succeed when updating to k8s 0.22.1.
> Update patch merge tags in struct to match those in the comment

- config/v1/0000_10_config-operator_01_oauth.crd.yaml
- config/v1/types_oauth.go
Making list atomic to prevent GitOps overwrite
> Bug 1992592: Atomic List Type

- route/v1/generated.proto
- route/v1/types.go
- route/v1/zz_generated.swagger_doc_generated.go
In the documentation for `tls.certificate`, it doesn't specify whether or not a certificate chain can be used. This PR adds an additional note in the docs for `tls.certificate` that only a single certificate should be used, not a chain or additonal CA(s).
> Bug 2013238: Make the documentation for tls.certificate more verbose

- route/v1/types.go
This PR applies to the fix for https://github.com/openshift/openshift-apiserver/pull/228. 
It makes use of the annotation in route/v1/types.go.
This update aligns the comments to reflect the type of validation that will be enforced.
> Bug 1964112: Fix for host name validator error

- README.md
* `README.md`: Add a section on defining new APIs, with a reference to the API conventions section of the OpenShift `CONVENTIONS.md` document.
---
This PR will be more useful if https://github.com/openshift/enhancements/pull/951 is accepted.
> README.md: Add a reference for API conventions

- machine/v1beta1/types_azureprovider.go
- machine/v1beta1/zz_generated.swagger_doc_generated.go
Edited: The original PR added support for both Marketplace and Shared Image Gallery images. I have decreased the scope to only Marketplace images, which means we just need a flag as to when to populate the purchase plan. To avoid a boolean, I have added a `string` field `PurchasePlanName` which when present should have the same value as the `SKU`, and would indicate we should create a plan. Using a string avoids using a boolean, and allows us space if there is ever drift in the Microsoft API where purchase plan name != SKU.  
Upstream types: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/d2b4e8ed2313adc270a0911d9d0c64e344f34cc4/api/v1beta1/types.go#L316-L398
The OpenShift cluster-api-provider-azure will need to implement logic based off the upstream (I will open a PR …
> Bug 2023434: Add Purchase Plan Name to Azure Machine Provider Spec

- config/v1/types_infrastructure.go
This allows downstream operators to recognize they are in a UPI IBM Cloud Satellite environment and make config adjustments when applicable.
> add ibmcloud satellite upi provider enum

- config/v1/types_feature.go
This creates an api field to allow users to enable or disable
machine-api-provider-openstack in place of
cluster-api-provider-openstack as the openstack-machine-controller
image. This feature is in tech preview in OpenShift 4.10.
> Create a feature gate for MAPO tech preview

- config/v1/types_feature.go
See https://github.com/openshift/enhancements/pull/902 for OpenShift enhancement details (not yet merged+implementable).
Should be all the implementation currently needed for [OCPNODE-618](https://issues.redhat.com/browse/OCPNODE-618). Enabling swap within a cluster doesn't require any other code changes; configs are detailed in the enhancement above. I was able to get swap working on a cluster-bot cluster using a `CustomNoUpgrade` feature gate config.
> config/v1: Add NodeSwap to TechPreviewNoUpgrade

- machine/v1/common.go
- machine/v1/doc.go
- machine/v1/register.go
- machine/v1/types_alibabaprovider.go
Upon recent refactoring, the cloud provider machine objects have moved to openshift/api.
In this pull request I'm adding the AlibabaCloud provider types from https://github.com/openshift/cluster-api-provider-alibaba/tree/main/pkg/apis/alibabacloudprovider/v1beta1
> Machine API: adding Alibaba cloud provider types.

- config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
- config/v1/types_infrastructure.go
The `ResourceGroupID` is not required, so change the `ResourceGroupID` to optional.
> change the `ResourceGroupID` to optional on alibabacloud provider

- go.mod
- go.sum
- vendor/github.com/openshift/build-machinery-go/make/lib/golang.mk
- vendor/github.com/openshift/build-machinery-go/make/targets/openshift/images.mk
- vendor/github.com/openshift/build-machinery-go/make/targets/openshift/kustomize.mk
- vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yaml-patch.mk
- vendor/modules.txt
I've noticed a few errors locally when attempting to `make verify`. I'm attempting to update the go.mod to use the latest fix from https://github.com/openshift/build-machinery-go/pull/58
Errors:
```
Installing yaml-patch into '_output/tools/bin/yaml-patch-v0.0.10'
mkdir -p '_output/tools/bin/'
curl -s -f -L https://github.com/krishicks/yaml-patch/releases/download/v0.0.10/yaml_patch_linux -o '_output/tools/bin/yaml-patch-v0.0.10'
make: *** [ensure-yaml-patch] Error 22
make: *** [Makefile:70: generate-with-container] Error 2
```
> Updating build-machinery-go to fix the yaml_patch error

- imageregistry/v1/00_imageregistry.crd.yaml
- imageregistry/v1/00_imageregistry.crd.yaml-patch
- imageregistry/v1/types.go
Found an issue with renaming the field from `Type` to `Method`. 
We thought we had tested with a latest image update, rebuild, push, and test but we missed the CRD regeneration. 
Since we do not support `PlainText` I am going to remove it from the enum and CRD.
> Fix rename property patch from type to method

- console/v1alpha1/types_console_plugin.go
These fields are marked optional, hence should be omited when serialized
to json
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2032289
> Bug 2032289: omit empty fields in ConsolePlugin CR

- machine/v1beta1/0000_10_machine.crd.yaml
- machine/v1beta1/0000_10_machineset.crd.yaml
- machine/v1beta1/types_machine.go
The `required` validation does not get parsed by the controller-gen tool and therefore the correct fields are not set on the generated CRD. I have updated these to use the correct kubebuilder tags to fix the code generation and ensure that the name and owner fields are required within the openapi schema
> Bug 2034879: Ensure name and owner are required within lifecycle hooks

- config/v1/types_feature.go
Moving [Insighst pulling SCA/entitlement certs functionality](https://github.com/openshift/enhancements/blob/master/enhancements/insights/pulling-sca-certs-from-ocm.md) from TP to GA.
> Remove "InsightsOperatorPullingSCA" from tech preview featureset

- machine/v1beta1/0000_10_machine.crd.yaml
- machine/v1beta1/0000_10_machineset.crd.yaml
- machine/v1beta1/types_machine.go
@sttts Picked this up while reviewing the etcd protection enhancement. We specify that multiple operators should be able to add and remove their own hooks from these lists, by default, they are treated as atomic which means the operators need to be careful not to accidentally remove other operators hooks.
With this change, using server side apply the lists should now merge correctly and each operator should be able to manage their own hooks independently.
Tested manually, steps described in the bug
> Bug 2042366: Set list-type map on Machine Deletion Hooks

- Dockerfile.build
I tried to run `make generate-with-container` but it failed due to Go 1.17 specific issues:
```
hack/update-swagger-docs.sh
Generating swagger type docs for apiserver/v1 at apiserver/v1
vendor/sigs.k8s.io/json/internal/golang/encoding/json/encode.go:1249:12: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
vendor/sigs.k8s.io/json/internal/golang/encoding/json/encode.go:1255:18: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
```
The Fedora 35 (latest) image doesn't contain Go 1.17, so I've updated the tag to use Fedora 36 which I appreciate is not ideal, perhaps we need to wait for the `latest` tag to move to 36?
Additionally, the `go get -u -v` no longer works in Go 1.17, so I've moved that over to `go install`. …
> Update Dockerfile to account for Go 1.17 dependencies

- config/v1/types_feature.go
- config/v1/types_features_test.go
CSI migration for Azure Disk and Cinder will be GA in OCP 4.11.
https://issues.redhat.com/browse/STOR-615
https://issues.redhat.com/browse/STOR-670
> CSI migration for Azure Disk and Cinder is GA in 4.11

- cmd/openshift-compatibility-gen/generate/comment/generator.go
- security/v1/generated.proto
- security/v1/types.go
- security/v1/zz_generated.swagger_doc_generated.go
Per https://docs.openshift.com/container-platform/4.9/rest_api/understanding-api-support-tiers.html some of the security types are tier 4, not tier 1.  This PR fixes them and makes the generator logic tolerant of that setting.
> Add exceptions to compatibility level rules and fix security api compatibility levels

- cmd/openshift-compatibility-gen/generate/comment/generator.go
- console/v1/0000_10_consoleclidownload.crd.yaml
- console/v1/0000_10_consoleexternalloglink.crd.yaml
- console/v1/0000_10_consolelink.crd.yaml
- console/v1/0000_10_consolenotification.crd.yaml
- console/v1/0000_10_consolequickstart.crd.yaml
- console/v1/0000_10_consoleyamlsample.crd.yaml
- console/v1/types_console_cli_download.go
- console/v1/types_console_external_log_links.go
- console/v1/types_console_link.go
- console/v1/types_console_notification.go
- console/v1/types_console_quick_start.go
- console/v1/types_console_yaml_sample.go
- console/v1/zz_generated.swagger_doc_generated.go
and update generator to tolerate it
see our docs here: https://docs.openshift.com/container-platform/4.9/rest_api/understanding-api-support-tiers.html#mapping-support-tiers-to-openshift-api-groups_understanding-api-tiers
> Move console apis to tier 2, per what our docs say

- machine/v1beta1/types_awsprovider.go
- machine/v1beta1/zz_generated.swagger_doc_generated.go
QE picked up this small error during testing. After various iterations of #1091 the name of this field was changed. It makes sense for it to be `paritionNumber` in a customer facing context
> Bug 2060697: Correct json tag on AWS Placement PartitionNumber

- machine/v1/0000_10_controlplanemachineset.crd.yaml
- machine/v1/types_controlplanemachineset.go
- machine/v1/zz_generated.swagger_doc_generated.go
I noticed that the kubebuilder validation for the enum was missing and that the comment was out of date
> Ensure enumeration of ControlPlaneMachineSetMachineType type alias

- config/v1/types_node.go
Added the required frequency constants that can be used during the implementation of the worker latency profile related changes.
Reference: https://github.com/openshift/enhancements/blob/master/enhancements/worker-latency-profile/worker-latency-profile.md
> added frequency constants in accordance with the worker latency profiles

- config/v1/0000_10_config-operator_01_node.crd.yaml
- config/v1/types_node.go
Node CRD added in openshift/api#1107 should be made cluster scoped instead of namespace scoped since the enhancement proposals [1] [2] also intends to make cluster level changes.
[1] https://github.com/openshift/enhancements/blob/master/enhancements/worker-latency-profile/worker-latency-profile.md#proposal
[2] https://github.com/openshift/enhancements/blob/master/enhancements/machine-config/mco-cgroupsv2-support.md#api-extensions
Signed-off-by: Swarup Ghosh <swghosh@redhat.com>
> Cluster scope for config/v1 node CRD

- config/v1/0000_10_config-operator_01_node.crd.yaml
- config/v1/types_node.go
Added validation to workerLatencyProfile, cgroupMode fields in config.openshift.io/v1/node CRD.
Signed-off-by: Swarup Ghosh <swghosh@redhat.com>
> Add enum validation to .spec.* fields in config/v1 node CRD

- Dockerfile.build
- Makefile
As a mac user, I can generate assets with `RUNTIME=docker make generate-with-container`. However, this takes a really long time so on occasion, it might be easier to update (eg godoc changes into swagger) the assets manually.
At the moment, because I run the generation in container, the assets are built for linux, not darwin, so the verify target fails. I know others have also had issues with running verify locally so I thought it might be useful to have a container based verify for those who aren't able to run it within their own development environments easily.
> Allow consistent verification across platforms with container verify target

- machine/v1beta1/types_azureprovider.go
Renaming the AzureUltraSSDCapabilityState consts to be more coherent with the available `Enabled/Disabled` values.
This was an inconsistency recently introduced by: https://github.com/openshift/api/pull/1119 which we would like to fix before the new API gets added to a release.
> machine: azureprovider: AzureUltraSSDCapabilityState const rename

- config/v1/0000_10_config-operator_01_ingress.crd.yaml
- config/v1/types_ingress.go
We use the[ go-openapi/strfmt library for the "hostname"](https://github.com/go-openapi/strfmt/blob/master/default.go#L59) kubebuilder validation format in `componentRoutes`. This format does not accept numbers or hyphens in the TLD as noted in https://bugzilla.redhat.com/show_bug.cgi?id=2039256#c3.
I checked with the openshift/api team and they recommended replacing the hostname format with my own regex, but I have to be careful with downgrades. Therefore I changed the regex pattern to be looser.
The old pattern that came from go-openapi/strfmt: 
`^([a-zA-Z0-9\p{S}\p{L}]((-?[a-zA-Z0-9\p{S}\p{L}]{0,62})?)|([a-zA-Z0-9\p{S}\p{L}](([a-zA-Z0-9-\p{S}\p{L}]{0,61}[a-zA-Z0-9\p{S}\p{L}])?)(\.)){1,}([a-zA-Z\p{L}]){2,63})$`
The new pattern is simply an `|` of the old pattern with the correct, …
> Bug 2039256: kubebuilder validation format hostname is not RFC compliant

- operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
- operator/v1/types_ingress.go
- operator/v1/zz_generated.deepcopy.go
- operator/v1/zz_generated.swagger_doc_generated.go
Add the routeSelector and namespaceSelector to support route status updates in [https://github.com/openshift/cluster-ingress-operator/pull/724](https://github.com/openshift/cluster-ingress-operator/pull/724) which provide fixes for https://bugzilla.redhat.com/show_bug.cgi?id=1944851 and other bugs indirectly.
These new fields in the status, which are a mirror of the fields in the spec, provide state of the selector allowing us to trigger when either of these selectors are updated.
> Bug 1944851: Add selectors to ingress controller status for determining state

- operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
- operator/v1/types_ingress.go
- operator/v1/zz_generated.swagger_doc_generated.go
- Update operator/v1/types_ingress.go to add Nutanix to LoadBalancerProviderType enum
- Regenerate operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
- Regenerate operator/v1/zz_generated.swagger_doc_generated.go
> Add Nutanix to the LoadBalancerProviderType enum

- config/v1/0000_10_config-operator_01_ingress.crd.yaml
- config/v1/types_ingress.go
The `DefaultPlacement` config status field should allow the `""` value
to be used during an Update for this subresource. This should allow the
status subresource to be updated even when `DefaultPlacement` has an
empty value.
Also removed the `kubebuilder:default:="Workers"` specifier because the
controller already regards an empty value as `"Workers"`, there's no
need for it to be explicitly set when omitted.
> Bug 2074243: `DefaultPlacement` allow empty enum value and remove default

- config/v1/types_cluster_version.go
- config/v1/types_cluster_version_test.go
Currently validators are [treating the union of all known sets as the set of all capabilities][1], but it is possible that some future
capability belongs to no set.  By adding a knew variable to hold all known capabilities, we avoid validators rejecting that no-set capability as unknown.
This could have been a new `All` set that held all known capabilities, but:
* We can add new sets in the future, but because of backwards compatibility requirements, we can never remove an existing set.
* We already have `v4.11` and `vCurrent` covering the set of all known capabilities.  Having three different sets with slightly different forward-looking semantics is more overhead for capability-selecting administrators than we want to bite off for 4.11.  As we get to later 4.y with more sets, the …
> config/v1/types_cluster_version: Add KnownClusterVersionCapabilities

- sharedresource/v1alpha1/0000_10_sharedconfigmap.crd.yaml
- sharedresource/v1alpha1/0000_10_sharedsecret.crd.yaml
relevant slack in case someone needs to [read](https://coreos.slack.com/archives/C01CQA76KMX/p1652975216903949).
> BZ 2088533: add subresource.status{} to sharedsecrets and sharedconfigmaps

- config/v1/0000_10_config-operator_01_ingress.crd.yaml
- config/v1/types_ingress.go
Cherry-pick #1120 to [release-4.8]
> Bug 2081457: kubebuilder validation format hostname is not RFC compliant

- config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
- config/v1/types_infrastructure.go
- config/v1/zz_generated.swagger_doc_generated.go
Adding support to use DNS Services for IBM Cloud IPI, where the
infrastructure resource will be updated with the DNS Services
instance CRN, when DNS is used for the cluster. Including same
configuration for PowerVS.
Related: https://bugzilla.redhat.com/show_bug.cgi?id=2094891
> Bug 2094891: IBMCloud: Add DNS CRN to IBM PlatformStatus

- machine/v1beta1/types_vsphereprovider.go
- machine/v1beta1/zz_generated.swagger_doc_generated.go
Due to potential default behaviour changes of `CloneMode` field docstrings should be updated.
vSphere Machine controller changes: https://github.com/openshift/machine-api-operator/pull/959
Related MAPI bug: https://bugzilla.redhat.com/show_bug.cgi?id=2001008
cc @JoelSpeed @elmiko
> Update docstrings for VSphereMachineProviderSpec

- operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
- operator/v1/types_csi_cluster_driver.go
- operator/v1/zz_generated.swagger_doc_generated.go
Add a field to skip creation of StorageClass for CSI driver.
xref https://github.com/openshift/enhancements/pull/1152
cc @openshift/storage
> Add a field in ClusterCSIDriver type to skip creation of storageclass

- operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
- operator/v1/types_ingress.go
- operator/v1/zz_generated.swagger_doc_generated.go
Allow configuring an IngressController with the "Private" endpoint publishing strategy type to use PROXY protocol.
* `operator/v1/types_ingress.go` (`PrivateStrategy`): Add `Protocol` field with type `IngressControllerProtocol`.
* `operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml`:
> Bug 2104481: operator/ingress: Allow PROXY protocol for Private endpoint publishing strategy

- operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
- operator/v1/types_ingress.go
Reject values for `healthCheckInterval` such as "0abc".
* `operator/v1/types_ingress.go` (`IngressControllerTuningOptions`): Fix validation for `healthCheckInterval`.
* `operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml`: Regenerate.
> Bug 2106086: operator/ingress: Fix healthCheckInterval pattern

- operator/v1/0000_70_cluster-network-operator_01.crd.yaml
- operator/v1/types_network.go
- operator/v1/zz_generated.swagger_doc_generated.go
Some users need to be able to specify the v4 and v6 join subnets
to use for ovn-k. In particular, they may be already using the
ones that ovn-k uses as default, and they need a way to be able to
specify a different set of subnets as join subnets. This commit
creates the config option for  the same. Eventually this will be
consumed by the CNO using rendered bootstrap data and passed to the
ovn-k daemonsets.
Signed-off-by: Peng Liu <pliu@redhat.com>
> Bug 1894268: Allow users to specify ovnkube join subnet

- operator/v1/0000_70_cluster-network-operator_01.crd.yaml
- operator/v1/0000_70_cluster-network-operator_01.crd.yaml-patch
Remove the unecessary yaml patch for the ClusterNetworkOperator
CRD since this wasn't working as intended anyways. See bz for more info
This reverts commit 6f0ce8c5f8b21d0262af50e99f3f9a6dcc0008e3.
> Bug 1978798: Revert "Update ovnKubernetesConfig.policyAuditConfig Default"

- Makefile
- route/v1/generated.proto
- route/v1/route.crd.yaml
- route/v1/route.crd.yaml-patch
- route/v1/test-route-validation.sh
- route/v1/types.go
* `Makefile`: Add an "update-codegen-crd-route" target.
* `route/v1/route.crd.yaml`: New file.  Define a CRD for the Route API.
* `route/v1/route.crd.yaml-patch`: New file.  Patch `route-crd.yaml` with validation that cannot be expressed using kubebuilder tags.
* `route/v1/test-route-validation.sh`: New file.  Verify that the API admits valid routes and rejects invalid routes.
* `route/v1/types.go`: Add kubebuilder validation tags.
---
The motivation for this PR is to supersede <https://github.com/openshift/router/blob/master/deploy/route_crd.yaml>, which does not perform any validation, for use in environments where OpenShift router is used without openshift-apiserver.  
This implements most of the validation that openshift-apiserver does; see …
> route/v1: Add CRD

- monitoring/v1alpha1/0000_50_monitoring_02_alertrelabelconfigs.crd.yaml
- monitoring/v1alpha1/types.go
- monitoring/v1alpha1/zz_generated.swagger_doc_generated.go
The action in alert relabel configs documents actions with starting with
a lowercase letter but the validation only passes capitalized actions.
The resulting prometheus yaml is always lowercase and controllers call
ToLower anyway. Accepting both lowercase actions and capitalied actions
is consistent with what prometheus-operator accepts.
Signed-off-by: Jan Fajerski <jfajersk@redhat.com>
> Bug 2100312: monitoring: include lowercase action in relabel_config validation

- config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
- config/v1/types_cluster_version.go
- console/v1/0000_10_consoleclidownload.crd.yaml
- console/v1/0000_10_consoleexternalloglink.crd.yaml
- console/v1/0000_10_consolelink.crd.yaml
- console/v1/0000_10_consolenotification.crd.yaml
- console/v1/0000_10_consolequickstart.crd.yaml
- console/v1/0000_10_consoleyamlsample.crd.yaml
- console/v1alpha1/0000_10_consoleplugin.crd.yaml
The lowercase form just landed via 9db3a0ce01 (#1232), CC @raspbeep, and that matched the lower-case precedent which we had been using for these enumerated capabilities.  But [the Kube-API preference is for PascalCase][1], so this commit pivots to that form.  Because we are so close on the heels of the original change, we don't need to preserve any references to the outgoing form.  Adjusting the 4.11 references like `openshift-samples` will take more dancing, and can happen in follow-up
work.  Generated with:
```console
$ sed -i 's|\(capability[.]openshift[.]io/name\): console|\1: Console|' $(git grep -l 'capability.openshift.io/name: console')
$ sed -i 's/console/Console/' config/v1/*version*
```
And then backing out one godocs hit that the above made:
```console
$ sed -i 's/the web …
```
> config/v1: Change ClusterVersion capability from 'console' to 'Console'

- helm/v1beta1/0000_10-project-helm-chart-repository.crd.yaml
- helm/v1beta1/types_project_helm_chart_repository.go
- helm/v1beta1/zz_generated.deepcopy.go
This change introduces the `BasicAuthConfig` field in the `ConnectionConfigNamespaceScoped` struct; this struct is a reference to a secret within a namespace containing the `username` and `password` fields to be used when connecting to a Helm chart repository such as ChartMuseum.
This is a dependency for https://github.com/openshift/console/pull/11782, which configures the connection utilizing the `username` and `password` fields mentioned above.
> Add basic authentication configuration support for Project Helm repositories

- operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
- operator/v1/types_ingress.go
- operator/v1/zz_generated.swagger_doc_generated.go
- operatoringress/v1/0000_50_dns-record.yaml
- operatoringress/v1/types.go
- operatoringress/v1/zz_generated.swagger_doc_generated.go
Add additional fields to configure DNS management on ingresscontrollers
---
This PR, introduces 2 fields to the IngressController API,
- `DNSManagementPolicy` of type `LoadBalancerDNSManagementPolicy` to the ingresscontroller spec. 
- `DNSManagementPolicy` to the DNSRecord spec.
RFE: https://issues.redhat.com/browse/RFE-895
EP: https://github.com/openshift/enhancements/pull/1114
> CFE-555: Add additional fields to configure DNS management on ingresscontrollers

- Makefile
- tls/go.mod
In https://github.com/openshift/api/pull/1226 I removed unused file, but it turns out it's needed for vendoring to work properly. While at it, I fixed the `Makefile` with the correct excluded dirs.
Found while working on https://github.com/openshift/api/pull/1248
> Bring back tls/go.mod file

- machine/v1/types_nutanixprovider.go
- openapi/generated_openapi/zz_generated.openapi.go
- openapi/openapi.json
The openapi gen is complaining that this tag is missing, though the script exits 0 🤔 
```
E0823 11:21:07.360904   75629 openapi.go:487] [github.com/openshift/api/machine/v1.NutanixResourceIdentifier]: union members must be optional: github.com/openshift/api/machine/v1.NutanixResourceIdentifier.Type
```
But yes, it highlighted that this tag is missing from the union discriminant
> Add missing unionDiscriminator tag to NutanixResourceIdentifier

- config/v1/types_feature.go
- config/v1/types_features_test.go
This is needed for landing k8s 1.25, since these 3 features are GA-ed upstream and locked to always on.
/assign @jsafrane @stlaz
> Drop GA-ed features (CSIMigrationAWS, CSIMigrationGCE, PodSecurity)

- config/v1/types_feature.go
Adds cgroups v2 to TechPreviewNoUpgrade FeatureSet
Jira Story - https://issues.redhat.com/browse/OCPNODE-1147
Signed-off-by: Harshal Patil <harpatil@redhat.com>
> [OCPNODE-1147] : Add cgroups v2 to TechPreviewNoUpgrade FeatureSet

- config/v1/0000_10_config-operator_01_ingress.crd.yaml
- config/v1/types_ingress.go
- openapi/generated_openapi/zz_generated.openapi.go
- openapi/openapi.json
ComponentRoutes are keyed by namespace,name tuples.  See the docs on the field here: https://kubernetes.io/docs/reference/using-api/server-side-apply/#merge-strategy
Not sure what to do about HSTS, that may be an evolutionary problem.
/assign @Miciah @JoelSpeed
> update ingress component route SSA list markers

- openapi/generated_openapi/zz_generated.openapi.go
- openapi/openapi.json
- operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
- operator/v1/types_ingress.go
- operator/v1/zz_generated.swagger_doc_generated.go
Signed-off-by: Thejas N <thn@redhat.com>
> Fixed lifecycle typo in ingress godoc

- config/v1/types_feature.go
While it technically doesn't do anything (As the crun feature is toggled by TechPreviewNoUpgrade),
it does make users aware of the feature they're enabling with TechPreviewNoUpgrade
Signed-off-by: Peter Hunt~ <pehunt@redhat.com>
> TechPreviewNoUpgrade: add Crun feature to set

- config/v1/types_feature.go
These 2 CSI migration features went GA in k8s 1.25 and the gates are [locked to true](https://github.com/kubernetes/kubernetes/blob/67d75db8905f16bb0d9d0a14b13a8736cb614533/pkg/features/kube_features.go#L904). They were removed from the list of disabled feature gates in https://github.com/openshift/api/pull/1260 but not from the `TechPreviewNoUpgrade` gates, which will cause issues when `TechPreviewNoUpgrade` is enabled.
https://issues.redhat.com/browse/STOR-749
https://issues.redhat.com/browse/STOR-762
/cc @openshift/storage @soltysh
> Remove CSIMigrationAWS and CSIMigrationGCE feature gate references

- config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
- config/v1/types_cluster_version.go
Add CSISnapshot capability which allows disabling CSI snapshot
controller operator which is responsible for watching the
VolumeSnapshot CRD objects and manages the creation and
deletion lifecycle of volume snapshots.
> [CNF-5646] Add CSISnapshot capability

- route/v1/route.crd.yaml
- route/v1/route.crd.yaml-patch
- route/v1/test-route-validation.sh
Fix the Route CRD validation for allow routes with null `spec.tls` and nonempty `spec.path`.
* `route/v1/route.crd.yaml-patch`: Add a case to allow `spec.path` to be nonempty when `spec.tls` is null.  The existing case to allow `spec.path` when `spec.tls.termination` is not "passthrough" is insufficient when `spec.tls` is not specified at all.
* `route/v1/route.crd.yaml`: Regenerate.
* `route/v1/test-route-validation.sh`: Add test cases "non-TLS with nonempty path" and "edge-terminated with nonempty path".
> USHIFT-333: route/v1: Fix CRD to allow path for non-TLS routes

- openapi/generated_openapi/zz_generated.openapi.go
- openapi/openapi.json
- operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
- operator/v1/types_ingress.go
- operatoringress/v1/0000_50_dns-record.yaml
- operatoringress/v1/types.go
Signed-off-by: Thejas N <thn@redhat.com>
> Add omitempty to dnsmanagementpolicy

- config/v1alpha1/0000_10_config-operator_01_insightsdatagather.crd.yaml
- monitoring/v1alpha1/0000_50_monitoring_01_alertingrules.crd.yaml
- monitoring/v1alpha1/0000_50_monitoring_02_alertrelabelconfigs.crd.yaml
- platform/v1alpha1/platformoperators.crd.yaml
This was added in
openshift/cluster-version-operator#821 to allow
more featuresets and allow for a future migration to include actual gates
/cc @wking
> update to release.openshift.io/feature-set to match OCP 4.12

- config/v1/types_cluster_operator.go
This will be used to indicate the result of the detection logic that was added to a component to evaluate the introduction of an invasive change that could potentially result in highly visible alerts, breakages or upgrade failures on user clusters.
Ref: https://github.com/openshift/enhancements/pull/1216
> OCPSE-25: introduce EvaluationConditionsDetected ClusterStatusConditionType

- platform/v1alpha1/platformoperators.crd.yaml
Update the PlatformOperator CRD and add the required self-managed-high-availability cluster profile.
Signed-off-by: timflannagan <timflannagan@gmail.com>
> platform/v1alpha1: Update the cluster profile annotations

- OWNERS
Over the past six months, @JoelSpeed has conducted the majority of first line API reviews.  In that time, he has consistently applied our API standards, refined our documentation, and maintained, improved, and created the machinery of operating this repo.
@JoelSpeed if you're willing to continue doing this work, please /lgtm. :)
> Add Joel Speed as API approver

- machine/v1/0000_10_controlplanemachineset.crd.yaml
- machine/v1/Makefile
- machine/v1/control-plane-machine-set.aws.stable.testsuite.yaml
- machine/v1/control-plane-machine-set.azure.stable.testsuite.yaml
- machine/v1/control-plane-machine-set.gcp.stable.testsuite.yaml
- machine/v1/control-plane-machine-set.stable.testsuite.yaml
- machine/v1/types_aws.go
- machine/v1/types_controlplanemachineset.go
- machine/v1/zz_generated.swagger_doc_generated.go
- openapi/generated_openapi/zz_generated.openapi.go
- openapi/openapi.json
- tests/hack/test.sh
/hold this needs the Kube 1.25 rebase to have landed before it will work
We have these validations already but they are currently maintained as a webhook. In an effort to reduce our code complexity and demonstrate the CEL usage for OpenShift, I've tried to replicate the validations here.
Eg. Today we validate the unions with https://github.com/openshift/cluster-control-plane-machine-set-operator/blob/1fa6ff25480e5eb4221a1f5d059dd7b416381e12/pkg/webhooks/controlplanemachineset/webhooks.go#L511-L570, which is complicated, using CEL would simplify this for us and others who are writing unions.
Q: Can users override this validation and persist objects that don't match the schema? Does this change allow us to delete the webhook code?
> Updates to ControlPlaneMachineSet validation with CEL

- machine/v1alpha1/register.go
This commit does not change any exposed OpenShift API. Rather, it conveniently exposes `machine.openshift.io/v1alpha1`'s versioning information, consistently with the other versions of the same resource.
> machine/v1alpha1: Expose GroupVersion

- config/v1/types_feature.go
This adds an OCP feature gate for a CSI Inline Volume Admission Plugin
behind TechPreviewNoUpgrade for 4.12.
Enhancement: https://github.com/openshift/enhancements/pull/1240
> STOR-829: Add CSIInlineVolumeAdmission feature gate

- config/v1/types_feature.go
Enabling as TPNoUpgrade. New alpha feature in 1.25.
https://github.com/openshift/kubernetes/blob/master/pkg/features/kube_features.go#L548-L553
> RFE-2797: config/v1: Add MatchLabelKeysInPodTopologySpread to TechPreviewNoUpgrade

- config/v1/0000_10_config-operator_01_imagedigestmirrorset.crd.yaml
- config/v1/0000_10_config-operator_01_imagetagmirrorset.crd.yaml
- config/v1/stable.imagedigestmirrorset.testsuite.yaml
- config/v1/stable.imagetagmirrorset.testsuite.yaml
Register ImageDigestMirrorset, ImageTagMirrorSet from 4.13.
These CRDs were unregistered before since we planned it for 4.13. Now, 4.13 branch is open, we can get this in.
CRD implementation: https://github.com/openshift/machine-config-operator/pull/3037
> [OCPNODE-521]Register ImageDigest/TagMirrorSet CRDs

- example/v1/0000_50_stabletype-default.crd.yaml
- example/v1/0000_50_stabletype-techpreview.crd.yaml
- example/v1/stable.stableconfigtype.testsuite.yaml
- example/v1/types_stable.go
- example/v1/zz_generated.swagger_doc_generated.go
- openapi/generated_openapi/zz_generated.openapi.go
- openapi/openapi.json
- tests/generator.go
- tests/types.go
Previously, we weren't testing the status subresource. However, now that kubectl exposes subresources to end users, we will want to add validations to the status so that we can prevent them from changing things we don't want them to change.
This PR updates the test generator so that status can be added to the update tests, allowing users to check that status can added to objects and allowing them to test validations
> Ensure integration tests can test status updates

- tools/Makefile
- tools/codegen/cmd/root.go
A lot of people are going to use this utility, and over time we expect it to evolve with new features and bug fixes.
To ensure that our users have the most up to date version, this PR does the following:
* Grabs the last commit to change any file that would affect the codegen utility (anything from the codegen source, or go modules relating to it)
* Injects that as a version arg into the codegen build
* Adds a `--version` flag to codegen
* Updates the makefile with a target that compares the current and built versions and removes the binary if it's an old version
The upshot of this is that whenever someone runs the update scripts, if the codegen tool needs to be rebuilt, it will automatically, if it doesn't, then there's no point rebuilding it.
> Add versioning to codegen utility

- imageregistry/v1/00_imageregistry.crd.yaml
- imageregistry/v1/01_imagepruner.crd.yaml
- imageregistry/v1/register.go
Our generator relies on each API group/version having an exported `GroupVersion` , some older APIs only have `SchemeGroupVersion` which was deprecated in favour of `GroupVersion`, `imageregistry/v1` is one of those that missed the change to the new name.
This fixes the API generation and updates the generated CRDs to match the formatting of the rest of the API repo.
> Ensure ImageRegistry v1 exports GroupVersion

- Makefile
- cloudnetwork/v1/001-cloudprivateipconfig.crd.yaml
- hack/verify-group-versions.sh
- image/docker10/register.go
- image/dockerpre012/register.go
- legacyconfig/v1/register.go
- samples/v1/0000_10_samplesconfig.crd.yaml
- samples/v1/register.go
- sharedresource/v1alpha1/0000_10_sharedconfigmap.crd.yaml
- sharedresource/v1alpha1/0000_10_sharedsecret.crd.yaml
- sharedresource/v1alpha1/register.go
- tools/codegen/pkg/generation/context.go
- tools/codegen/pkg/swaggerdocs/generator.go
- unidling/v1alpha1/register.go
The new codegen tool relies on having a public `GroupVersion` `schema.GroupVersion` in each API group, this is how it discovers the API group/version. Some of our APIs didn't have this so weren't being picked up by the generator.
I've added a log line so we can catch which folders are being ignored in the future, and I've set up a script which should catch this as well. Based on our existing API search (which uses some regexes to look for folders that look like API versions), it checks for a register.go file and the `GroupVersion` within that. This worked well for most of our API groups but a few hadn't been updated and where still using the legacy `SchemeGroupVersion` name.
There are a few formatting changes in the CRDs which are due to the differences in how we were formatting manifests …
> Fix missing group versions for some API groups

- route/v1/generated.proto
- route/v1/route.crd.yaml
- route/v1/stable.route.testsuite.yaml
- route/v1/types.go
Setting the default value for spec.to.weight is typically performed by openshift-apiserver, but it's missing when Route is CRD-backed.
> OCPBUGS-3635: Set default for spec.to.weight in Route CRD.

- example/v1alpha1/0000_50_notstabletype-techpreview.crd.yaml
- machine/v1beta1/0000_10_machine.crd.yaml
- machine/v1beta1/0000_10_machinehealthcheck.yaml
- machine/v1beta1/0000_10_machineset.crd.yaml
- tools/codegen/pkg/schemapatch/generator.go
- tools/codegen/pkg/schemapatch/schemapatch.go
The runtime, I thought took ages to load and therefore tried to optimise so that we could share it between generation runs. It turns out, some state within this is being mutated and causes issues when generating multiple groupversions from the same runtime.
This PR removes the shared state and fixes the example and machine APIs which accidentally had some validations removed due to this bug.
This was found because I changed a list to a map within another branch I'm working on, which meant orderings were no longer preserved, I could then see it making weird swaps in a non-deterministic way. This has gone away with this change.
> Runtime should not be shared between generator runs

- hack/update-protobuf.sh
The protobuf generator currently requires that the GOPATH is set to run, this will be fixed in a future version (https://github.com/kubernetes/kubernetes/pull/112061) but for now we must warn that the generator cannot be used without a GOPATH
> Warn of no gopath for protobuf generator

- tests/README.md
This PR adds some documentation to help explain how the API integration tests work, and how to write a test for them.
I think I've covered everything but having authored them I have more context than most so open to feedback if anyone thinks I've missed anything.
> Add initial documentation for integration test suite

- config/v1/types_feature.go
Since we have to revert enforcement for 4.12, this enables people using 4.12 to experiment with PSA enabled.
In 4.13, we will move this to default again because we're optimistic.
> OCPBUGS-3985: add pod security admission enforcement to techpreview

- machine/v1beta1/types_machine.go
Rather than forcing machine providers to replicate machine phases, if needed, the phases should be made public consts instead.
Related: https://issues.redhat.com/browse/OCPCLOUD-1783
> OCPCLOUD-1783: Make machine phases public consts

- tools/codegen/pkg/generation/context.go
- tools/codegen/pkg/generation/types.go
I noticed a couple of things while working on other features:
- The legacyconfig group has no group name which means the generator was ignoring it, switch the check to check for a non-empty groupversion string which should cover the same check as the original intention
- The deepcopy serialisation for disabled wasn't correct
> Minor codegen fixes

- tools/codegen/pkg/schemapatch/generator.go
- tools/codegen/pkg/utils/diff.go
There were a couple of errors in my previous PR.
First up, I got the order wrong, I meant to put the existing data as the base of the patch so that you get the diff in the expected direction, red lines are things that are removed, green lines are things that have been added, this is fixed now.
Secondly, prow, annoyingly, doesn't colour blocks of data, but only individual lines. So we have to print the colour code on every coloured line
Currently have a WIP commit for testing the output.
> Improve diff output of schemapatch verification within Prow

- tools/codegen/pkg/schemapatch/generator.go
In #1359 which I merged last week, there was a small bug in the verification stage of the schemapatch. Rather than continuing the loop to the next object when there was an issue, it instead returned from the function.
This meant the verification would only verify the first object in each API group 🤦
> Fix verifying multiple manifests in schemapatch

- tools/codegen/cmd/root.go
- tools/codegen/pkg/schemapatch/schemapatch.go
- tools/codegen/pkg/utils/aggregate.go
In a recent PR, we saw the generators updated a bunch of files and created invalid CRD schemas because of a typo within the configv1 API group. After reviewing the code and stepping through with a debugger, I noticed that errors were being surfaced in the packages themselves which were causing the generation to fail, however, these were never surfaced higher and the generator happily produced an incorrect result.
To make this easier to spot in the future, I've added some code to gather errors observed in the packages we generate and then print these out in a hopefully readable format.
The printing of the errors splits the wrapped errors and prints each error wrap on a new line, with aggregate errors printed on each line separately as well.
Currently there's an extra commit to show what …
> Print errors that are not currently surfaced by the schemapatch generator

- config/v1/types_feature.go
- config/v1/types_features_test.go
> STOR-1119, STOR-751: CSI migration for vSphere and Azure file are GA

- config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
- config/v1/types_cluster_version.go
Along with adding a 4.13 capability set, this PR adds node-tuning to the set of OpenShift capabilities that can be optionally disabled at cluster install starting with OpenShift 4.13. This can be used to disable the Node Tuning Operator (NTO) and the containerized TuneD daemon which it manages. 
The Node Tuning Operator applies TuneD default profiles to the control plane and worker nodes, and enables users to apply custom OS-level tuning. When disabled, the default tuning profiles will not be applied which may impact the performance of certain workloads, and will impact scalability of very large clusters (~900 nodes or ~1000 routes).  
Any tuning that is functionally required will be handled by MCO going forward (see https://github.com/openshift/machine-config-operator/pull/3440)
Related …
> (PSAP-741) config/v1/types_cluster_version: add node-tuning capability

- tools/codegen/pkg/openapi/generator.go
My last PR which introduced the openapi generation into the codegen utility, for some reason changed the input from package paths (eg the import `github.com/openshift/api/apps/v1`) to a relative path, not sure why this was done as it breaks generation when not in `$GOPATH`
This changes it back, tested locally by checking out openshift API outside of my GOPATH
> OpenAPI expects package path inputs

- config/v1/types_feature.go
- config/v1/types_features_test.go
We want to release RetroactiveDefaultStorageClass as TechPreview in 4.13: https://issues.redhat.com/browse/STOR-1133
KEP: https://github.com/kubernetes/enhancements/issues/3333
cc @openshift/storage
> STOR-1133: set RetroactiveDefaultStorageClass feature as TechPreview

- config/v1/types_feature.go
adding UnhealthyPodEvictionPolicy for PodDisruptionBudgets which was added as an alpha in kube 1.26
> WRKLDS-657: add PDBUnhealthyPodEvictionPolicy to tech preview

- config/v1/types_feature.go
Remove `crun` and `cgroup v2` from TechPreviewNoUpgrade as both of those features have been graduated to GA. 
Signed-off-by: Harshal Patil <harpatil@redhat.com>
> Remove crun and cgroup v2 from TechPreviewNoUpgrade

- config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
- config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
- config/v1/stable.infrastructure.testsuite.yaml
- config/v1/types_infrastructure.go
- config/v1/zz_generated.swagger_doc_generated.go
- openapi/generated_openapi/zz_generated.openapi.go
- openapi/openapi.json
Fixes https://issues.redhat.com/browse/MULTIARCH-3212
These two fields are required to add the storage support for PowerVS cloud platform in https://github.com/openshift/cluster-image-registry-operator. 
With the recent [commit](https://github.com/openshift/cluster-image-registry-operator/pull/820/commits/eac9584446660721c5a31f54fd342f01415a8e92) in cluster-image-registry-operator, powervs platform blocked from using emptyDir as storage.
Trying to use IBMCOS as storage since its already supported as one of the storage option.
It reads location and resource group information from Infrastructure Status object.
So adding these two fields in PowerVSPlatformStatus.
> Add ResourceGroup field to PowerVSPlatformStatus

- config/v1/types_feature.go
Enable https://kubernetes.io/docs/concepts/scheduling-eviction/dynamic-resource-allocation/ for TechPreviewNoUpgrade
Part of making https://issues.redhat.com/browse/OCPBU-208 available for early adoption.
> TechPreview: enable DynamicResourceAllocation feature gate

- openapi/generated_openapi/zz_generated.openapi.go
- openapi/openapi.json
- operator/v1/0000_50_cluster_storage_operator_01_crd.yaml
- operator/v1/stable.storage.testsuite.yaml
- operator/v1/types_storage.go
- operator/v1/zz_generated.swagger_doc_generated.go
https://issues.redhat.com/browse/STOR-1266
Dependent PR's:
- https://github.com/openshift/kubernetes/pull/1514
- https://github.com/openshift/cluster-kube-apiserver-operator/pull/1466
- https://github.com/openshift/cluster-kube-controller-manager-operator/pull/710
- https://github.com/openshift/cluster-kube-scheduler-operator/pull/469
- https://github.com/openshift/machine-config-operator/pull/3614
- https://github.com/openshift/cluster-storage-operator/pull/351
- https://github.com/openshift/vmware-vsphere-csi-driver-operator/pull/145
> STOR-1266: Add CSI migration option to Storage operator spec

- openapi/generated_openapi/zz_generated.openapi.go
- openapi/openapi.json
- operator/v1/0000_50_cluster_storage_operator_01_crd.yaml
- operator/v1/stable.storage.testsuite.yaml
- operator/v1/types_storage.go
- operator/v1/zz_generated.swagger_doc_generated.go
https://issues.redhat.com/browse/STOR-1266
/cc @openshift/storage @JoelSpeed @deads2k @jsafrane
This is a simple backport of https://github.com/openshift/api/pull/1423
`git cherry-pick 426d59473937ba3aaec1e6ef768051090d1c78ac`
> OCPBUGS-11146: Add CSI migration option to Storage operator spec

- operator/v1/0000_50_cluster_storage_operator_01_crd.yaml
- operator/v1/stable.storage.testsuite.yaml
- operator/v1/types_storage.go
We need to be able to switch between `LegacyDeprecatedInTreeDriver` and `""` so this updates the validation to relax it so that we can do so.
I've simplified based on what I believe the intention is, allowing changing to CSIWithMigraitonDriver, but not allowing changing away from it, so once oldSelf is CSIMigration driver, self must be too
> Update storage vSphere driver validation

- openapi/generated_openapi/zz_generated.openapi.go
- openapi/openapi.json
- operator/v1/0000_50_cluster_storage_operator_01_crd.yaml
- operator/v1/stable.storage.testsuite.yaml
- operator/v1/types_storage.go
- operator/v1/zz_generated.swagger_doc_generated.go
https://issues.redhat.com/browse/OCPBUGS-11729
This also disables setting LegacyDeprecatedInTreeDriver in 4.14. That setting is only valid in 4.13. Integration tests are updated accordingly, since this caused any test case using that setting to fail.
/cc @JoelSpeed
> OCPBUGS-11729: VSphereStorageDriver does not document the platform default

- openapi/generated_openapi/zz_generated.openapi.go
- openapi/openapi.json
- operator/v1/0000_50_cluster_storage_operator_01_crd.yaml
- operator/v1/types_storage.go
- operator/v1/zz_generated.swagger_doc_generated.go
https://issues.redhat.com/browse/OCPBUGS-11776
/cc @JoelSpeed
depends on 4.14 PR: https://github.com/openshift/api/pull/1440
> OCPBUGS-11776: VSphereStorageDriver does not document the platform default

- config/v1/types_feature.go
This requires additional work in cluster-kube-apiserver-operator to recognize the gate and enable related APIs accordingly.
> Remove ValidatingAdmissionPolicy from tech preview.

- config/v1/types_feature.go
We need to have the ability to promote these two providers individually. I will teach the library-go code to observer both feature gates for these platforms and then, once we have the new feature gate, status based decisions in place, will be able to promote each of these individually in a single PR.
CC @deads2k have I missed anything for adding a new feature gate?
> [OCPCLOUD-2034] Add Azure/GCP specific external cloud provider feature gates

- config/v1/types_feature.go
This PR adds an `"AzureWorkloadIdentity"` feature to `TechPreviewNoUpgrade`.
Enhancement proposal: https://github.com/openshift/enhancements/pull/1301
[CCO-187](https://issues.redhat.com//browse/CCO-187)
> config/v1: Add AzureWorkloadIdentity to TechPreviewNoUpgrade

- config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
- config/v1/stable.infrastructure.testsuite.yaml
- config/v1/types_infrastructure.go
This API has not moved and there is no plan to make any change that
would be backward incompatible in the future.
The feature was well tested (and automated) by our QE on this platform,
as well documented on OCP 4.13.
We think this API is ready to be GA'ed.
> OSASINFRA-3152: move `loadBalancer` API to GA for OpenStack

- openapi/generated_openapi/zz_generated.openapi.go
- openapi/openapi.json
- route/v1/generated.proto
- route/v1/route.crd.yaml
- route/v1/route.crd.yaml-patch
- route/v1/stable.route.testsuite.yaml
- route/v1/types.go
- route/v1/zz_generated.swagger_doc_generated.go
For insecureEdgeTerminationPolicy, "Disable" is not a valid option and "Allow" is only valid for edge/reencrypt termination types.
- `route/v1/types.go`: Update doc for `InsecureEdgeTerminationPolicy`
- `openapi/generated_openapi/zz_generated.openapi.go`:
- `openapi/openapi.json`:
- `route/v1/route.crd.yaml`:
- `route/v1/generated.proto`:
- `route/v1/zz_generated.swagger_doc_generated.go`:  Generated Updates
> OCPBUGS-11393: Fix incorrect API usage documentation for insecureEdgeTerminationPolicy

- config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
- config/v1/types_cluster_version.go
This PR add machine-api capability which
disables the following operators
- machine-api-operator
- cluster-autoscaler-operator
- cluster-control-plane-machine-set-operator
This capability is responsible for machines configuration
and heavily targeted for SNO clusters.
> [CNF-5643] add machine-api capability

- config/v1/feature_gates.go
- config/v1/types_feature.go
To enable https://kubernetes.io/blog/2022/05/27/maxunavailable-for-statefulset/ for TP testing.
> WRKLDS-746: TechPreviewNoUpgrade: enable MaxUnavailableStatefulSet

- openapi/generated_openapi/zz_generated.openapi.go
- openapi/openapi.json
- operator/v1/0000_70_cluster-network-operator_01.crd.yaml
- operator/v1/types_network.go
- operator/v1/zz_generated.swagger_doc_generated.go
With https://github.com/ovn-org/ovn-kubernetes/pull/3374 and https://github.com/openshift/machine-config-operator/pull/3676 we stopped enabling IP forwarding globally in the OCP host. It is now only enabled on interfaces that OVNK manages. Additionally iptables rules are put in place to limit what traffic is forwarded. This was to resolve an issue where our node by default acts as a router: https://issues.redhat.com/browse/OCPBUGS-3176
With these changes, by default in OCP we will no longer forward IP traffic. Most users should welcome this change as it means the OCP node will not be forwarding traffic unintentionally on their network. However, in case there is some corner case where a user expects traffic to be forwarded we will expose this new config knob to allow them to go back to the …
> OCPBUGS-3176: Add config knob for enabling ip forwarding

- config/v1/feature_gates.go
- config/v1/types_feature.go
Adding a feature gate as part of the EPIC [OCPNODE-1628](https://issues.redhat.com/browse/OCPNODE-1628)
cc @QiWang19 @mrunalp 
Refers to enhancement https://github.com/openshift/enhancements/pull/1402
> Add `SigstoreImageVerification` feature gate

- openapi/generated_openapi/zz_generated.openapi.go
- openapi/openapi.json
- operator/v1/0000_70_cluster-network-operator_01.crd.yaml
- operator/v1/types_network.go
- operator/v1/zz_generated.swagger_doc_generated.go
We are not supposed to use booleans anymore for API, so modifying the config to use a new type.
https://github.com/openshift/crd-schema-checker/blob/master/pkg/manifestcomparators/comp_no_bools.go#L20
> OCPBUGS-3176: Rework IP Forwarding config

- config/v1/feature_gates.go
- config/v1/types_feature.go
Support for adding labels and tags to GCP resources created for OCP cluster through [enhancement](https://github.com/openshift/enhancements/pull/1217) will be made available as TechPreview in OpenShift-4.14 and the PR contains `GCPLabelsTags` featureGate added for the same.
> CFE-685 : Add TechPreviewNoUpgrade featureGate for GCP Labels and Tags support

- config/v1/feature_gates.go
- config/v1/types_feature.go
Alibaba as a platform should always have been behind a feature gate. To start the process of unwinding it, we should put everything behind a feature gate that is related to Alibaba.
Adding it to Default for now, we must move it to TPNU before 4.14 ships. Will need to make sure that every cluster installed as Alibaba going forward includes the TechPreviewNoUpgrade FeatureSet.
> Add AlibabaPlatform feature gate to TechPreviewNoUpgrade

- config/v1/0000_10_config-operator_01_dns.crd.yaml
found in https://github.com/openshift/cluster-config-operator/pull/314
> make the default DNS only install for default to avoid conflicts

- config/v1/0000_10_config-operator_01_dns-TechPreviewNoUpgrade.crd.yaml
- config/v1/techpreview.dns.testsuite.yaml
- config/v1/types_dns.go
The regex pattern to match the AWS ARN was incorrect.
cc @gcs278 @Miciah @mrunalp @deads2k
> DNS: Fix hostedZoneRole regex Pattern

- config/v1/feature_gates.go
- config/v1/types_feature.go
In order to allow passing dual-stack IPs to the `--node-ip` when using cloud provider, we are enabling the CloudDualStackNodeIPs feature gate.
This affects only behaviour of deployments that want to pass 2 IP addresses as `--node-ip` together with `--cloud-provider`. Before K8s 1.27 this was not possible (you can either have dual-stack Node IPs or use a cloud provider, but not both).
Upstream KEP https://github.com/kubernetes/enhancements/issues/3705 adds ability to pass exactly 2 IPs as `--node-ip` also when using cloud provider, but given its alpha stage, feature gate is required here.
Enablement of this feature gate is not affecting in any way single-stack deployments as well as dual-stack deployments with no cloud provider.
Enablement of this feature gate is not affecting in any way …
> OPNET-263: Enable CloudDualStackNodeIPs feature gate

- config/v1/feature_gates.go
- config/v1/types_feature.go
From https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#topologyspreadconstraints-field:
```
Note: The matchLabelKeys field is a beta-level field and enabled by default in 1.27. You can disable it by disabling the MatchLabelKeysInPodTopologySpread [feature gate](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/).
```
> WRKLDS-757: Drop MatchLabelKeysInPodTopologySpread from TP, it is beta upstream now

- machine/v1/0000_10_controlplanemachineset.crd.yaml
- machine/v1beta1/0000_10_machine.crd.yaml
- machine/v1beta1/0000_10_machinehealthcheck.yaml
- machine/v1beta1/0000_10_machineset.crd.yaml
- tests/hack/test.sh
In order to merge https://github.com/openshift/machine-api-operator/pull/1119 I need to add capability annotations to api files because they are directly copied at machine-api-operator
> [CNF-5643] add capability name to machine crd

- machine/v1/stable.controlplanemachineset.openstack.testsuite.yaml
This patch adds an integration test validating the spec for a default cluster that does not use explicit availability zones.
> openstack: Test no failure domains

- machine/v1beta1/types_awsprovider.go
- machine/v1beta1/zz_generated.swagger_doc_generated.go
- openapi/generated_openapi/zz_generated.openapi.go
- openapi/openapi.json
This PR adds a field named `placementGroupName` to `AWSMachineProviderConfig` so we can start supporting placement groups in machine-api for AWS.
I have updated the swagger documentation and openapi stuff as well using make commands.
> OCPCLOUD-2113: Api changes to support placementGroupName for AWS machines

- openapi/generated_openapi/zz_generated.openapi.go
- openapi/openapi.json
- operator/v1alpha1/types.go
- operator/v1alpha1/zz_generated.swagger_doc_generated.go
Following up on a slack coversation with @soltysh. These (or very similar) types are available in operator/v1.
It was confusing to me when adding a new `operator/v1alpha1` root API (in #1504) whether I should use v1alpha1.OperatorSpec|Status of v1.OperatorSpec|Status.
This will help clarify for future contributors that v1.OperatorSpec|Status should be used. This became especially apparent when working with the `StaticResourceController` and `DeploymentController` in library-go, both of which require v1.OperatorSpec|Status.
> deprecate operator/v1alpha.OperatorSpec|Status and related types

- go.mod
Similar to openshift/client-go#246, this change retracts the only published version v3.9.0+incompatible.
> Retract v3.9.0+incompatible

- config/v1/types_feature.go
This PR promotes the Azure CCM feature gate from TechPreviewNoUpgrade to default.
Will need to be proven with payload tests against config-operator before we merge
> OCPBUGS-13547: Promote Azure CCM from TPNU to default

- route/v1/route-CustomNoUpgrade.crd.yaml
- route/v1/route-TechPreviewNoUpgrade.crd.yaml
- tools/go.mod
- tools/go.sum
- tools/vendor/modules.txt
- tools/vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/patch_validation.go
This just bumps the controller-tools dep in the tools repo to the latest commit and regenerates the manifests, they should now be stable in ordering
> Update controller tools to fix featureset validation ordering

- machine/v1/0000_10_controlplanemachineset.crd.yaml
- machine/v1/stable.controlplanemachineset.openstack.testsuite.yaml
- machine/v1/types_controlplanemachineset.go
When a machine is created with a compute availability zone (defined in a failure domain as `availabilityZone`) and a storage root volume (defined as `rootVolume`) and that `rootVolume` has no specified `rootVolume.availabilityZone`, CAPO will use the compute AZ for the volume AZ.
This can be problematic if the AZ doesn't exist in Cinder.
Source:
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/9d183bd479fe9aed4f6e7ac3d5eee46681c518e7/pkg/cloud/services/compute/instance.go#L439-L442
```golang
func (s *Service) getOrCreateRootVolume(eventObject runtime.Object, instanceSpec *InstanceSpec, imageID string) (*volumes.Volume, error) {
(...)
availabilityZone := instanceSpec.FailureDomain
if rootVolume.AvailabilityZone != "" {
availabilityZone = rootVolume.AvailabilityZone
} …
```
> CPMS/openstack: add root volume AZ validation

- openapi/generated_openapi/zz_generated.openapi.go
- openapi/openapi.json
- operator/v1/0000_70_cluster-network-operator_01.crd.yaml
- operator/v1/types_network.go
- operator/v1/zz_generated.swagger_doc_generated.go
These were missed in the original commit [0] to add maxLogFiles to defaultNetwork:ovnKubernetesConfig:properties:policyAuditConfig
[0] https://github.com/openshift/api/commit/fca46d2460bf38a6e22d987b6e682717365467fc
> Add 'kubebuilder' validations for maxLogFiles

- config/v1/feature_gates.go
- config/v1/types_feature.go
Related enhancement for the feature: https://github.com/openshift/enhancements/pull/1414
This feature is TechPreview in OCP 4.14 but we want some users to be able to switch this on if they want to, hence adding a feature gate where the feature is to be enabled only on TechPreview Clusters and not in standard cluster.
PS: I hope I am supposed to use `with` and not `without` right? (Goal is to disable the feature by default in 4.14 but enable it only in TechPreviewNoUpgrade clusters)
Once this PR merges, this will be revendered into CNO and used there.
> SDN-4024: Add TechPreview feature gate for OVNK-ANP

- config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
- config/v1/types_cluster_version.go
- operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
- operatoringress/v1/0000_50_dns-record.yaml
Enhancement Proposal: https://github.com/openshift/enhancements/pull/1415.
This PR introduces a new `Ingress` cluster capability which allows to enable or disable the default ingress of the OpenShift cluster: the cluster ingress operator and its custom resources. As of now the `Ingress` capability is added to 4.14 capabilityset. This is a subject to change if [the underlying epic](https://issues.redhat.com/browse/NE-1129) changes the target version.
Also, 2 CRDs managed by the cluster ingress operator are annotated with `Ingress` capability: `IngressController`, `DNSRecord`.
> NE-1303: cluster version: add ingress capability

- config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
- config/v1/types_cluster_version.go
- operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
- operatoringress/v1/0000_50_dns-record.yaml
This reverts commit ee31fd8914ccfc897fd7e9defbfd5c66cc047166.
The ingress capability has been deferred to OCP 4.15. Reverting the API change to not rush on the changes in the other repositories (cvo, installer, console operator).
> NE-1303: Revert "cluster version: add ingress capability"

- config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
- config/v1/types_cluster_version.go
Both Build and DeploymentConfig APIs have been selected as optional APIs to reduce the resource footprint and bug surface area for clusters that do not need to utilize the deploymentconfig functionality, such as SNO and OKE. OCP 4.14 will be the first release where both APIs are optional, yet still enabled. Corresponding epics:
- Build: https://issues.redhat.com/browse/BUILD-565
- DC: https://issues.redhat.com/browse/WRKLDS-695
This PR is a prerequisite for merging any work over OAM and OCM. E.g.:
- https://github.com/openshift/cluster-openshift-apiserver-operator/pull/532
- https://github.com/openshift/openshift-apiserver/pull/366
- https://github.com/openshift/cluster-openshift-controller-manager-operator/pull/291
> WRKLDS-728: Make Build and DeploymentConfig API optional through capabilities

- openapi/generated_openapi/zz_generated.openapi.go
- openapi/openapi.json
- operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
- operator/v1/types_ingress.go
- operator/v1/zz_generated.swagger_doc_generated.go
- route/v1/generated.proto
- route/v1/route-CustomNoUpgrade.crd.yaml
- route/v1/route-TechPreviewNoUpgrade.crd.yaml
- route/v1/route.crd.yaml
- route/v1/types.go
- route/v1/zz_generated.swagger_doc_generated.go
The header name max size limit is changed to 255.
This was changed as haproxy does not allow more 255 bytes to be set for header name because of the reason mentioned here: https://jfrog.com/blog/critical-vulnerability-in-haproxy-cve-2021-40346-integer-overflow-enables-http-smuggling/
Issue link: https://issues.redhat.com/browse/OCPBUGS-17414
> OCPBUGS-17414: Limit header names to 255 characters

- config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
- config/v1/stable.infrastructure.testsuite.yaml
- config/v1/types_infrastructure.go
Workload Partitioning was in techpreview to run some tests before the 4.13 GA. The created unit tests and runs have indicated no change in operation to the cluster. The errors we ran into during testing was related to components not having the correct annotation or odd behavior in the CI that was not related to this change. Those have been resolved and now the pipelines and tests are succeeding. 
After the annotations errors were resolved, we had a long history of 4.13 runs succeeding, the 4.14 runs were failing but that seems to have been related to errors in stability in 4.14 nightlies and not this change.
Links:
[Enhancement](https://github.com/openshift/enhancements/pull/1213)
[E2E Tests 4.13 - Sippy](https://sippy.dptools.openshift.org/sippy-ng/tests/4.13?filters=%257B%2522items%2522% …
> OCPBUGS-12205: remove techpreview from cpu partitioning

- config/v1/feature_gates.go
- config/v1/types_feature.go
It was promoted to beta and enabled by default in 1.27 upstream:
- https://github.com/kubernetes/kubernetes/pull/115363
> [WRKLDS-707] remove PDBUnhealthyPodEvictionPolicy feature gate from TechPreviewNoUpgrade

- config/v1/types_cluster_version.go
In order to make capability sets working properly we had to add MAPI capability everywhere where baremetal capability present. We also add api and installer validation to ensure that baremetal and MAPI enabled together, see
1. https://github.com/openshift/installer/pull/7394
2. https://github.com/openshift/api/pull/1537
> OCPBUGS-15654: Add MAPI to all capability sets

- openapi/generated_openapi/zz_generated.openapi.go
- openapi/openapi.json
- operator/v1/0000_12_etcd-operator_01_config.crd.yaml
- operator/v1/techpreview.etcd.testsuite.yaml
- operator/v1/types_etcd.go
- operator/v1/zz_generated.swagger_doc_generated.go
Adds the techpreview API for etcd tuning profiles as will be outlined in https://github.com/openshift/enhancements/pull/1447
This will allow for limited user configuration of etcd's tolerated intervals/timeouts (heartbeat interval, leader election timeout)
Adds the API:
profiles.config.openshift.io/v1alpha1
Used to configure the tuning profiles in etcd
/cc @tjungblu @deads2k @hasbro17 @williamcaban
> Adding etcd tuning profiles api

- tests/hack/test.sh
These tests are being added to and are starting to hit the 15m limit. Need to find a way to speed them up, but for now, lets just extend the timeout to give ourselves some headroom.
> Extend integration test timeout to 30m

- config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
- config/v1/stable.clusterversion.testsuite.yaml
- config/v1/types_cluster_version.go
Opening for discussion as to whether this is the right thing to do
We understand that the `baremetal` capability relies on the `MachineAPI` capability.
The API for capabilities means that, for any cluster that has defined `None` as the baseline capability set, on upgrade, any capability that is new to the cluster version (eg `MachineAPI` added in 4,14), it will be added to the status `enabledCapabilities` on upgrade.
So, if we add this validation, on upgrade, all existing clusters should pass the validation if they either have the `baseline` capability already added, or, want to add it at a later date.
For new clusters in 4.14, if the user wants the baseline set `None`, they are required to enable `MachineAPI` at cluster creation, so the validation should also pass for the create test …
> Ensure baremetal cap is not enabled without MachineAPI cap

- config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
- config/v1/types_cluster_version.go
Capability manages the image registry which allows to distribute Docker images
> CNF-9384: add ImageRegistry capability

- config/v1/feature_gates.go
- config/v1/types_feature.go
This feature is intentionally not enabled in an feature set since it depends on a change to the kube-apiserver operator. The kube-apiserver operator change can't merge (sans hack) until this feature is "known". So the intention is to introduce ValidatingAdmissionPolicy here, then merge the operator change, and finally add ValidatingAdmissionPolicy to the tech preview feature set.
> Introduce ValidatingAdmissionPolicy gate as disabled.

- machine/v1/0000_10_controlplanemachineset.crd.yaml
- machine/v1/types_controlplanemachineset.go
- machine/v1/zz_generated.swagger_doc_generated.go
- openapi/generated_openapi/zz_generated.openapi.go
- openapi/openapi.json
This PR adds a Subnet and InternalLoadBalancer field to the Azure Failure domain.
The subnet is not marked optional in the providerSpec. What's the default? I don't think we can add a required field to the failure domain.
https://github.com/openshift/api/blob/aaae7101a7ad14abba8be0102efc8ab503ccac9d/machine/v1beta1/types_azureprovider.go#L79C2-L79C2
> OCPCLOUD-2130: CPMS: Add subnet to azure FailureDomain

- config/v1/types_feature.go
BuildCsiVolume feature is techPreview since 4.10.  The feature is promted GA
Tests are succeeding for techPreview clusters
Links:
Tracker https://issues.redhat.com/browse/BUILD-689
[sippy 4.14](https://sippy.dptools.openshift.org/sippy-ng/tests/4.14?filters=%257B%2522items%2522%253A%255B%257B%2522columnField%2522%253A%2522current_runs%2522%252C%2522operatorValue%2522%253A%2522%253E%253D%2522%252C%2522value%2522%253A%25227%2522%257D%252C%257B%2522columnField%2522%253A%2522variants%2522%252C%2522not%2522%253Atrue%252C%2522operatorValue%2522%253A%2522contains%2522%252C%2522value%2522%253A%2522never-stable%2522%257D%252C%257B%2522columnField%2522%253A%2522variants%2522%252C%2522not%2522%253Atrue%252C%2522operatorValue%2522%253A%2522contains%2522%252C%2522value%2522%253A%2522aggregated%2522%257 …
> BUILD-689: Promote BuildCSIVolumes featureGate to GA

- operator/v1/0000_12_etcd-operator_01_config-TechPreviewNoUpgrade.crd.yaml
- operator/v1/techpreview.etcd.testsuite.yaml
I mistakenly added this while working on the tests for #1538, I think that it's causing this crd to not get laid down correctly which is causing etcd to not start properly.
> Remove tech preview feature set annotation from existing non-techpreview crd

- Makefile
When the schema check fails, it may need to be overridden. By splitting into it's own target, make will continue to execute other dependencies, but report only the failure of verify-crd-schema.
Presently if it fails, it reports that verify-scripts failed, which is not ideal, since we require this to pass.
I would like to have a separate status check on GitHub for the two sets, those that must pass and those that may not, so will sort that once this is merged. But the intention is that `make verify` still works locally for devs
> Split CRD schema check into separate Makefile target

- config/v1/types_feature.go
Promote the azureWorkloadIdentity feature from the TechPreviewNoUpgrade featureSet to defaultFeatures.
Corresponding cluster-config-operator pr: https://github.com/openshift/cluster-config-operator/pull/345
Feature periodic: https://prow.ci.openshift.org/job-history/gs/origin-ci-test/logs/periodic-ci-openshift-cloud-credential-operator-release-4.14-periodics-e2e-azure-manual-oidc
> CCO-412: Promote azureWorkloadIdentity to defaultFeatures.

- config/v1/types_feature.go
Move PSA enforcement from default feature-set to technical preview.
Still to many PS violations to enforce it for 4.14.
After:
```
$ kubectl create namespace psa-check
namespace/psa-check created
$ kubectl get ns psa-check -oyaml 
apiVersion: v1
kind: Namespace
metadata:
labels:
kubernetes.io/metadata.name: psa-check
pod-security.kubernetes.io/audit: restricted
pod-security.kubernetes.io/audit-version: v1.24
pod-security.kubernetes.io/warn: restricted
pod-security.kubernetes.io/warn-version: v1.24
name: psa-check
resourceVersion: "65330"
uid: d275932b-a57e-4405-ab56-956f511c0ca3
spec:
finalizers:
- kubernetes
status:
phase: Active
```
Before:
```
$ kubectl create namespace psa-check
namespace/psa-check created
$ kubectl get ns psa-check -oyaml 
apiVersion: v1
kind: Namespace
metadata: …
```
> OCPBUGS-16726: psa - move into tech preview for 4.14

- annotations/annotations.go
Given the large number of resources we have, it is useful to have a mechanism to determine which component to contact when a particular one needs attention.  The first direct usage will be for recording who is responsible for in-cluster secrets and configmaps that contain certs, keys, and CA bundles.
> Add an owning-component annotation.

- tools/codegen/pkg/schemapatch/generator.go
Expand the schemapatch generator's "could not unmarshal YAML" error message to reference the file path of the problematic yaml.
Before this change, the error output looked like this:
F0803 04:00:17.068303 2579545 root.go:59] Error running codegen:
error running generator schemapatch on group operator.openshift.io:
could not run schemapatch generator for group/version operator.openshift.io/v1:
could not load generation contexts:
could not unmarshal YAML for type meta inspection: error converting YAML to JSON: yaml: line 480: mapping values are not allowed in this context
make: *** [Makefile:32: update-codegen-crds] Error 255
After this change, the error output looks like this:
F0803 04:03:31.376213 2670287 root.go:59] Error running codegen:
error running generator schemapatch on group …
> schemapatch: Print file path if unmarshal fails

- config/v1/types_feature.go
We would like to promote the GCP CCM to on-by-default, to do this, we need to switch the feature gate to on-by-default.
Opening this early to test run to find obvious issues that need to be fixed before we can promote this.
> OCPCLOUD-1989: Promote GCP CCM from TPNU to default

- insights/v1alpha1/types_insights.go
- insights/v1alpha1/zz_generated.swagger_doc_generated.go
- machineconfiguration/.codegen.yaml
- openapi/generated_openapi/zz_generated.openapi.go
- openapi/openapi.json
- tools/codegen/cmd/swaggerdocs.go
We had intended to change the default comment policy to Enforce to make sure that all fields and structs that are exposed via APIs have complete documentation. This wasn't done correctly as I forgot to update the default flag value.
This updates the default flag value and corrects a handful of missing comments that were failing when making this change
> Fix default comment policy, set to Enforce

- config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
- config/v1/stable.clusterversion.testsuite.yaml
- config/v1/types_cluster_version.go
Add the OLM as a capability.
Note, that OLM and Marketplace have a dependency, the Marketplace should not be enabled and the OLM disabled. This enforcement will be done at the installer level similar to how we enforce [MachineAPI](https://github.com/openshift/installer/blob/7f49fee68faee3f4def8e0cbbf4c27efc3488859/pkg/types/validation/installconfig.go#L162)
> OCPVE-672: feat: add the OLM as a capability

- config/v1/0000_10_config-operator_01_build.crd.yaml
Add missing `capability.openshift.io/name` annotation to the Build cluster configuration CRD. This will ensure that the config object for the Build sub-system is not created when the Build capability is not enabled.
This is a cherrypick of #1616
> OCPBUGS-20439: Capability Annotation for Build CRD

- machineconfiguration/v1/0000_80_machineconfig.crd.yaml
- machineconfiguration/v1/types.go
- machineconfiguration/v1/zz_generated.swagger_doc_generated.go
See https://github.com/openshift/machine-config-operator/pull/3903
> Update machineCopnfig documentation for KernelType.

- config/v1/0000_10_config-operator_01_infrastructure-CustomNoUpgrade.crd.yaml
- config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
- config/v1/types_infrastructure.go
Regex check used for validating GCP label key configured in Infrastructure expects minimum two characters for the key, which is corrected to accept minimum 1 character and maximum of 63 characters.
> OCPBUGS-21781: Rectify Infrastructure GCP label key validation check

- config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
- config/v1/types_cluster_version.go
Currently, we don't have a v4.15 cap set, which causing errors on QE side
> add new capability set version

- config/v1/feature_gates.go
- config/v1/types_feature.go
This adds a featuegate for the work on openshift/api#1596 which I will then bring into the MCO. Keeping this separate as it can merge before the types get into the API.
> add featuregate for MachineConfigNodes

- config/v1/feature_gates.go
- config/v1/types_feature.go
`RetroactiveDefaultStorageClass` moved to GA in 1.28 upstream: https://github.com/kubernetes/website/pull/41206
Feature gate is planned to be removed in 1.29: https://github.com/kubernetes/kubernetes/pull/120861
cc @openshift/storage
> STOR-1343: remove RetroactiveDefaultStorageClass feature gate

- config/v1/feature_gates.go
- config/v1/types_feature.go
enhancement proposal: openshift/enhancements#1426
This feature will TechPreview in OCP 4.15 hence adding a feature gate where the feature is to be enabled only on TechPreview Clusters and not in standard cluster.
Goal is to disable the feature by default in 4.15 but enable it only in TechPreviewNoUpgrade clusters
cc: @simonpasquier
> MON-3410: Add FeatureGate for MetricsServer

- config/v1/0000_10_config-operator_01_infrastructure-CustomNoUpgrade.crd.yaml
- config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
- config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
- config/v1/stable.infrastructure.testsuite.yaml
- config/v1/types.go
- config/v1/types_infrastructure.go
- config/v1/zz_generated.swagger_doc_generated.go
- machineconfiguration/v1/0000_80_controllerconfig.crd.yaml
- openapi/generated_openapi/zz_generated.openapi.go
- openapi/openapi.json
Add a new enum and values for IBM Cloud Service names.
Related: https://issues.redhat.com/browse/SPLAT-1097
> SPLAT-1097: IBMCloud: Add IBM Cloud Service names

- machineconfiguration/v1/types.go
- machineconfiguration/v1/zz_generated.deepcopy.go
close: https://issues.redhat.com/browse/OCPBUGS-15934
**- What I did**
Change the type of `OverlaySize` and `LogSizeMax` resource.Quantity to pointer *resource.Quantity. 
the struct type will be set as 0 automatically when retrieving the ctrcfg object.
I am uncertain if we can make this update to current ContainerruntimeConfig API, I propose this change because the ContainerruntimeConfig API is currently MCO internal.
**- How to verify it**
```
apiVersion: machineconfiguration.openshift.io/v1
kind: ContainerRuntimeConfig
metadata:
name: pidlimit
spec:
machineConfigPoolSelector:
matchLabels:
pools.operator.machineconfiguration.openshift.io/worker: '' 
containerRuntimeConfig:
pidsLimit: 4096 
logLevel: debug
$ oc get containerruntimeconfig  pidlimit -o json | jq …
```
> OCPBUGS-15934: use *resource.Quantity to not automatically set 0

- annotations/annotations.go
Some projects are still on kube 1.27.  Rather than bring them all up to master, backporting this unversioned annotation will broaden adoption.
> backport the openshift owner anntotation

- machine/v1/0000_10_controlplanemachineset-Default.crd.yaml
Confirmed that with this change, the Default feature set CRD is not applied when TechPreviewNoUpgrade feature set is enabled in https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/228 .
```
I1115 16:34:23.292105       1 payload.go:210] excluding Filename: "0000_30_control-plane-machine-set-operator_00_controlplanemachineset-customnoupgrade.crd.yaml" Group: "apiextensions.k8s.io" Kind: "CustomResourceDefinition" Name: "controlplanemachinesets.machine.openshift.io": "TechPreviewNoUpgrade" is required, and release.openshift.io/feature-set=CustomNoUpgrade
I1115 16:34:23.326421       1 payload.go:210] excluding Filename: "0000_30_control-plane-machine-set-operator_00_controlplanemachineset-default.crd.yaml" Group: "apiextensions.k8s.io" Kind: "CustomResourceDefinition" …
```
> SPLAT-1240: annotate default CRD with default feature-set annotation

- config/v1/types_feature.go
Adds the AWS SDK and CAPI Install path to the tech preview feature set, but includes them as Disabled by default.
> features: add alternative installers to TP

- build/v1/consts.go
Since introducing the 'git-lfs' package into the build container, we have had customers that have an issue with the git-lfs automatically being run and would like the option to disable this functionality via the 'GIT_LFS_SKIP_SMUDGE' environment variable.
> OCPBUGS-19358: Allow GIT_LFS_SKIP_SMUDGE environment variable

- machineconfiguration/v1/0000_80_controllerconfig.crd.yaml
- machineconfiguration/v1/0000_80_machineconfigpool.crd.yaml
- machineconfiguration/v1/types.go
Mistakes were made:
- we previously added some strings to the MCO that should have been `metav1.Time`
- we removed the fields from the MCO for 4.14: https://github.com/openshift/machine-config-operator/pull/3866 
- the fields were marked required after our API migration which merged for 4.15
- during upgrades, there is a race condition between when the ControllerConfig/MachineConfigPool CRDs get applied and when the "old"  (4.14) MCO controller pods get replaced during an upgrade 
- If we lose the race, this is breaking CI because the MCO goes `Available=False` when the "old" MCO render_controller [fails to supply the fields](https://github.com/openshift/machine-config-operator/blob/76e4c1867cbf37bd8ba9a953fa83623de817bb93/pkg/operator/sync.go#L1365C41-L1365C41) and returns an error
What …
> OCPBUGS-22364: Make MCO certificate observability fields optional for 4.15

- config/v1/0000_10_config-operator_01_infrastructure-CustomNoUpgrade.crd.yaml
- config/v1/0000_10_config-operator_01_infrastructure-TechPreviewNoUpgrade.crd.yaml
- config/v1/feature_gates.go
- config/v1/techpreview.infrastructure.testsuite.yaml
- config/v1/types_feature.go
- config/v1/types_infrastructure.go
- config/v1/zz_generated.swagger_doc_generated.go
- openapi/generated_openapi/zz_generated.openapi.go
- openapi/openapi.json
This feature attempts to provide a DNS alternative to customers that have specific restrictions around using the cloud provider default DNS.
These API changes are being introduced to indicate the state and type of DNS solution used within the cluster. Currently, this feature applies to AWS, Azure and GCP platforms, but this PR only focuses on GCP support. This new status field indicates in its default state that the OpenShift cluster is using the DNS solution provided by default by the underlying cloud platform. For example, that would be Route53 in the case of the AWS platform.
When Enabled by the Installer, this status field indicates that the default Cloud DNS is not in use. The cluster utilizes a self-hosted DNS solution to achieve a successful cluster installation. The user then has …
> CORS-2429: Update GCP PlatformStatus for user provided dns

- config/v1/types_feature.go
Enables AWS SDK alternate infrastructure in tech preview feature set.
> CORS-2979: Include AWS Alt Infra in Tech Preview

- machineconfiguration/v1alpha1/0000_80_machineconfignode-CustomNoUpgrade.crd.yaml
- machineconfiguration/v1alpha1/0000_80_machineconfignode-TechPreviewNoUpgrade.crd.yaml
These CRD selectors do not match the constants in types_machineconfignode.go I'd prefer to change the CRD now before 4.15 is cut. But if not, I can change the types later.
> fix MCN CRD to use proper Drained and Cordoned condition types

- config/v1/0000_10_config-operator_01_network-CustomNoUpgrade.crd.yaml
- config/v1/0000_10_config-operator_01_network-Default.crd.yaml
- config/v1/0000_10_config-operator_01_network-TechPreviewNoUpgrade.crd.yaml
- config/v1/0000_10_config-operator_01_network.crd.yaml
- config/v1/custom.network.testsuite.yaml
- config/v1/feature_gates.go
- config/v1/stable.network.testsuite.yaml
- config/v1/techpreview.network.testsuite.yaml
- config/v1/types_feature.go
- config/v1/types_network.go
- config/v1/zz_generated.deepcopy.go
- config/v1/zz_generated.swagger_doc_generated.go
- openapi/generated_openapi/zz_generated.openapi.go
- openapi/openapi.json
- operator/v1/0000_70_cluster-network-operator_01-CustomNoUpgrade.crd.yaml
- operator/v1/0000_70_cluster-network-operator_01-Default.crd.yaml
- operator/v1/0000_70_cluster-network-operator_01-TechPreviewNoUpgrade.crd.yaml
- operator/v1/0000_70_cluster-network-operator_01.crd.yaml
- operator/v1/custom.network.testsuite.yaml
- operator/v1/stable.network.testsuite.yaml
- operator/v1/techpreview.network.testsuite.yaml
- operator/v1/types_network.go
- operator/v1/zz_generated.swagger_doc_generated.go
Enhancement: https://github.com/openshift/enhancements/pull/1064
Changes include:
- Add new 'mode' flag to 'spec.Migration' in Networks.operator.openshift.io
- Add status.conditions to networks.config.openshift.io
- Restrict the newly added fields to TechPreview
This PR is based on https://github.com/openshift/api/pull/1546 and https://github.com/openshift/api/pull/1560 with minor changes.
> NP-793: SDN live migration

- Dockerfile.rhel8
Full chain is 
1. https://github.com/openshift/api/pull/1666
2. https://github.com/openshift/cluster-config-operator/pull/379
3. https://github.com/openshift/installer/pull/7666
4. https://github.com/openshift/cluster-config-operator/pull/349
5. https://github.com/openshift/cluster-config-operator/pull/382
6. https://github.com/openshift/cluster-config-operator/pull/380
7. https://github.com/openshift/cluster-config-operator/pull/381
8. https://github.com/openshift/api/pull/1669
9. https://github.com/openshift/cluster-config-operator/pull/380
10. https://github.com/openshift/api/pull/1665
11. https://github.com/openshift/api/pull/1662
12. https://github.com/openshift/api/pull/1642
13. https://github.com/openshift/release/pull/43522
14. https://github.com/openshift/api/pull/1635
15. …
> have the CVO manage CRDs from the api image

- README.md
Just a minor doc change - mentioning the "make generate-with-container" option when file generation fails.
> Add a mention of 'make generate-with-container' to the README file

- config/v1/feature_gates.go
- config/v1/types_feature.go
This adds a feature gate for the implementation of [openshift/enhancements#1496](https://github.com/openshift/enhancements/pull/1496) by the MCO team.  This feature is planned to be released in 4.15 as TechPreview.
> add feature gate for MCO boot images updates

- config/v1/feature_gates.go
- config/v1/types_feature.go
Based on discussion in https://redhat-internal.slack.com/archives/C065R4NCLGM/p1701682788330769, we need to disable this feature gate until we have time to test and configure the credentials providers.
This will require us to make changes in the MCO to set up new configuration and run the credentials binaries on the host.
CC @elmiko @soltysh
> Set DisableKubeletCloudCredentialProviders upstream feature gate to False

- config/v1/feature_gates.go
- config/v1/types_feature.go
This patch adds a new `PinnedImages` feature gate for the pin and pre-load images feature described [here](https://github.com/openshift/enhancements/blob/master/enhancements/machine-config/pin-and-pre-load-images.md).
Related: https://issues.redhat.com/browse/MCO-838
Related: https://github.com/openshift/enhancements/blob/master/enhancements/machine-config/pin-and-pre-load-images.md
> MCO-838: Add feature gate for pinned images

- config/v1/0000_10_config-operator_01_authentication.crd-CustomNoUpgrade.yaml
- config/v1/0000_10_config-operator_01_authentication.crd-TechPreviewNoUpgrade.yaml
- config/v1/0000_10_config-operator_01_authentication.crd.yaml
- config/v1/custom.authentication.testsuite.yaml
- config/v1/stable.authentication.testsuite.yaml
- config/v1/techpreview.authentication.testsuite.yaml
- config/v1/types_authentication.go
- payload-manifests/crds/0000_10_config-operator_01_authentication.crd-CustomNoUpgrade.yaml
- payload-manifests/crds/0000_10_config-operator_01_authentication.crd-TechPreviewNoUpgrade.yaml
- payload-manifests/crds/0000_10_config-operator_01_authentication.crd.yaml
> AUTH-439: authentication: use CRD validation for the 'type' field

- config/v1/types_feature.go
Cherry-Pick of https://github.com/openshift/api/pull/1575
Move PSA enforcement from default feature-set to technical preview.
Still to many PS violations to enforce it for 4.15.
After:
```
$ kubectl create namespace psa-check
namespace/psa-check created
$ kubectl get ns psa-check -oyaml 
apiVersion: v1
kind: Namespace
metadata:
labels:
kubernetes.io/metadata.name: psa-check
pod-security.kubernetes.io/audit: restricted
pod-security.kubernetes.io/audit-version: v1.24
pod-security.kubernetes.io/warn: restricted
pod-security.kubernetes.io/warn-version: v1.24
name: psa-check
resourceVersion: "65330"
uid: d275932b-a57e-4405-ab56-956f511c0ca3
spec:
finalizers:
- kubernetes
status:
phase: Active
```
Before:
```
$ kubectl create namespace psa-check
namespace/psa-check created
$ kubectl get ns …
```
> OCPBUGS-26441: disable psa

- Dockerfile.rhel8
- Makefile
- hack/update-payload-featuregates.sh
- hack/verify-payload-featuregates.sh
- payload-command/render/config.go
- payload-manifests/featuregates/featureGate-CustomNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-Default.yaml
- payload-manifests/featuregates/featureGate-LatencySensitive.yaml
- payload-manifests/featuregates/featureGate-TechPreviewNoUpgrade.yaml
This will allow payload inspect tools to report which features have been
created and promoted between various levels.  This means we cannot
remove featuregates for at least a release after their introduction.
> Add generated featuregate files inertly to payloads

- config/v1alpha1/register.go
https://github.com/openshift/api/pull/1457 did not add ImagePolicyList and ClusterImagePolicyList to scheme known types, led to error `no kind "ClusterImagePolicyList" is registered for version "config.openshift.io/v1alpha1" in scheme`.
> Add ImagePolicyList and ClusterImagePolicyList to scheme known types

- machine/v1beta1/types_vsphereprovider.go
- machine/v1beta1/zz_generated.deepcopy.go
- machine/v1beta1/zz_generated.swagger_doc_generated.go
- openapi/generated_openapi/zz_generated.openapi.go
- openapi/openapi.json
This PR intends to address RFE https://issues.redhat.com/browse/RFE-1799. Additional tags are provided by the declaring a slice of tags referenced by their URN ID. This is consistent with how [CAPV ingests additional tags](https://github.com/openshift/cluster-api-provider-vsphere/blob/b21c0ba942580e08352ad6b3170ee17a010a2a00/apis/v1beta1/types.go#L190-L193) for a VM.
> SPLAT-1385: introduce TagIDs field to vSphere providerSpec

- config/v1/feature_gates.go
- config/v1/types_feature.go
- payload-manifests/featuregates/featureGate-Default.yaml
- payload-manifests/featuregates/featureGate-LatencySensitive.yaml
- payload-manifests/featuregates/featureGate-TechPreviewNoUpgrade.yaml
Add a new `UpgradeStatus` feature gate for the work towards improved upgrade status & health insights information provided via a future `oc adm upgrade status` command.
The code for this feature does not exist yet except for experimental client-side logic implemented in `oc`.
Related: https://issues.redhat.com/browse/OTA-1114
Related: https://github.com/jupierce/oc-update-design-ideas/blob/main/status.md
> OTA-1169: Add feature gate for upgrade status

- config/v1/0000_10_config-operator_01_authentication.crd-Default-Hypershift.yaml
- config/v1/0000_10_config-operator_01_authentication.crd-Default-Hypershift.yaml-patch
- config/v1/0000_10_config-operator_01_authentication.crd-Default.yaml
- config/v1/0000_10_config-operator_01_authentication.crd-TechPreviewNoUpgrade.yaml
- config/v1/0000_10_config-operator_01_authentication.crd-TechPreviewNoUpgrade.yaml-patch
- config/v1/stable.authentication.testsuite.yaml
- config/v1/stable.hypershift.authentication.testsuite.yaml
- payload-manifests/crds/0000_10_config-operator_01_authentication.crd-Default-Hypershift.yaml
- payload-manifests/crds/0000_10_config-operator_01_authentication.crd-Default.yaml
This allows a new configuration on hypershfit by default that isn't in OCP self managed by default.
Long term we need to change how we generate these types to avoid having a fragile, potentially mismatching type.
/hold
needs testing and 
1. move the rendering to merge first
2. update installer to pass the clusterprofile arg
3. update hypershift to pass the clusterprofile arg
4. merge the rest
tested with `./render  --cluster-profile=ibm-cloud-managed --rendered-manifest-dir=../installer-input-manifests --payload-version=fake --asset-output-dir=../output-hypershift --image-manifests=../image-input-manifests` and the diff is correct for featuregate specified in input manifests and the clusterprofile in the arg.
A likely better approach in 4.16 with more time is to read the clusterprofile …
> OCPBUGS-27366: add separate authentication config manifest for hypershift

- cloudnetwork/v1/001-cloudprivateipconfig.crd.yaml
- cloudnetwork/v1/001-cloudprivateipconfig.crd.yaml-patch
CloudPrivateIPConfig's name is supposed to be an IPv4 or IPv6 address. However, the K8s constraints do not allow colons in the names of the resources, so for IPv6 addresses the names are the addresses fully expanded with colons replaced with dots. E.g. `fc00:f853:ccd:e793::54` becomes `fc00.f853.0ccd.e793.0000.0000.0000.0054`. This means that standard K8s validation of `format: ipv6` will not work as it'll try parsing the address using golang's `net` library and that will fail due to `s/\:/\./`.
This commit replaces `format: ipv6` with a pattern that matches fully expanded IPv6 addresses to fix the problem.
> OCPBUGS-27222: Allow modified IPv6 address as CPIC name

- config/v1/types_feature.go
- operator/v1/0000_70_cluster-network-operator_01-Default.crd.yaml
- operator/v1/stable.network.testsuite.yaml
- operator/v1/types_network.go
- payload-manifests/featuregates/featureGate-Default.yaml
- payload-manifests/featuregates/featureGate-LatencySensitive.yaml
CI history for this feature:
master
[pull-ci-openshift-cluster-network-operator-master-e2e-aws-live-migration-sdn-ovn](https://prow.ci.openshift.org/job-history/gs/test-platform-results/pr-logs/directory/pull-ci-openshift-cluster-network-operator-master-e2e-aws-live-migration-sdn-ovn)
[pull-ci-openshift-cluster-network-operator-master-e2e-aws-live-migration-sdn-ovn-rollback](https://prow.ci.openshift.org/job-history/gs/test-platform-results/pr-logs/directory/pull-ci-openshift-cluster-network-operator-master-e2e-aws-live-migration-sdn-ovn-rollback)
4.15
[pull-ci-openshift-cluster-network-operator-master-e2e-aws-live-migration-sdn-ovn](https://prow.ci.openshift.org/?job=pull-ci-openshift-cluster-network-operator-release-4.15-e2e-aws-live-migration-sdn-ovn) …
> NP-874: Promote SDN Live Migration to GA

- openapi/generated_openapi/zz_generated.openapi.go
- openapi/openapi.json
- route/v1/generated.proto
- route/v1/route-CustomNoUpgrade.crd.yaml
- route/v1/route-TechPreviewNoUpgrade.crd.yaml
- route/v1/route.crd.yaml
- route/v1/types.go
- route/v1/zz_generated.swagger_doc_generated.go
Add UnservableInFutureVersions as a route status condition type. This change allows the router to indicate that a route is using an unsupported configuration and will be unservable in the future. The ingress operator may use this condition to block upgrades.
More details in forum-ocp-updates [slack thread](https://redhat-internal.slack.com/archives/CEGKQ43CP/p1704894930666179) and latest updates discussion in forum-api-review [slack thread](https://redhat-internal.slack.com/archives/CE4L0F143/p1706626476105289)
> OCPBUGS-26498: Add UnservableInFutureVersions route status condition type

- cloudnetwork/v1/001-cloudprivateipconfig.crd.yaml
- cloudnetwork/v1/001-cloudprivateipconfig.crd.yaml-patch
CloudPrivateIPConfig's name is supposed to be an IPv4 or IPv6 address. However, the K8s constraints do not allow colons in the names of the resources, so for IPv6 addresses the names are the addresses fully expanded with colons replaced with dots. E.g. `fc00:f853:ccd:e793::54` becomes `fc00.f853.0ccd.e793.0000.0000.0000.0054`. This means that standard K8s validation of `format: ipv6` will not work as it'll try parsing the address using golang's `net` library and that will fail due to `s/\:/\./`.
This commit replaces `format: ipv6` with a pattern that matches fully expanded IPv6 addresses to fix the problem.
> OCPBUGS-28902: Allow modified IPv6 address as CPIC name

- config/v1/types_feature.go
- operator/v1/0000_70_cluster-network-operator_01-Default.crd.yaml
- operator/v1/stable.network.testsuite.yaml
- operator/v1/types_network.go
- payload-manifests/featuregates/featureGate-Default.yaml
- payload-manifests/featuregates/featureGate-LatencySensitive.yaml
CI history for this feature:
master
[pull-ci-openshift-cluster-network-operator-master-e2e-aws-live-migration-sdn-ovn](https://prow.ci.openshift.org/job-history/gs/test-platform-results/pr-logs/directory/pull-ci-openshift-cluster-network-operator-master-e2e-aws-live-migration-sdn-ovn)
[pull-ci-openshift-cluster-network-operator-master-e2e-aws-live-migration-sdn-ovn-rollback](https://prow.ci.openshift.org/job-history/gs/test-platform-results/pr-logs/directory/pull-ci-openshift-cluster-network-operator-master-e2e-aws-live-migration-sdn-ovn-rollback)
4.15
[pull-ci-openshift-cluster-network-operator-master-e2e-aws-live-migration-sdn-ovn](https://prow.ci.openshift.org/?job=pull-ci-openshift-cluster-network-operator-release-4.15-e2e-aws-live-migration-sdn-ovn) …
> NP-905: [release-4.15] Promote Live Migration to GA

- machineconfiguration/v1/types.go
BuildInterrupted indicates that the build has been stopped by some sort of user action or outside force. It is not necessarily a failure but causes the build to be thrown away.
> OCPBUGS-18991: Add BuildInterrupted type

- config/v1/0000_10_config-operator_01_network-Default.crd.yaml
- config/v1/stable.network.testsuite.yaml
- config/v1/types_network.go
- payload-manifests/crds/0000_10_config-operator_01_network-Default.crd.yaml
This is a follow up to https://github.com/openshift/api/pull/1747.
It was found during testing that ca64d33e45b4097c538b486da3f1477674c2159d missed moving the `status.condtions` (intorudced [here](https://github.com/openshift/api/commit/458a0f1a4a5a44888ea349743c718ad1a041b93d)) of network.config to GA.
/cc @martinkennelly @pliurh
> OCPBUGS-29075: Move network.config status.conditions to GA

- config/v1/0000_10_config-operator_01_network-Default.crd.yaml
- config/v1/stable.network.testsuite.yaml
- config/v1/types_network.go
- payload-manifests/crds/0000_10_config-operator_01_network-Default.crd.yaml
This is a follow up to https://github.com/openshift/api/pull/1749.
It was found during testing that https://github.com/openshift/api/commit/75431de1f00c6058724cfdc5ce7d16731353492b missed moving the status.condtions (intorudced [here](https://github.com/openshift/api/commit/458a0f1a4a5a44888ea349743c718ad1a041b93d)) of network.config to GA.
> [release-4.15] OCPBUGS-29074: Move network.config conditions to GA

- operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
- operator/v1/types_csi_cluster_driver.go
When trying to set up KMS encryption in us-isob-east-1 region validation fails on the custom resource.
> OCPBUGS-29196: Update AWSCSIDriverConfigSpec fields validation to accept all current AWS partitions

- config/v1/0000_00_cluster-version-operator_01_clusterversion-CustomNoUpgrade.crd.yaml
- config/v1/0000_00_cluster-version-operator_01_clusterversion-Default.crd.yaml
- config/v1/0000_00_cluster-version-operator_01_clusterversion-TechPreviewNoUpgrade.crd.yaml
- config/v1/types_cluster_version.go
- operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
- operatoringress/v1/0000_50_dns-record.yaml
Retake of https://github.com/openshift/api/pull/1516.
Enhancement Proposal: https://github.com/openshift/enhancements/pull/1415.
This PR introduces a new `Ingress` cluster capability which allows to enable or disable the default ingress of the OpenShift cluster: the cluster ingress operator and its custom resources. The `Ingress` capability is added to a new 4.16 capabilityset as it's the first capability added for 4.16. The two CRDs managed by the cluster ingress operator are annotated with `Ingress` capability: `IngressController`, `DNSRecord`.
> NE-1303: cluster version: add v4.16 set and ingress capability

- config/v1/0000_00_cluster-version-operator_01_clusterversion-CustomNoUpgrade.crd.yaml
- config/v1/0000_00_cluster-version-operator_01_clusterversion-Default.crd.yaml
- config/v1/0000_00_cluster-version-operator_01_clusterversion-TechPreviewNoUpgrade.crd.yaml
- config/v1/types_cluster_version.go
- config/v1/zz_generated.swagger_doc_generated.go
- openapi/generated_openapi/zz_generated.openapi.go
- openapi/openapi.json
Catching up with openshift/enhancements@c446cd7846 (openshift/enhancements#1420), which points out that this type was never implemented, because `Recommended=Unknown` is sufficient to say "we're trying (and failing) to figure out if some of the target's risks apply to the cluster".
> config/v1/types_cluster_version: Drop never-implemented 'Evaluating' conditionalUpdates condition type

- config/v1/0000_10_config-operator_01_authentication.crd-CustomNoUpgrade.yaml
- config/v1/0000_10_config-operator_01_authentication.crd-Default-Hypershift.yaml
- config/v1/0000_10_config-operator_01_authentication.crd-Default-Hypershift.yaml-patch
- config/v1/0000_10_config-operator_01_authentication.crd-TechPreviewNoUpgrade.yaml
- config/v1/types_authentication.go
- payload-manifests/crds/0000_10_config-operator_01_authentication.crd-CustomNoUpgrade.yaml
- payload-manifests/crds/0000_10_config-operator_01_authentication.crd-Default-Hypershift.yaml
- payload-manifests/crds/0000_10_config-operator_01_authentication.crd-TechPreviewNoUpgrade.yaml
Manual backport of https://github.com/openshift/api/pull/1771
/assign @deads2k
> OCPBUGS-29435: allow multiple audiences to be configured for kube-apiserver

- operator/v1/0000_70_cluster-network-operator_01-CustomNoUpgrade.crd.yaml
- operator/v1/0000_70_cluster-network-operator_01-Default.crd.yaml
- operator/v1/0000_70_cluster-network-operator_01-TechPreviewNoUpgrade.crd.yaml
- operator/v1/stable.network.testsuite.yaml
- operator/v1/types_network.go
gatewayConfig.ipForwarding shall only allow "", "Global" and "Restricted".
Reported-at: https://issues.redhat.com/browse/OCPBUGS-23788
Launch clusterbot test cluster with: `launch 4.16,openshift/api#1691,openshift/cluster-network-operator#2172 aws`
(or try with gcp as well if aws fails)
> OCPBUGS-23788: Only allow valid values for gatewayConfig.ipForwarding

- operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
- operator/v1/types_csi_cluster_driver.go
Cherry-pick https://github.com/openshift/api/commit/72a9eae21ecb292364d00707ca0cb062bead70b0 into release-4.15
> [4.15] OCPBUGS-29370: Update AWSCSIDriverConfigSpec fields validation to accept all current AWS partitions

- tools/codegen/cmd/crd_manifest_merge.go
- tools/codegen/pkg/manifestmerge/filters.go
- tools/codegen/pkg/manifestmerge/generator.go
fulfills IOU from the featuregate PR
> make the serialized featuregate location an input param

- config/.codegen.yaml
- config/v1/0000_10_config-operator_01_authentication.crd-Hypershift.yaml
- config/v1/0000_10_config-operator_01_authentication.crd-SelfManagedHA-CustomNoUpgrade.yaml
- config/v1/0000_10_config-operator_01_authentication.crd-SelfManagedHA-Default.yaml
- config/v1/0000_10_config-operator_01_authentication.crd-SelfManagedHA-TechPreviewNoUpgrade.yaml
- config/v1/0000_10_config-operator_01_authentication.crd-SingleNode-CustomNoUpgrade.yaml
- config/v1/0000_10_config-operator_01_authentication.crd-SingleNode-Default.yaml
- config/v1/0000_10_config-operator_01_authentication.crd-SingleNode-TechPreviewNoUpgrade.yaml
- config/v1/custom.authentication.single.testsuite.yaml
- config/v1/custom.authentication.testsuite.yaml
- config/v1/stable.authentication.single.testsuite.yaml
- config/v1/stable.hypershift.authentication.testsuite.yaml
- config/v1/techpreview.authentication.single.testsuite.yaml
- machine/v1/manual-override-crd-manifests/controlplanemachinesets.machine.openshift.io/SelfManagedHA.yaml
- payload-manifests/crds/0000_10_config-operator_01_authentication.crd-Hypershift.yaml
- payload-manifests/crds/0000_10_config-operator_01_authentication.crd-SelfManagedHA-CustomNoUpgrade.yaml
- payload-manifests/crds/0000_10_config-operator_01_authentication.crd-SelfManagedHA-Default.yaml
- payload-manifests/crds/0000_10_config-operator_01_authentication.crd-SelfManagedHA-TechPreviewNoUpgrade.yaml
- payload-manifests/crds/0000_10_config-operator_01_authentication.crd-SingleNode-CustomNoUpgrade.yaml
- payload-manifests/crds/0000_10_config-operator_01_authentication.crd-SingleNode-Default.yaml
- payload-manifests/crds/0000_10_config-operator_01_authentication.crd-SingleNode-TechPreviewNoUpgrade.yaml
- platform/v1alpha1/manual-override-crd-manifests/platformoperators.platform.openshift.io/PlatformOperators.yaml
- platform/v1alpha1/types.go
- platform/v1alpha1/zz_generated.featuregated-crd-manifests.yaml
- platform/v1alpha1/zz_generated.featuregated-crd-manifests/platformoperators.platform.openshift.io/PlatformOperators.yaml
- tools/codegen/pkg/generation/types.go
- tools/codegen/pkg/manifestmerge/filters.go
- tools/codegen/pkg/manifestmerge/generator.go
Adds clusterProfile as a dimension for determining featureset.  this is used by hypershift today to manage external OIDC.
> Merge manifests based on clusterProfile and featureSet

- config/v1/feature_gates.go
- payload-manifests/featuregates/featureGate-Default-Hypershift.yaml
- payload-manifests/featuregates/featureGate-Default-SelfManagedHA.yaml
- payload-manifests/featuregates/featureGate-Default-SingleNode.yaml
- payload-manifests/featuregates/featureGate-Default.yaml
[SPLAT-1293](https://issues.redhat.com/browse/SPLAT-1293)
- Changed vSphereStaticIPs to now be on by default for GA support removing the need to set TechPreviewNoUpgrade.
- https://github.com/openshift/installer/pull/7943
> SPLAT-1293: Moved vSphereStaticIPs into Default from TechPreview

- network/v1/001-clusternetwork-crd.yaml
- network/v1/002-hostsubnet-crd.yaml
- network/v1/003-netnamespace-crd.yaml
- network/v1/004-egressnetworkpolicy-crd.yaml
- network/v1/generated.proto
- network/v1/types.go
- network/v1/zz_generated.featuregated-crd-manifests.yaml
- network/v1/zz_generated.featuregated-crd-manifests/clusternetworks.network.openshift.io/AAA_ungated.yaml
- network/v1/zz_generated.featuregated-crd-manifests/egressnetworkpolicies.network.openshift.io/AAA_ungated.yaml
- network/v1/zz_generated.featuregated-crd-manifests/hostsubnets.network.openshift.io/AAA_ungated.yaml
- network/v1/zz_generated.featuregated-crd-manifests/netnamespaces.network.openshift.io/AAA_ungated.yaml
> update network group to use "normal" generation

- config/v1/0000_10_config-operator_01_infrastructure-Default.crd.yaml
- config/v1/feature_gates.go
- config/v1/stable.infrastructure.testsuite.yaml
- config/v1/techpreview.infrastructure.testsuite.yaml
- machineconfiguration/v1/0000_80_controllerconfig-Default.crd.yaml
- machineconfiguration/v1/stable.controllerconfig.testsuite.yaml
- payload-manifests/crds/0000_10_config-operator_01_infrastructure-Default.crd.yaml
- payload-manifests/featuregates/featureGate-Default-Hypershift.yaml
- payload-manifests/featuregates/featureGate-Default-SelfManagedHA.yaml
- payload-manifests/featuregates/featureGate-Default-SingleNode.yaml
- payload-manifests/featuregates/featureGate-Default.yaml
This PR promotes the PlatformLoadBalancer to GA for bare-metal and vSphere platforms. The feature has been in TP for long enough so that we are ready to promote it.
> OPNET-466: PlatformLoadBalancer becomes GA for On-Prem

- README.md
I got this far before needing to get dressed for the Daddy Daughter Dance.
/hold
> add section about adding new APIs

- README.md
> explain roughly what the new generator is doing

- tests/generator.go
On my machine, this reduces the runtime of the integration tests from about 28m to 6m.
The change here is that we install/uninstall the CRD file once per suite file, rather than once per test case.
We lose randomness of tests within each test suite file, but, the time saving is probably worth that.
Each suite file we have will still be randomised.
> NO-JIRA: Switch integration tests to ordered to save time

- config/v1/types_ingress.go
- config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_ingresses.crd.yaml
- config/v1/zz_generated.featuregated-crd-manifests/ingresses.config.openshift.io/AAA_ungated.yaml
- payload-manifests/crds/0000_10_config-operator_01_ingresses.crd.yaml
Add the necessary kubebuilder syntax to the godoc for the ingress config API's Hostname type in order to hide developer notes from the generated CRD's description for the `status.componentRoutes.currentHostnames` field.  Also, add a user-oriented description of the field with a reference to the relevant RFC.
Before this change, the `oc explain` output for the API field described it in terms of its Go type, kubebuilder syntax, and regular-expression syntax for validation.  After this change, the `oc explain` output for the API field describes it in terms that are relevant to the end-user.
The commit that added the validation did not mention *which* RFC it was enforcing.  The closest RFC seems to be [RFC-1123](https://www.rfc-editor.org/rfc/rfc1123) in that the validation allows the host …
> OCPBUGS-31058: config/ingress: Make Hostname godoc user-friendly

- config/v1/feature_gates.go
- features.md
- payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
This PR:
1. Moves ANP featuregate to also be part of the default set so that the feature is enabled by default (gate was being used from CNO)
2. Work related to https://issues.redhat.com/browse/SDN-4157 4.16 epic ANP
3. Aim is to have this feature ON by default on all OCP/HCP clusters
Unsure if I need to do PRs in other repos like CCC? I tried to look through https://docs.google.com/document/d/1zOL38_KDKwAvsx-LMHfyDdX4-jq3HQU1YWBjfuHaM0Q/edit but not sure what the new process is since the API code around FG has changed quiet a bit. After this PR I wonder if I need to do something else, pointers in right direction will be much appreciated!
E2E Test Info: This feature's tests live in: https://github.com/kubernetes-sigs/network-policy-api/tree/main/conformance and they are run as presubmits …
> SDN-4596: Promote `AdminNetworkPolicy` to GA

- config/v1/feature_gates.go
- features.md
- openapi/generated_openapi/zz_generated.openapi.go
- openapi/openapi.json
- operator/v1/tests/clustercsidrivers.operator.openshift.io/VSphereDriverConfiguration.yaml
- operator/v1/types_csi_cluster_driver.go
- operator/v1/zz_generated.crd-manifests/0000_90_csi-driver_01_clustercsidrivers-CustomNoUpgrade.crd.yaml
- operator/v1/zz_generated.crd-manifests/0000_90_csi-driver_01_clustercsidrivers-Default.crd.yaml
- operator/v1/zz_generated.crd-manifests/0000_90_csi-driver_01_clustercsidrivers-TechPreviewNoUpgrade.crd.yaml
- operator/v1/zz_generated.deepcopy.go
- operator/v1/zz_generated.featuregated-crd-manifests.yaml
- operator/v1/zz_generated.featuregated-crd-manifests/clustercsidrivers.operator.openshift.io/VSphereDriverConfiguration.yaml
- operator/v1/zz_generated.swagger_doc_generated.go
- payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
- payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
cc @openshift/storage
Enhancement: https://github.com/openshift/enhancements/pull/1563
> STOR-1803: add vsphere snapshot configuration fields to ClusterCSIDriver

- tests/hack/gen-minimal-test.sh
/assign @deads2k @Elbehery 
This will give you the following output, when either you don't provide arguments, or you're missing `yq`:
```
$ ./tests/hack/gen-minimal-test.sh 
Can't find 'yq' tool in PATH, please install from https://github.com/mikefarah/yq
```
```
$ ./tests/hack/gen-minimal-test.sh 
./tests/hack/gen-minimal-test.sh <folder> <version>: generate minimal tests
Examples:
./tests/hack/gen-minimal-test.sh operator/v1 v1   # Generates minimal tests for operator/v1 folder, and version v1 specifically.
```
> Provide a small help when invoking tests/hack/gen-minimal-test.sh

- tools/codegen/pkg/sippy/json_types.go
PreviousFlakePercentage field in SippyTestInfo struct should be float instead of int given percentage value can be decimal. The data from Sippy does return previous_flake_percentage as decimal.
> NO-JIRA: Change PreviousFlakePercentage value type from int to float

- openapi/generated_openapi/zz_generated.openapi.go
- openapi/openapi.json
- operator/v1/types_machineconfiguration.go
- operator/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfigurations-CustomNoUpgrade.crd.yaml
- operator/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfigurations-DevPreviewNoUpgrade.crd.yaml
- operator/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfigurations-TechPreviewNoUpgrade.crd.yaml
- operator/v1/zz_generated.featuregated-crd-manifests/machineconfigurations.operator.openshift.io/NodeDisruptionPolicy.yaml
- operator/v1/zz_generated.swagger_doc_generated.go
This fixes the godoc on `NodeDisruptionPolicySpecAction`. It incorrectly specified Special as a possible value for the enum, when it wasn't. `Special` is only a possible value for `NodeDisruptionPolicyStatusActionType`, which is not settable by the user.
> clean up NodeDisruptionPolicySpecAction godoc

- operator/v1/tests/networks.operator.openshift.io/AAA_ungated.yaml
- operator/v1/types_network.go
- operator/v1/zz_generated.crd-manifests/0000_70_network_01_networks.crd.yaml
- operator/v1/zz_generated.featuregated-crd-manifests/networks.operator.openshift.io/AAA_ungated.yaml
- operator/v1/zz_generated.featuregated-crd-manifests/networks.operator.openshift.io/NetworkLiveMigration.yaml
New IP and CIDR CEL validations for 4.16 mean we can drop a bunch of complex and hard to reason about CEL introduced over the last release.
The majority of the tests we added are testing basic IPv6 parsing, which is now deferred to `netip.ParseAddr`. There's one case we had that fails, where you have a fully qualified address but with an elided final segment, this appears to be valid so I think we can actually drop that test.
Finally, the only cases I can see where the CEL IP stuff doesn't account, is for the non-zero first octet, which I've added a separate validation for.
CC @bpickard22 @knobunc
> Simplify CEL validations in network operator

- features.md
- features/features.go
- payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
- payload-manifests/featuregates/featureGate-Hypershift-DevPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-DevPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
Adds a capi-installer feature gate for each platform.
/cc @JoelSpeed @deads2k 
FYI:
@r4f4 
@jhixson74 
@bfournie 
@cjschaef 
@yanhua121 
@stephenfin 
@mjturek
@rvanderp3
> features: add capi-installer gate per platform

- config/v1/types_infrastructure.go
- config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_infrastructures-CustomNoUpgrade.crd.yaml
- config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_infrastructures-Default.crd.yaml
- config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_infrastructures-DevPreviewNoUpgrade.crd.yaml
- config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_infrastructures-TechPreviewNoUpgrade.crd.yaml
- config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/AAA_ungated.yaml
- config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/BareMetalLoadBalancer.yaml
- config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/GCPClusterHostedDNS.yaml
- config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/GCPLabelsTags.yaml
- config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/VSphereControlPlaneMachineSet.yaml
- machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_controllerconfigs-CustomNoUpgrade.crd.yaml
- machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_controllerconfigs-Default.crd.yaml
- machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_controllerconfigs-DevPreviewNoUpgrade.crd.yaml
- machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_controllerconfigs-TechPreviewNoUpgrade.crd.yaml
- machineconfiguration/v1/zz_generated.featuregated-crd-manifests/controllerconfigs.machineconfiguration.openshift.io/AAA_ungated.yaml
- machineconfiguration/v1/zz_generated.featuregated-crd-manifests/controllerconfigs.machineconfiguration.openshift.io/BareMetalLoadBalancer.yaml
- machineconfiguration/v1/zz_generated.featuregated-crd-manifests/controllerconfigs.machineconfiguration.openshift.io/GCPClusterHostedDNS.yaml
- machineconfiguration/v1/zz_generated.featuregated-crd-manifests/controllerconfigs.machineconfiguration.openshift.io/GCPLabelsTags.yaml
- machineconfiguration/v1/zz_generated.featuregated-crd-manifests/controllerconfigs.machineconfiguration.openshift.io/VSphereControlPlaneMachineSet.yaml
- openapi/generated_openapi/zz_generated.openapi.go
- openapi/openapi.json
- payload-manifests/crds/0000_10_config-operator_01_infrastructures-CustomNoUpgrade.crd.yaml
- payload-manifests/crds/0000_10_config-operator_01_infrastructures-Default.crd.yaml
- payload-manifests/crds/0000_10_config-operator_01_infrastructures-DevPreviewNoUpgrade.crd.yaml
- payload-manifests/crds/0000_10_config-operator_01_infrastructures-TechPreviewNoUpgrade.crd.yaml
In order to handle ownership of network addresses in a more elegant way,
we are switching list type from `set` to `atomic`. Thanks to this the
whole list will be managed as one, instead of different owners for every
entry on the list.
We are adding CEL validation to fields in PlatformStatus for the
consistency. As this field has already been validated by o/installer,
this should not affect CRs with PlatformStatus already populated.
> OPNET-512: config/v1/types_infrastructure: change set to atomic for networks

- hack/update-payload-crds.sh
- payload-manifests/crds/0000_10_control-plane-machine-set_01_controlplanemachinesets.crd.yaml
This starts shipping all Machine v1 CRDs from the o/api image. This is just CPMS at the moment.
I also took the liberty to sort the list of CRD globs alphabetically, in future lets keep it that way.
/hold this will need to be merged simultaneously with removing the CRD from the CPMS repo
> Add Machine V1 to payload CRDs

- imageregistry/v1/types.go
- imageregistry/v1/zz_generated.crd-manifests/00_configs-CustomNoUpgrade.crd.yaml
- imageregistry/v1/zz_generated.crd-manifests/00_configs-Default.crd.yaml
- imageregistry/v1/zz_generated.crd-manifests/00_configs-DevPreviewNoUpgrade.crd.yaml
- imageregistry/v1/zz_generated.crd-manifests/00_configs-TechPreviewNoUpgrade.crd.yaml
- imageregistry/v1/zz_generated.featuregated-crd-manifests/configs.imageregistry.operator.openshift.io/AAA_ungated.yaml
- imageregistry/v1/zz_generated.featuregated-crd-manifests/configs.imageregistry.operator.openshift.io/ChunkSizeMiB.yaml
> Update SSA tag markers

- example/v1/tests/stableconfigtypes.example.openshift.io/-Example.yaml
- example/v1/tests/stableconfigtypes.example.openshift.io/AAA_ungated.yaml
- example/v1/tests/stableconfigtypes.example.openshift.io/Example.yaml
- example/v1/types_stable.go
- example/v1/zz_generated.crd-manifests/0000_50_my-operator_01_stableconfigtypes-CustomNoUpgrade.crd.yaml
- example/v1/zz_generated.crd-manifests/0000_50_my-operator_01_stableconfigtypes-Default.crd.yaml
- example/v1/zz_generated.crd-manifests/0000_50_my-operator_01_stableconfigtypes-DevPreviewNoUpgrade.crd.yaml
- example/v1/zz_generated.crd-manifests/0000_50_my-operator_01_stableconfigtypes-TechPreviewNoUpgrade.crd.yaml
- example/v1/zz_generated.featuregated-crd-manifests/stableconfigtypes.example.openshift.io/AAA_ungated.yaml
- example/v1/zz_generated.featuregated-crd-manifests/stableconfigtypes.example.openshift.io/Example.yaml
- example/v1/zz_generated.swagger_doc_generated.go
- openapi/generated_openapi/zz_generated.openapi.go
- openapi/openapi.json
This PR adds an example for a new field `BackendQuotaGiB` within `EtcdSpec` type. 
Example for https://github.com/openshift/api/pull/1736
see https://issues.redhat.com/browse/ETCD-513
cc @openshift/openshift-team-etcd  @JoelSpeed  @deads2k
> ETCD-520: add BackendQuotaGiB example

- operator/v1/types_machineconfiguration.go
This PR adds a few new `MachineConfiguration` conditions, which will be used by the MSBIC to inform the user of the results of the boot image reconciliation loop. These conditions will be behind the ManagedBootImages feature gate.
More info:
- [Failure conditions for boot image updates](https://github.com/openshift/enhancements/blob/master/enhancements/machine-config/manage-boot-images.md#error--alert-mechanism)
> add MachineConfiguration conditions for boot image updates

- Makefile
- tests/hack/test.sh
1. RUNTIME_IMAGE_NAME should match what we're running in CI, or .ci-operator.yaml, so make sure they do.
2. In OpenShift CI the colored ginkgo output is causing unnecessary noise, so just don't do it there.
> NO-JIRA: Update runtime image and drop color in CI

- features.md
- features/features.go
- payload-manifests/featuregates/featureGate-Hypershift-DevPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-DevPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
- aws
- nutanix
- openstack
- powervs
- vsphere
Have all passed e2e tests using the capi installer.
Depends on https://github.com/openshift/installer/pull/8343
Depends on https://issues.redhat.com/browse/CORS-3477
> Add eligible CAPI-install platforms to TechPreview

- features.md
- features/features.go
- payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
Update the feature gate framework to reflect that Gateway API is not yet a TechPreview feature. It is only a DevPreview feature.
Gateway API was added as a DevPreviewNoUpgrade feature before recent changes to the FeatureGate framework, and has not progressed to TechPreviewNoUpgrade.    When the FeatureGate framework changed, Gateway API was mistakenly listed as a TechPreviewNoUpgrade feature.
For 4.16 we are adding TechPreview testing to the cluster-ingress-operator for other features, and we do not want to test Gateway API as a tech preview feature.  In fact, it has its own separate test.
- features/features.go is the only edited file.  All other files were generated.
> OCPBUGS-33727: Fix Gateway API Feature Gate

- operator/v1/types_network.go
- operator/v1/zz_generated.crd-manifests/0000_70_network_01_networks.crd.yaml
- operator/v1/zz_generated.featuregated-crd-manifests.yaml
- operator/v1/zz_generated.featuregated-crd-manifests/networks.operator.openshift.io/AAA_ungated.yaml
- operator/v1/zz_generated.featuregated-crd-manifests/networks.operator.openshift.io/NetworkLiveMigration.yaml
By removing the annotation from types_network.go we can rely on the generators to add the cluster profiles.
This commit doesn't introduce any functional changes as CNO was already annotating that CRD with the ibm-cloud-managed cluster profile:
https://github.com/openshift/cluster-network-operator/blob/019fa77b2afb6186320ebe15604f7d26d76bcfab/manifests/0000_70_network_01_networks.crd.yaml#L7
https://github.com/openshift/cluster-network-operator/blob/019fa77b2afb6186320ebe15604f7d26d76bcfab/hack/update-codegen.sh#L63
> NO-JIRA: Enable the ibm-cloud-managed cluster profile on network.operator CRD

- openapi/generated_openapi/zz_generated.openapi.go
- openapi/openapi.json
- route/v1/generated.proto
- route/v1/route-CustomNoUpgrade.crd.yaml
- route/v1/route-TechPreviewNoUpgrade.crd.yaml
- route/v1/route.crd.yaml
- route/v1/types.go
- route/v1/zz_generated.swagger_doc_generated.go
Cherry-Pick of https://github.com/openshift/api/pull/1722
Add UnservableInFutureVersions as a route status condition type. This change allows the router to indicate that a route is using an unsupported configuration and will be unservable in the future. The ingress operator may use this condition to block upgrades.
> [release-4.15] OCPBUGS-28928: Add UnservableInFutureVersions route status condition type

- tools/codegen/cmd/featuregate-test-analyzer.go
- tools/codegen/cmd/featuregate-test-analyzer_test.go
- tools/codegen/pkg/sippy/json_types.go
When validating a feature gate has tests, try to determine if the
feature gate is specific to a platform or architecture and only query
those results.
If it's an installer feature gate, then we don't require specific tests;
use the existing `cluster install` tests.
> Feature gates for platforms, architecture, and installs

- tools/Makefile
Have published a new version of the tools, committing this so that we have history of what I have published.
> Update published Kubebuilder tools

- features.md
- features/features.go
- payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
- payload-manifests/featuregates/featureGate-Hypershift-DevPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-DevPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
Adds a day-0 multi-arch cluster installer feature gate per platform.
AWS: https://issues.redhat.com/browse/OCPSTRAT-1472
Azure: https://issues.redhat.com/browse/OCPSTRAT-1476
GCP: https://issues.redhat.com/browse/OCPSTRAT-1477
> features: add multi-arch feature gate per platform

- console/v1/manual-override-crd-manifests/consoleplugins.console.openshift.io/AAA_ungated.yaml
- console/v1/zz_generated.crd-manifests/90_consoleplugins.crd.yaml
We forgot to remove these two references of the conversion webhook server for v1 <-> v1alpha1 conversions.
/assign @deads2k @JoelSpeed
> OCPBUGS-36213: Remove the conversion webhook reference from the ConsolePlugin CRD spec

- machine/v1beta1/types_awsprovider.go
- machine/v1beta1/zz_generated.deepcopy.go
Since this API does not support kubebuilder marker validations, we added the [range validation (1-7)](https://github.com/openshift/machine-api-operator/pull/1265) as a webhook validation, which will run after that value got defaulted to 0.
However, as discussed in https://issues.redhat.com/browse/CFE-1066, there is a semantic difference between unset and 0
Making this field as pointer would help differentiate between unset and `0`
> OCPBUGS-36469: Update placementGroupPartition to pointer

- operator/v1/tests/ingresscontrollers.operator.openshift.io/IngressControllerLBSubnetsAWS.yaml
- operator/v1/types_ingress.go
- operator/v1/zz_generated.crd-manifests/0000_50_ingress_00_ingresscontrollers-CustomNoUpgrade.crd.yaml
- operator/v1/zz_generated.crd-manifests/0000_50_ingress_00_ingresscontrollers-DevPreviewNoUpgrade.crd.yaml
- operator/v1/zz_generated.crd-manifests/0000_50_ingress_00_ingresscontrollers-TechPreviewNoUpgrade.crd.yaml
- operator/v1/zz_generated.featuregated-crd-manifests/ingresscontrollers.operator.openshift.io/IngressControllerLBSubnetsAWS.yaml
The CEL validation for AWSSubnets enforcing at least 1 subnet to be specified was not correct as it still allowed for empty [] ID and name slices. This fix ensures that at least 1 subnet ID or name is specified if the subnets struct is not nil.
> NE-1530: Fix empty subnet list CEL validation

- features.md
- features/features.go
- payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
- payload-manifests/featuregates/featureGate-Hypershift-DevPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-DevPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
This is for https://github.com/openshift/enhancements/pull/1631
The MCO is experimenting a bootc based OS content update path, to prepare for the deprecation of rpm-ostree. Before bootc is fully ready, we need to gate the path from default mainly for testing purposes.
> Added Feature Gate for Bootc Update Path

- features.md
- features/features.go
- payload-manifests/featuregates/featureGate-Hypershift-DevPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-DevPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
The functionality has merged in the Installer.
AWS: https://issues.redhat.com/browse/MULTIARCH-4567
GCP: https://issues.redhat.com/browse/MULTIARCH-4618
AWS multi-arch day-0 periodics: [sippy link](https://sippy.dptools.openshift.org/sippy-ng/jobs/4.17/analysis?filters=%7B%22items%22%3A%5B%7B%22columnField%22%3A%22name%22%2C%22operatorValue%22%3A%22equals%22%2C%22value%22%3A%22periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-e2e-aws-ovn-heterogeneous-day-0%22%7D%5D%7D)
GCP multi-arch day-0 periodics: [sippy link](https://sippy.dptools.openshift.org/sippy-ng/jobs/4.17/analysis?filters=%7B%22items%22%3A%5B%7B%22columnField%22%3A%22name%22%2C%22operatorValue%22%3A%22equals%22%2C%22value%22%3A%22periodic-ci-openshift-multiarch-master-nightly-4.17-ocp-e2e-gcp-ovn-heterogeneous-day-0%22%7 …
> MULTIARCH-4770: features: move MultiArchInstall[AWS|GCP] to TechPreview

- config/v1/tests/featuregates.config.openshift.io/AAA_ungated.yaml
- config/v1/types_feature.go
- config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_featuregates.crd.yaml
- config/v1/zz_generated.featuregated-crd-manifests/featuregates.config.openshift.io/AAA_ungated.yaml
- payload-manifests/crds/0000_10_config-operator_01_featuregates.crd.yaml
In the past, there was an admission plugin for checking if the value of the featureSet field matched a known one. 
With https://github.com/openshift/kubernetes/pull/1944, the validation was moved to CEL and the check was dropped. 
This PR adds the missing check. 
NOTE that there was an additional check that allowed updates to FG even with an invalid featureSet if the field wasn't modified. I haven't found a way to move this to CEL for kube < 1.30. 
The validation was moved in 4.16, and setting an invalid value breaks an operator and prevents upgrades. This PR allows transitioning from an invalid value to unblock upgrades.
For full backward compatibility we would have to bring back the admission plugin for 4.16 and use for 4.17 use `optionalOldSelf`.
> OCPBUGS-35906: a rule to check if the featureSet is one of the known set of features

- Makefile
When working on #1928, noticed that the payload crds were not generated after running a `make update`. This is because codegen is run after update-scripts. This PR removes update-payload-crds from update-scripts and runs it after codegen.
> Run update-payload-crds after update-codegen-crds

- security/v1/consts.go
Add an annotation constant that reveals what the label syncer would enforce.
It is unclear what the label syncer would set, if alert labels are set or the syncer is turned off.
> AUTH-527: security/v1 - add constant for enforcing psa annotation

- tools/codegen/cmd/featuregate-test-analyzer.go
vsphere-ipi is now just vsphere for the platform name after the move to the variant registry.
> featuregate analyzer: use correct platform name

- envtest-releases.yaml
- tools/Makefile
- tools/publish-kubebuilder-tools/README.md
- tools/publish-kubebuilder-tools/main.go
The newest versions of envtest rely on a published index file to identify and download archives containing the relevant KAS and etcd binaries.
This PR introduces this from 1.30.3 (4.17) so that those updating controller runtime can move away from the deprecated GCS discovery and into this brave new world.
The tooling for publishing kubebuilder artifacts now publishes the binaries as it did before, but, calculates the hash of the archive and adds a new entry to the `envtest-releases.yaml` file in the root of this repo.
This will be used in repositories across OpenShift to use an OpenShift build of KAS, by adding the following flag
```
--index https://raw.githubusercontent.com/openshift/api/master/envtest-releases.yaml
```
They can now drop the `remote-bucket` and `-use-deprecated-gcs` …
> Update envtest publishing to create index file

- tools/codegen/cmd/featuregate-test-analyzer.go
Like vsphere, metal-ipi is now just metal in Sippy. Also show network stack in the summary page
Example: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_api/2003/pull-ci-openshift-api-master-verify/1824454654252027904/artifacts/test/artifacts/feature-promotion-summary.html
> featuregate analyzer: fix platform name for metal

- tools/codegen/cmd/featuregate-test-analyzer.go
Allow a 1-week lookback if it's sufficient, to avoid a long tail of a regression into the historical results
> featuregate analyzer: use 1 week lookback if possible

- openapi/generated_openapi/zz_generated.openapi.go
- openapi/openapi.json
- operator/v1/types_console.go
- operator/v1/zz_generated.crd-manifests/0000_50_console_01_consoles.crd.yaml
- operator/v1/zz_generated.featuregated-crd-manifests/consoles.operator.openshift.io/AAA_ungated.yaml
- operator/v1/zz_generated.swagger_doc_generated.go
Replaces https://github.com/openshift/api/pull/1992
> CONSOLE-4055: Add "Getting started resources" console capability

- config/v1/types_cluster_version.go
- config/v1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversions-CustomNoUpgrade.crd.yaml
- config/v1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversions-Default.crd.yaml
- config/v1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversions-DevPreviewNoUpgrade.crd.yaml
- config/v1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversions-TechPreviewNoUpgrade.crd.yaml
- config/v1/zz_generated.featuregated-crd-manifests/clusterversions.config.openshift.io/AAA_ungated.yaml
- config/v1/zz_generated.featuregated-crd-manifests/clusterversions.config.openshift.io/SignatureStores.yaml
These are both synonyms for v4.16, because there have not been capability-recommendation changes since that release.  4.17 is about to go Generally Available, which means v4.17 will always be a synonym for v4.16.  v4.18 may or may not evolve before 4.18 goes GA.  I think defining synonym capability sets is busywork that takes developer time without adding customer value, but [OCPBUGS-41111][1] points out that so far every 4.y release has had a v4.y capability set string associated with it, and folks might find adjustments to that pattern surprising.  I'm declaring sets for our next two 4.y here to continue the existing set-for-each-4.y pattern (and breaking the set-for-each-4.y-with-a-different-default pattern) to unblock 4.17's GA, but we may revisit this approach in the future with more …
> OCPBUGS-41111: config/v1/types_cluster_version: Add v4.17 and v4.18 capability sets

- config/v1/types_cluster_version.go
- config/v1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversions-CustomNoUpgrade.crd.yaml
- config/v1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversions-Default.crd.yaml
- config/v1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversions-DevPreviewNoUpgrade.crd.yaml
- config/v1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversions-TechPreviewNoUpgrade.crd.yaml
- config/v1/zz_generated.featuregated-crd-manifests/clusterversions.config.openshift.io/AAA_ungated.yaml
- config/v1/zz_generated.featuregated-crd-manifests/clusterversions.config.openshift.io/SignatureStores.yaml
This is a synonym for v4.16, because there have not been capability-recommendation changes since that release.  4.17 is about to go Generally Available, which means v4.17 will always be a synonym for v4.16.  I think defining synonym capability sets is busywork that takes developer time without adding customer value, but [OCPBUGS-41111][1] points out that so far every 4.y release has had a v4.y capability set string associated with it, and folks might find adjustments to that pattern surprising.  I'm declaring the v4.17 set to continue the existing set-for-each-4.y pattern (and breaking the
set-for-each-4.y-with-a-different-default pattern) to unblock 4.17's GA, but we may revisit this approach in the future with more lead time.  This commit backports (without v4.18) #2022 to …
> OCPBUGS-41642: config/v1/types_cluster_version: Add v4.17 capability set

- hack/update-payload-crds.sh
- payload-manifests/crds/0000_10_config-operator_01_backups-CustomNoUpgrade.crd.yaml
- payload-manifests/crds/0000_10_config-operator_01_backups-DevPreviewNoUpgrade.crd.yaml
- payload-manifests/crds/0000_10_config-operator_01_backups-TechPreviewNoUpgrade.crd.yaml
- payload-manifests/crds/0000_10_etcd_01_etcdbackups-CustomNoUpgrade.crd.yaml
- payload-manifests/crds/0000_10_etcd_01_etcdbackups-DevPreviewNoUpgrade.crd.yaml
- payload-manifests/crds/0000_10_etcd_01_etcdbackups-TechPreviewNoUpgrade.crd.yaml
- payload-manifests/crds/0000_10_openshift-controller-manager_01_builds.crd.yaml
- payload-manifests/crds/0000_12_etcd_01_etcds-CustomNoUpgrade.crd.yaml
- payload-manifests/crds/0000_12_etcd_01_etcds-Default.crd.yaml
- payload-manifests/crds/0000_12_etcd_01_etcds-DevPreviewNoUpgrade.crd.yaml
- payload-manifests/crds/0000_12_etcd_01_etcds-TechPreviewNoUpgrade.crd.yaml
- payload-manifests/crds/0000_20_kube-apiserver_01_kubeapiservers.crd.yaml
- payload-manifests/crds/0000_25_kube-controller-manager_01_kubecontrollermanagers.crd.yaml
- payload-manifests/crds/0000_25_kube-scheduler_01_kubeschedulers.crd.yaml
- payload-manifests/crds/0000_30_openshift-apiserver_01_openshiftapiservers.crd.yaml
- payload-manifests/crds/0000_50_authentication_01_authentications.crd.yaml
- payload-manifests/crds/0000_50_openshift-controller-manager_02_openshiftcontrollermanagers.crd.yaml
1. etcd
2. kube-apiserver
3. kube-controller-manager
4. kube-scheduler
5. openshift-apiserver
6. openshift-controller-manager
7. openshift-authentication
to come in other PRs, MCO stuff, image registry, network edge, storage.
> NO-jIRA: move some operator crds to openshift/api

- hack/update-payload-crds.sh
- payload-manifests/crds/0000_10_config-operator_01_clusterimagepolicies-CustomNoUpgrade.crd.yaml
- payload-manifests/crds/0000_10_config-operator_01_clusterimagepolicies-DevPreviewNoUpgrade.crd.yaml
- payload-manifests/crds/0000_10_config-operator_01_clusterimagepolicies-TechPreviewNoUpgrade.crd.yaml
- payload-manifests/crds/0000_80_machine-config_01_containerruntimeconfigs.crd.yaml
- payload-manifests/crds/0000_80_machine-config_01_controllerconfigs-CustomNoUpgrade.crd.yaml
- payload-manifests/crds/0000_80_machine-config_01_controllerconfigs-Default.crd.yaml
- payload-manifests/crds/0000_80_machine-config_01_controllerconfigs-DevPreviewNoUpgrade.crd.yaml
- payload-manifests/crds/0000_80_machine-config_01_controllerconfigs-TechPreviewNoUpgrade.crd.yaml
- payload-manifests/crds/0000_80_machine-config_01_kubeletconfigs.crd.yaml
- payload-manifests/crds/0000_80_machine-config_01_machineconfignodes-CustomNoUpgrade.crd.yaml
- payload-manifests/crds/0000_80_machine-config_01_machineconfignodes-DevPreviewNoUpgrade.crd.yaml
- payload-manifests/crds/0000_80_machine-config_01_machineconfignodes-TechPreviewNoUpgrade.crd.yaml
- payload-manifests/crds/0000_80_machine-config_01_machineconfigpools-CustomNoUpgrade.crd.yaml
- payload-manifests/crds/0000_80_machine-config_01_machineconfigpools-Default.crd.yaml
- payload-manifests/crds/0000_80_machine-config_01_machineconfigpools-DevPreviewNoUpgrade.crd.yaml
- payload-manifests/crds/0000_80_machine-config_01_machineconfigpools-TechPreviewNoUpgrade.crd.yaml
- payload-manifests/crds/0000_80_machine-config_01_machineconfigs.crd.yaml
- payload-manifests/crds/0000_80_machine-config_01_machineconfigurations.crd.yaml
- payload-manifests/crds/0000_80_machine-config_01_machineosbuilds-CustomNoUpgrade.crd.yaml
- payload-manifests/crds/0000_80_machine-config_01_machineosbuilds-DevPreviewNoUpgrade.crd.yaml
- payload-manifests/crds/0000_80_machine-config_01_machineosbuilds-TechPreviewNoUpgrade.crd.yaml
- payload-manifests/crds/0000_80_machine-config_01_machineosconfigs-CustomNoUpgrade.crd.yaml
- payload-manifests/crds/0000_80_machine-config_01_machineosconfigs-DevPreviewNoUpgrade.crd.yaml
- payload-manifests/crds/0000_80_machine-config_01_machineosconfigs-TechPreviewNoUpgrade.crd.yaml
- payload-manifests/crds/0000_80_machine-config_01_pinnedimagesets-CustomNoUpgrade.crd.yaml
- payload-manifests/crds/0000_80_machine-config_01_pinnedimagesets-DevPreviewNoUpgrade.crd.yaml
- payload-manifests/crds/0000_80_machine-config_01_pinnedimagesets-TechPreviewNoUpgrade.crd.yaml
this makes promotion of featuregates more atomic as the CRD schema for Default changes in the same PR that makes the feature default.
/cc @yuqi-zhang
> copy mco crds to be managed by openshfit/api

- hack/update-payload-crds.sh
- payload-manifests/crds/0000_50_storage_01_storages.crd.yaml
- payload-manifests/crds/0000_90_csi-driver_01_clustercsidrivers.crd.yaml
This is a follow-up to https://github.com/openshift/api/pull/2030.
This makes the promotion of featuregates more atomic, as the CRD schema changes in the same PR that changes the feature.
This will prevent changes like [this](https://github.com/openshift/cluster-storage-operator/commit/076e178df7aa8bd9753a2b5de9aa14542412a757) when adding new TechPreview fields to ClusterCSIDriver CRDs.
> NO-JIRA: move storage CRDs to openshift/api

- envtest-releases.yaml
- tools/Makefile
This adds the 1.31.0 openshift version of the kubebuilder binaries to the index. I've already run the script so the artifacts are in place at this point.
Once merged, envtest invocations will be able to leverage the index option and replace the now removed GCS bucket download option.
```
--index https://raw.githubusercontent.com/openshift/api/master/envtest-releases.yaml
```
> NO-JIRA: Publish kubebuilder openshift binaries to 1.31.0

- envtest-releases.yaml
- tools/Makefile
Found out that the release is actually based on 1.31.1 and not 1.31.0
CC @bertinatto
> NO-JIRA: Add envtest archives for K8s 1.31.1

- openapi/generated_openapi/zz_generated.openapi.go
- openapi/openapi.json
- operator/v1/tests/ingresscontrollers.operator.openshift.io/IngressControllerLBOpenStack.yaml
- operator/v1/types_ingress.go
- operator/v1/zz_generated.crd-manifests/0000_50_ingress_00_ingresscontrollers.crd.yaml
- operator/v1/zz_generated.featuregated-crd-manifests/ingresscontrollers.operator.openshift.io/AAA_ungated.yaml
- operator/v1/zz_generated.featuregated-crd-manifests/ingresscontrollers.operator.openshift.io/IngressControllerLBSubnetsAWS.yaml
- operator/v1/zz_generated.featuregated-crd-manifests/ingresscontrollers.operator.openshift.io/SetEIPForNLBIngressController.yaml
- operator/v1/zz_generated.swagger_doc_generated.go
This was poorly named and this hasn't been used anywhere so we can make
the change while it's still time.
Also add CEL validation to make sure the field is only used for external
LB (and add tests).
> RFE-6242: ingress: rename loadBalancerIP to floatingIP

- operator/v1/types.go
Add a comment about validation for `GenerationStatus.LastGeneration` field (originally this PR added the validation itself, but we need to use a different approach and we'll do that later on).
/assign @deads2k @p0lyn0mial @JoelSpeed
> Last generation only increase

- tools/go.mod
- tools/go.sum
- tools/vendor/modules.txt
- tools/vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/patch_validation.go
Bumping controller tools to include a new option for required feature gates (AND between gates) as well as a fix to apply openshift gated xvalidations to fields, as well as structs.
> Update controller-tools to latest

- config/v1/tests/clusterversions.config.openshift.io/AAA_ungated.yaml
- config/v1/tests/clusterversions.config.openshift.io/SignatureStores.yaml
- config/v1/types_cluster_version.go
- config/v1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversions-CustomNoUpgrade.crd.yaml
- config/v1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversions-Default.crd.yaml
- config/v1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversions-DevPreviewNoUpgrade.crd.yaml
- config/v1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversions-TechPreviewNoUpgrade.crd.yaml
- config/v1/zz_generated.featuregated-crd-manifests/clusterversions.config.openshift.io/AAA_ungated.yaml
- config/v1/zz_generated.featuregated-crd-manifests/clusterversions.config.openshift.io/SignatureStores.yaml
Preconditions: 
Changes:
* Adds the 'OperatorLifecycleManagerV1' cluster capability
Next PR: [openshift/cluster-olm-operator#74](https://github.com/openshift/cluster-olm-operator/pull/74)
> OPRUN-3588: Add OperatorLifecycleManagerV1 cluster version capability

- operator/v1/register.go
When we added the new v1 type, we forgot to register it in the scheme.
> OPRUN-3402: operator/v1: add OLM to scheme

- config/v1/tests/clusterversions.config.openshift.io/ImageStreamImportMode.yaml
- config/v1/types_cluster_version.go
- config/v1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversions-DevPreviewNoUpgrade.crd.yaml
- config/v1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversions-TechPreviewNoUpgrade.crd.yaml
- config/v1/zz_generated.featuregated-crd-manifests.yaml
- config/v1/zz_generated.featuregated-crd-manifests/clusterversions.config.openshift.io/ImageStreamImportMode.yaml
- config/v1/zz_generated.swagger_doc_generated.go
- openapi/generated_openapi/zz_generated.openapi.go
- openapi/openapi.json
As [requested in the enhancement][1].  [Motivation for the new property from the enhancement][2]:
> There were a few options discussed in lieu of introducing a new ClusterVersion status field and the potential risks for doing so. The alternatives are highlighted with reasoning given for why they were not pursued:
> * Default ImportMode to PreserveOriginal everywhere: single-arch-release users maybe concerned about import size and the lack of metadata like `dockerImageLayers` and `dockerImageMetadata` for manifestlisted imagestream tags.
> * Clusters with homogeneous nodes running the multi payload who do not want to import manifestlists: The clusters can either migrate to single arch payloads or manually toggle the importMode through the image config CRD.
> * CVO provides architecural …
> MULTIARCH-4559: config/v1/types_cluster_version.go: Add 'architecture' to the release structure

- tools/codegen/pkg/schemacheck/generator.go
We used to prefix the errors coming out of the schemachecker with the comparator name, for example `NoMaps`, or `NoNewRequiredFields`. In my recent refactor, I lost this information and I want it back 😅
> Re-add schemachecker comparator name to outputs

- machine/v1beta1/types_vsphereprovider.go
- machine/v1beta1/zz_generated.swagger_doc_generated.go
- openapi/generated_openapi/zz_generated.openapi.go
- openapi/openapi.json
For the machine api operator to support
vm-host based zonal a single new field of
`vmGroup` needs to be added that will indicate
the vCenter cluster group to add a newly created
virtual machine into.
- https://github.com/openshift/enhancements/pull/1677
- https://github.com/openshift/installer/pull/8873
- https://github.com/openshift/client-go/pull/294
- https://github.com/openshift/library-go/pull/1782
- https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/325
- https://github.com/openshift/machine-api-operator/pull/1285
- https://github.com/openshift/api/pull/1999
> SPLAT-1743: Add VMGroup to VSphere Provider workspace

- example/v1/tests/stableconfigtypes.example.openshift.io/Example.yaml
- example/v1/types_stable.go
- example/v1/zz_generated.crd-manifests/0000_50_my-operator_01_stableconfigtypes-CustomNoUpgrade.crd.yaml
- example/v1/zz_generated.crd-manifests/0000_50_my-operator_01_stableconfigtypes-Default.crd.yaml
- example/v1/zz_generated.crd-manifests/0000_50_my-operator_01_stableconfigtypes-DevPreviewNoUpgrade.crd.yaml
- example/v1/zz_generated.crd-manifests/0000_50_my-operator_01_stableconfigtypes-TechPreviewNoUpgrade.crd.yaml
- example/v1/zz_generated.featuregated-crd-manifests/stableconfigtypes.example.openshift.io/AAA_ungated.yaml
- example/v1/zz_generated.featuregated-crd-manifests/stableconfigtypes.example.openshift.io/Example.yaml
- example/v1/zz_generated.swagger_doc_generated.go
- openapi/generated_openapi/zz_generated.openapi.go
- openapi/openapi.json
- tests/Makefile
This adds an example of the new format library for validating DNS 1123 subdomains to the example API. Will be leveraging this few a through APIs so providing an example hopefully helps some folks.
> Add example format validation

- features.md
- features/features.go
- payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
- payload-manifests/featuregates/featureGate-Hypershift-DevPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-DevPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
`ResilientWatchCacheInitialization` should be disabled for all API servers. At the moment [we carry a patch ](https://github.com/openshift/kubernetes/blob/master/pkg/features/kube_features.go#L1287-L1288)for kas (which will be replaced by this PR)
The FG will be disabled temporarily until cause of storage error triggering cache reinitialization during bootstrap is fixed in https://issues.redhat.com/browse/OCPBUGS-45126.
There's a separate pre-existing issue causing storage layer errors and watch cache re-initialization during cluster bootstrap. 
With ResilientWatchCacheInitialization enabled, clients (reflectors in particular) are turned away with 429 responses while the watch cache is being repopulated and retry repeatedly. Without this feature, requests hang (consuming priority and …
> OCPBUGS-44693: Disable ResilientWatchCacheInitialization

- features.md
- features/features.go
- payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
- payload-manifests/featuregates/featureGate-Hypershift-DevPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-DevPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
This reverts commit 52ecd418ae879ad0872a7a0d98cdc6f827afe73f.
After syncing with @deads2k , the expectation is not to disable the FG but to fix the underlying issue.
> Revert "OCPBUGS-44693: Disable ResilientWatchCacheInitialization"

- tools/.custom-gcl.yml
- tools/go.mod
- tools/go.sum
- tools/vendor/github.com/JoelSpeed/kal/pkg/analysis/commentstart/analyzer.go
- tools/vendor/github.com/JoelSpeed/kal/pkg/analysis/conditions/analyzer.go
- tools/vendor/github.com/JoelSpeed/kal/pkg/analysis/helpers/extractjsontags/analyzer.go
- tools/vendor/github.com/JoelSpeed/kal/pkg/analysis/helpers/extractjsontags/doc.go
- tools/vendor/github.com/JoelSpeed/kal/pkg/analysis/helpers/markers/analyzer.go
- tools/vendor/github.com/JoelSpeed/kal/pkg/analysis/helpers/markers/doc.go
- tools/vendor/github.com/JoelSpeed/kal/pkg/analysis/integers/analyzer.go
- tools/vendor/github.com/JoelSpeed/kal/pkg/analysis/jsontags/analyzer.go
- tools/vendor/github.com/JoelSpeed/kal/pkg/analysis/nobools/analyzer.go
- tools/vendor/github.com/JoelSpeed/kal/pkg/analysis/nophase/analyzer.go
- tools/vendor/github.com/JoelSpeed/kal/pkg/analysis/optionalorrequired/analyzer.go
- tools/vendor/github.com/JoelSpeed/kal/pkg/analysis/requiredfields/analyzer.go
- tools/vendor/github.com/JoelSpeed/kal/pkg/analysis/utils/type_check.go
- tools/vendor/modules.txt
This includes fixes for the linter not picking up the json tags on embedded fields like objectmeta and typemeta, leading to no reports of missing comments or the optional/required tag on the metadata field
> Update KAL with bug fixes for embedded fields

- hack/update-protobuf.sh
Some folks have been having issues recently because the protobuf generator is very, very fussy about where it is located.
You must have `$GOPATH` set, and you must check out the API repo at `$GOPATH/src/github.com/openshift/api`. If you do not, it will just write the resources there anyway, and remove any proto files from your actual checkout location. Resulting in confusion as "it deleted all the proto files".
This PR adds a check in the script, until we can work out a way to get around this weird proto generation issue (perhaps moving to gengo v2 will fix this for us)
> Add path warning for protobuf updates

- Makefile
This adds a new make target, which I'll add to the lint status check, that runs the lint-fixes (output to null for now as it's noisy) and then checks for a diff. Similar to other verify checks.
This means we can enforce that all fixes are applied prior to passing the lint check.
Eg this means we will always convert `kubeuilder:validation:Required` to `required` automatically.
> Add verify-lint-fix make target

- README.md
We recently changed the shape of a couple of v1alpha1 APIs in breaking ways (when moving to a new API version).
We could only do this because we started the API as a v1alpha1. Had we started directly at v1, and then made these changes, generated clients prior to the change, trying to deserialize the new schema would have issues.
This is added as a reminder of why we have v1alpha1, to allow us to make big changes!
> Add section about why we start APIs as v1alpha1

- machine/v1alpha1/types_openstack.go
- machine/v1alpha1/zz_generated.swagger_doc_generated.go
- openapi/generated_openapi/zz_generated.openapi.go
- openapi/openapi.json
This has no real impact on end-users but it is useful flag for reviewers as we start translating from MAPO<->CAPO. Some of these issues - such as `SecurityGroupFilter.TenantID` being ignored rather than "coalesced" with the `ProjectID` field - are likely bugs, but we're not going to fix these at this stage of MAPO's lifecycle.
This was generated via manual inspection of MAPO, most significantly the https://github.com/openshift/machine-api-provider-openstack/blob/release-4.18/pkg/machine/convert.go file.
> OSASINFRA-3689: Deprecate unused MAPO fields

- machine/v1beta1/types_vsphereprovider.go
- machine/v1beta1/zz_generated.swagger_doc_generated.go
- openapi/generated_openapi/zz_generated.openapi.go
- openapi/openapi.json
[SPLAT-2008](https://issues.redhat.com//browse/SPLAT-2008)
- Updated api documentation regarding vSphere max disk size for data disks
> SPLAT-2008: Update vSphere multi disk api size limit doc

- .golangci.yaml
- tools/.custom-gcl.yml
- tools/go.mod
- tools/go.sum
- tools/vendor/github.com/JoelSpeed/kal/README.md
- tools/vendor/github.com/JoelSpeed/kal/pkg/analysis/helpers/markers/analyzer.go
- tools/vendor/github.com/JoelSpeed/kal/pkg/analysis/maxlength/analyzer.go
- tools/vendor/github.com/JoelSpeed/kal/pkg/analysis/maxlength/doc.go
- tools/vendor/github.com/JoelSpeed/kal/pkg/analysis/maxlength/initializer.go
- tools/vendor/github.com/JoelSpeed/kal/pkg/analysis/registry.go
- tools/vendor/github.com/JoelSpeed/kal/pkg/analysis/statussubresource/analyzer.go
- tools/vendor/github.com/JoelSpeed/kal/pkg/analysis/statussubresource/doc.go
- tools/vendor/github.com/JoelSpeed/kal/pkg/analysis/statussubresource/initializer.go
- tools/vendor/modules.txt
This updates KAL to include two new linter rules.
This linter will check for objects marked as a CRD root, and, if they have a `status` field, will make sure that they have the appropriate subresource status marker.
It will also report when we have objects that have the marker, but do not have a status field, which is true of several of our APIs (I assume we should drop those).
This linter will check for untyped strings and arrays and ensure that a maximum length/items is configured appropriately.
Setting maximum lengths on fields is good practice to prevent folks from abusing an API (persisting large data in the database, potential DDOS), but also means that as we add CEL validations over time, their computational complexity is bound and their runtime cost is managed, by having sensible …
> Update KAL to introduce statussubresource and maxlength linters

- example/v1/tests/stableconfigtypes.example.openshift.io/Example+Example2.yaml
- example/v1/types_stable.go
- example/v1/zz_generated.crd-manifests/0000_50_my-operator_01_stableconfigtypes-DevPreviewNoUpgrade.crd.yaml
- example/v1/zz_generated.featuregated-crd-manifests.yaml
- example/v1/zz_generated.featuregated-crd-manifests/stableconfigtypes.example.openshift.io/Example+Example2.yaml
- features.md
- features/features.go
- features/legacyfeaturegates.go
- payload-command/render/legacyfeaturegates.go
- payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
- payload-manifests/featuregates/featureGate-Hypershift-DevPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-DevPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
- tools/codegen/pkg/emptypartialschemas/content_creator.go
- tools/codegen/pkg/emptypartialschemas/tags.go
- tools/codegen/pkg/manifestmerge/filters.go
- tools/go.mod
- tools/go.sum
- tools/vendor/modules.txt
- tools/vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/patch_validation.go
We have a couple of examples (for example https://github.com/openshift/api/pull/2131) of validations that end up relying on multiple feature gates. Thus far, this has caused an issue where one gate is promoted, but the other is not, since the validation cannot be automatically handled if the gated validation is promoted prior to the ungated dependent gate.
This PR updates the example API with a second Example2 feature gate, and then adds a validation that is only enabled when both the Example and Example2 feature gates are enabled (as can be seen by the fact that the validation is enabled in Custom and Dev CRDs, but not TPNU where Example2 is disabled.
I need to merge https://github.com/openshift/kubernetes-sigs-controller-tools/pull/25 and update the vendor here before we can merge this …
> Fix handling of validations that require multiple feature gates

- hack/update-payload-crds.sh
- payload-manifests/crds/0000_80_machine-config_01_machineosbuilds-CustomNoUpgrade.crd.yaml
- payload-manifests/crds/0000_80_machine-config_01_machineosbuilds-DevPreviewNoUpgrade.crd.yaml
- payload-manifests/crds/0000_80_machine-config_01_machineosbuilds-TechPreviewNoUpgrade.crd.yaml
- payload-manifests/crds/0000_80_machine-config_01_machineosconfigs-CustomNoUpgrade.crd.yaml
- payload-manifests/crds/0000_80_machine-config_01_machineosconfigs-DevPreviewNoUpgrade.crd.yaml
- payload-manifests/crds/0000_80_machine-config_01_machineosconfigs-TechPreviewNoUpgrade.crd.yaml
This PR updates the payload `MachineOSConfig`/`MachineOSBuild` CRDs to v1 from v1alpha1. This should be tested along with https://github.com/openshift/machine-config-operator/pull/4756 and will have to be merged alongside the same.
> Change OCL CRD deployment to v1 from v1alpha1

- Makefile
This adds a separate make target to run the feature promotion checks. This is intended to be used to add a separate check for feature promotion checks aside from the main verify run
> Add separate Make target for feature promotion

- Makefile
This drops the feature gate promotion from the main verify check, as it has now been added as a separate check on its own
/hold Must merge after https://github.com/openshift/api/pull/2173 and https://github.com/openshift/release/pull/61007
> Drop feature promotion from main verify check

- tests/generator.go
This should fix a race between the CRD being updated, and being active and served, vs the attempt to create a resource.
Seeking a flake occasionally because the initial object isn't created, because it fails the validation that the previous patch to the CRD schema was removing, as part of our ratcheting tests.
Also moves the CRD schema cleanup earlier to avoid exiting before we do the cleanup
> Fix race in tests using CRD patches for ratcheting

- machine/v1alpha1/types_openstack.go
- machine/v1alpha1/zz_generated.swagger_doc_generated.go
- openapi/generated_openapi/zz_generated.openapi.go
- openapi/openapi.json
Cinder uses GiB, not GB. This was a source of confusion during the MAPO<->CAPO work.
More discussion here: https://github.com/openshift/cluster-capi-operator/pull/188#discussion_r1927180443
> OSASINFRA-3690: Fix typo

- operator/v1alpha1/register.go
operator/v1alpha1: Add the `ClusterVersionOperator` to scheme
I forgot to register the new type in the scheme when adding the `ClusterVersionOperator` API in https://github.com/openshift/api/pull/2044.
This pull request references https://issues.redhat.com/browse/OTA-209
> OTA-209: operator/v1alpha1: Add the `ClusterVersionOperator` to scheme

- envtest-releases.yaml
- tools/Makefile
They are required for testing purposes on the repositories where we bump k8s dependencies to 1.32.
CC @JoelSpeed @deads2k @bertinatto
> NO-JIRA: Add envtest archives for K8s 1.32.1

- features/features.go
Component name for arbiter changed in jira, updating reference.
> NO-JIRA: upkeep: update component name for arbiter feature

- config/v1/tests/infrastructures.config.openshift.io/AAA_ungated.yaml
- machine/v1/tests/controlplanemachinesets.machine.openshift.io/stable.controlplanemachineset.openstack.testsuite.yaml
- operator/v1/tests/ingresscontrollers.operator.openshift.io/IngressControllerLBSubnetsAWS.yaml
- operator/v1/tests/ingresscontrollers.operator.openshift.io/SetEIPForNLBIngressController.yaml
- samples/v1/tests/configs.samples.operator.openshift.io/AAA_ungated.yaml
- tests/Makefile
- tests/generator.go
If we had the ability to add these tests when the PR for these changes was merged, we would have caught this earlier.
This adds tests for both spec and status to show that the ratcheting validation we added for 4.18 is working.
Currently blocked on waiting for https://github.com/openshift/kubernetes/pull/2167 to merge, and then publishing a new set of kubebuilder binaries from that.
> OCPBUGS-48078: Add ratcheting tests for PowerVS service endpoints

- tools/codegen/cmd/featuregate-test-analyzer.go
When the version is not main branch, and its a released version example, release-4.18 etc we need verify job to pick the correct release and not the latest release
> OCPBUGS-49779: Use BASE_REF env var to pull the release version for sippy data

- machine/v1beta1/types_awsprovider.go
- machine/v1beta1/zz_generated.swagger_doc_generated.go
- openapi/generated_openapi/zz_generated.openapi.go
- openapi/openapi.json
This PR adds support market type in AwsMachineProviderConfig. A new field, `MarketType`, is added. This ID is used specify the instance type i.e CapacityBlock, Spot, OnDemand.
> Add the field "MarketType" to "AwsMachineProviderConfig"

- features.md
- features/features.go
- payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
Enhancement: [Gateway API with Cluster Ingress Operator](https://github.com/openshift/enhancements/blob/master/enhancements/ingress/gateway-api-with-cluster-ingress-operator.md)
> NE-1871: Promote GatewayAPI to Tech Preview

- features/features.go
It was missing "APIV1", was named FeatureGateNewOLMCatalogdMetas before.
Signed-off-by: Anik Bhattacharjee <anbhatta@redhat.com>
> Fix FeatureGateNewOLMCatalogdAPIV1Metas spelling error

- security/v1/consts.go
Add annotation for validated SCC type (User / ServiceAccount).
An SCC is being assigned to a workload based on the capabilities the ServiceAccount or user has. To distinct, against whom this was validated against, this annotation is being introduced.
This is necessary to identify namespaces that might not be labeled properly by the PSA label syncer as it doesn't watch the user's SCCs and picks the wrong PodSecurityStandard for PodSecurityAdmission labels.
- [Pod Security Admission Enforcement Config](https://github.com/openshift/enhancements/pull/1747)
> security: add annotation for validated SCC type

- features.md
- features/features.go
- payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
- payload-manifests/featuregates/featureGate-Hypershift-DevPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-DevPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
They're Kubernetes feature gates, both alpha in Kubernetes 1.32, adding to DevPreviewNoUpgrade,
See https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/1710-selinux-relabeling
Depending on testing results, SELinuxChangePolicy might reach TechPreviewNoUpgrade before 4.19 freeze, a separate PR will follow.
> STOR-2267: Add SELinuxMount and SELinuxChangePolicy to DevPreview

- features.md
- features/features.go
- payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
- payload-manifests/featuregates/featureGate-Hypershift-DevPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-DevPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
Enhancement proposal: https://github.com/openshift/enhancements/pull/1670
> API-1689: features: add ShortCertRotation

- tools/codegen/pkg/schemacheck/generator.go
All partial manifests end up being generated to at least one (CustomNoUpgrade) of the merged manifests. This means that they often just duplicate errors that are otherwise represented in the merged manifests.
Also, whenever we add a new feature gated field, it forks the entire resource. Because this is a new file according to the schema checker, it determines that all of the pre-existing, non-fixable issues are new and reports them, leading to false positives.
This PR stops the schema check from inspecting the partial manifests to prevent the noise and false positives.
> Ignore partial manifests when running schemacheck

- config/v1/tests/nodes.config.openshift.io/AAA_ungated.yaml
- config/v1/types_node.go
- config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_nodes-CustomNoUpgrade.crd.yaml
- config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_nodes-Default.crd.yaml
- config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_nodes-DevPreviewNoUpgrade.crd.yaml
- config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_nodes-TechPreviewNoUpgrade.crd.yaml
- config/v1/zz_generated.featuregated-crd-manifests/nodes.config.openshift.io/AAA_ungated.yaml
- config/v1/zz_generated.featuregated-crd-manifests/nodes.config.openshift.io/MinimumKubeletVersion.yaml
- payload-manifests/crds/0000_10_config-operator_01_nodes-CustomNoUpgrade.crd.yaml
- payload-manifests/crds/0000_10_config-operator_01_nodes-Default.crd.yaml
- payload-manifests/crds/0000_10_config-operator_01_nodes-DevPreviewNoUpgrade.crd.yaml
- payload-manifests/crds/0000_10_config-operator_01_nodes-TechPreviewNoUpgrade.crd.yaml
- Removing support to configure cgroupsv1 in the OCP clusters.
- Removed the enum validation of "v1" for the `cgroupMode` field of the `nodes.config.openshift.io` object.
- Also added integration tests to validate the enum removal on the `cgroupMode` field
Enhancement Proposal Ref: https://github.com/openshift/enhancements/blob/master/enhancements/machine-config/mco-cgroupsv2-support.md
Summary:
- This PR allows to block the user from setting `cgroupMode v1`
- A change would be added for 4.18 in MCO to set machine-config cluster operator's `Upgradeable=False` when the `cgroupMode` is found to be `v1` and request users to update to `v2`
- All the clusters upgrading to 4.19 have to update to the minimum version of 4.18.z containing the above changes. This can be achieved through the …
> OCPNODE-2877: Remove support to configure cgroupsv1 in OCP

- tools/go.mod
- tools/go.sum
- tools/vendor/modules.txt
- tools/vendor/sigs.k8s.io/controller-tools/pkg/crd/patch_schema.go
This is part of a series of backports to 4.18 related to the changes in https://github.com/openshift/api/pull/2234 which needs to be backported to 4.18.
This PR specifically is a manual bump of the openshift/controller-tools dependency to pull in https://github.com/openshift/kubernetes-sigs-controller-tools/pull/29
> OCPBUGS-54784: [release-4.18] Bump openshift/controller-tools to latest commit

- tools/codegen/cmd/featuregate-test-analyzer.go
The 4.20 release has been enabled in sippy, which is now being picked up as the latest release branch and is therefore returning incorrect data for 4.19 promotions.
I've requested (https://issues.redhat.com/browse/TRT-2080) a way to determine programatically what the development branch is, but until then, if we can carry this commit until branching (and then revert), we will have accurate feature gate analysis without putting too much pressure on TRT to fix this today.
This is a temporary fix and should be reverted once branching completes on Friday 18th.
> Temporarily pin feature-gate-analyzer to 4.19

- config/v1/tests/infrastructures.config.openshift.io/HighlyAvailableArbiter+DualReplica.yaml
- config/v1/types_infrastructure.go
- config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_infrastructures-TechPreviewNoUpgrade.crd.yaml
- config/v1/zz_generated.featuregated-crd-manifests.yaml
- config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/DualReplica.yaml
- config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/HighlyAvailableArbiter+DualReplica.yaml
- features.md
- features/features.go
- machineconfiguration/v1/tests/controllerconfigs.machineconfiguration.openshift.io/HighlyAvailableArbiter+DualReplica.yaml
- machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_controllerconfigs-TechPreviewNoUpgrade.crd.yaml
- machineconfiguration/v1/zz_generated.featuregated-crd-manifests.yaml
- machineconfiguration/v1/zz_generated.featuregated-crd-manifests/controllerconfigs.machineconfiguration.openshift.io/HighlyAvailableArbiter+DualReplica.yaml
- machineconfiguration/v1/zz_generated.featuregated-crd-manifests/controllerconfigs.machineconfiguration.openshift.io/HighlyAvailableArbiter.yaml
- payload-manifests/crds/0000_10_config-operator_01_infrastructures-TechPreviewNoUpgrade.crd.yaml
- payload-manifests/crds/0000_80_machine-config_01_controllerconfigs-TechPreviewNoUpgrade.crd.yaml
- payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
- tools/codegen/pkg/manifestmerge/generator.go
CC @eggfoobar 
This updates the way we apply manifests to make sure that where we have combinations (A+B), that these are applied after the constituent gates.
This means that we can control the order, and, where there are multiple gates affecting a single validation (enum), we can choose how to apply for either of the gates being enabled, or both gates being enabled.
This also drops the DualReplica gate to DevPreview, which is why we needed to find a solution for this
> OCPEDGE-1775: Enable separation of conflicting enum values, and drop DualReplica to DevPreview

- features.md
- features/features.go
- machine/v1/tests/controlplanemachinesets.machine.openshift.io/CPMSMachineNamePrefix.yaml
- machine/v1/zz_generated.crd-manifests/0000_10_control-plane-machine-set_01_controlplanemachinesets-DevPreviewNoUpgrade.crd.yaml
- machine/v1/zz_generated.crd-manifests/0000_10_control-plane-machine-set_01_controlplanemachinesets-TechPreviewNoUpgrade.crd.yaml
- machine/v1beta1/zz_generated.crd-manifests/0000_10_machine-api_01_machines-DevPreviewNoUpgrade.crd.yaml
- machine/v1beta1/zz_generated.crd-manifests/0000_10_machine-api_01_machines-TechPreviewNoUpgrade.crd.yaml
- machine/v1beta1/zz_generated.crd-manifests/0000_10_machine-api_01_machinesets-DevPreviewNoUpgrade.crd.yaml
- machine/v1beta1/zz_generated.crd-manifests/0000_10_machine-api_01_machinesets-TechPreviewNoUpgrade.crd.yaml
- payload-manifests/crds/0000_10_control-plane-machine-set_01_controlplanemachinesets-DevPreviewNoUpgrade.crd.yaml
- payload-manifests/crds/0000_10_control-plane-machine-set_01_controlplanemachinesets-TechPreviewNoUpgrade.crd.yaml
- payload-manifests/featuregates/featureGate-Hypershift-DevPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-DevPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
Enabling the MAPI to CAPI conversion in TechPreview for 4.19.
Required before merging:
> OCPCLOUD-2914: Add MAPI to CAPI migration to TechPreview

- machine/v1/tests/controlplanemachinesets.machine.openshift.io/CPMSMachineNamePrefix.yaml
Colliding promotions for CPMSMachineNamePrefix to default and MachineAPIMigration to tech preview broke this test suite on the default feature set. For now, disable the suite in the default feature set by requiring the MachineAPIMigration gate.
> Fix broken ControlPlaneMachineSet integration tests

- features.md
- features/features.go
- payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
- payload-manifests/featuregates/featureGate-Hypershift-DevPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-DevPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
Adds the 'NewOLMOwnSingleNamespace' cluster capability.
Clones #2258
> OPRUN-3766: Add FeatureFlag for OLMv1 Single/OwnNamespace

- README.md
Extended the feature gate test requirements section with:
- Definition of the time window for evaluating test results (7 or 14 days depending on run count).
- Clarification that test flakes count as failures and affect pass rates.
> README: Add criteria for featuregate test result windows and flake handling

- config/v1/types_authentication.go
- config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_authentications-Hypershift-CustomNoUpgrade.crd.yaml
- config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_authentications-Hypershift-Default.crd.yaml
- config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_authentications-Hypershift-DevPreviewNoUpgrade.crd.yaml
- config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_authentications-Hypershift-TechPreviewNoUpgrade.crd.yaml
- config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_authentications-SelfManagedHA-CustomNoUpgrade.crd.yaml
- config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_authentications-SelfManagedHA-DevPreviewNoUpgrade.crd.yaml
- config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_authentications-SelfManagedHA-TechPreviewNoUpgrade.crd.yaml
- config/v1/zz_generated.featuregated-crd-manifests/authentications.config.openshift.io/ExternalOIDC.yaml
- config/v1/zz_generated.featuregated-crd-manifests/authentications.config.openshift.io/ExternalOIDCWithUIDAndExtraClaimMappings.yaml
- config/v1/zz_generated.swagger_doc_generated.go
- openapi/generated_openapi/zz_generated.openapi.go
- openapi/openapi.json
- payload-manifests/crds/0000_10_config-operator_01_authentications-Hypershift-CustomNoUpgrade.crd.yaml
- payload-manifests/crds/0000_10_config-operator_01_authentications-Hypershift-Default.crd.yaml
- payload-manifests/crds/0000_10_config-operator_01_authentications-Hypershift-DevPreviewNoUpgrade.crd.yaml
- payload-manifests/crds/0000_10_config-operator_01_authentications-Hypershift-TechPreviewNoUpgrade.crd.yaml
- payload-manifests/crds/0000_10_config-operator_01_authentications-SelfManagedHA-CustomNoUpgrade.crd.yaml
- payload-manifests/crds/0000_10_config-operator_01_authentications-SelfManagedHA-DevPreviewNoUpgrade.crd.yaml
- payload-manifests/crds/0000_10_config-operator_01_authentications-SelfManagedHA-TechPreviewNoUpgrade.crd.yaml
I had noticed that the GoDoc for the OIDC-related fields was a bit sparse and needed to be brought up to date with the OpenShift API conventions.
This PR attempts to improve the GoDoc for only the OIDC-related fields as part of the GA criteria for the BYO OIDC feature.
> CNTRLPLANE-367: Update Authentication API GoDoc for OIDC-related fields

- machineconfiguration/v1/types_machineosbuild.go
- machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineosbuilds.crd.yaml
- machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineosconfigs.crd.yaml
- machineconfiguration/v1/zz_generated.featuregated-crd-manifests/machineosbuilds.machineconfiguration.openshift.io/OnClusterBuild.yaml
- machineconfiguration/v1/zz_generated.featuregated-crd-manifests/machineosconfigs.machineconfiguration.openshift.io/OnClusterBuild.yaml
- machineconfiguration/v1/zz_generated.swagger_doc_generated.go
- payload-manifests/crds/0000_80_machine-config_01_machineosbuilds.crd.yaml
- payload-manifests/crds/0000_80_machine-config_01_machineosconfigs.crd.yaml
Fix the validation for the Resource field in the MOSB API to be of dns1035Label.
Fixes https://issues.redhat.com/browse/OCPBUGS-56382
> OCPBUGS-56382: Fix validation for Resource field in MOSB API

- config/v1/tests/infrastructures.config.openshift.io/GCPCustomAPIEndpoints.yaml
- config/v1/types_infrastructure.go
- config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_infrastructures-CustomNoUpgrade.crd.yaml
- config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_infrastructures-DevPreviewNoUpgrade.crd.yaml
- config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_infrastructures-TechPreviewNoUpgrade.crd.yaml
- config/v1/zz_generated.featuregated-crd-manifests/infrastructures.config.openshift.io/GCPCustomAPIEndpoints.yaml
- machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_controllerconfigs-CustomNoUpgrade.crd.yaml
- machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_controllerconfigs-DevPreviewNoUpgrade.crd.yaml
- machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_controllerconfigs-TechPreviewNoUpgrade.crd.yaml
- machineconfiguration/v1/zz_generated.featuregated-crd-manifests/controllerconfigs.machineconfiguration.openshift.io/GCPCustomAPIEndpoints.yaml
- payload-manifests/crds/0000_10_config-operator_01_infrastructures-CustomNoUpgrade.crd.yaml
- payload-manifests/crds/0000_10_config-operator_01_infrastructures-DevPreviewNoUpgrade.crd.yaml
- payload-manifests/crds/0000_10_config-operator_01_infrastructures-TechPreviewNoUpgrade.crd.yaml
- payload-manifests/crds/0000_80_machine-config_01_controllerconfigs-CustomNoUpgrade.crd.yaml
- payload-manifests/crds/0000_80_machine-config_01_controllerconfigs-DevPreviewNoUpgrade.crd.yaml
- payload-manifests/crds/0000_80_machine-config_01_controllerconfigs-TechPreviewNoUpgrade.crd.yaml
** The tag manager or tagging does appear to have a service in GCP, but this particular one is NOT used. Instead openshift uses the cloud resource manager service, so there is no need to support Tag Manager. 
** The origin of the changes stemmed from https://issues.redhat.com/browse/CORS-2389. The [tech-preview] feature gate was added during the openshift-4.19 release. The TagManager value is removed during the openshift-4.20 release. The feature as a whole was not officially released during openshift-4.19, and the openshift installer is currently the only user for this feature, so the impact is very low.
> CORS-4041: Remove the TagManager from the GCP Custom Endpoints

- features.md
- features/features.go
- payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
- payload-manifests/featuregates/featureGate-Hypershift-DevPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-DevPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
This adds the MAP feature gate but doesn't enable it in any feature set yet.
To be enabled in a feature set we first need to tell KASO to enable the APIs in KAS, and the gate must be registered before we can do that.
This will eventually allow our customers and developers to start playing with the feature and determining where it can be used in place of webhooks for defaulting and other mutations.
> Register MutatingAdmissionPolicy in feature gates

- hack/update-payload-crds.sh
- payload-manifests/crds/0000_03_config-operator_01_rolebindingrestrictions.crd.yaml
Reverts openshift/api#2138
Opening to run payload tests while investigating [OCPBUGS-58231](https://issues.redhat.com//browse/OCPBUGS-58231)
Narrowing down timeline for regressions to [4.20.0-0.nightly-2025-06-27-202106](https://sippy.dptools.openshift.org/sippy-ng/release/4.20/tags/4.20.0-0.nightly-2025-06-27-202106) and the [diff](https://sippy.dptools.openshift.org/api/payloads/diff?fromPayload=4.20.0-0.nightly-2025-06-27-150956&toPayload=4.20.0-0.nightly-2025-06-27-202106) show this as one of the changes.
Verified via multiple aggregate runs of
```
/payload-aggregate periodic-ci-openshift-release-master-nightly-4.20-e2e-aws-ovn-fips 10
```
That the regression failure we have seen in payloads / ci / other suspected reverts is not present in these runs
```
: …
```
> Revert "CNTRLPLANE-72: remove RoleBindingRestriction CRD from payload"

- config/v1/register.go
Register v1 type of ClusterImagePolicy and ImagePolicy. Follow-up PR of https://github.com/openshift/api/pull/2310
> Register v1 (cluster)imagepolicy

- tools/Makefile
Add to Makefile the newest version used to publish kubebuilder tools.
> makefile: bump-publish-kubebuilder-tools to 1.33.2

- envtest-releases.yaml
- tools/publish-kubebuilder-tools/README.md
- tools/publish-kubebuilder-tools/main.go
- first commit rectifies issue with the previous https://github.com/openshift/api/pull/2407 PR by adding a `v` prefix version in the index
- second commit adds requirement about the `v` prefix in the documentation + a check in the tool to ensure it is specified.
Thanks @theobarberbany for the report.
> Fix kubebuilder tools/envtest index for v1.33.2 (add v prefix)

- features.md
- features/features.go
- hack/update-payload-crds.sh
- payload-manifests/crds/0000_10_config-operator_01_clusterimagepolicies-CustomNoUpgrade.crd.yaml
- payload-manifests/crds/0000_10_config-operator_01_clusterimagepolicies-DevPreviewNoUpgrade.crd.yaml
- payload-manifests/crds/0000_10_config-operator_01_clusterimagepolicies-TechPreviewNoUpgrade.crd.yaml
- payload-manifests/crds/0000_10_config-operator_01_imagepolicies-CustomNoUpgrade.crd.yaml
- payload-manifests/crds/0000_10_config-operator_01_imagepolicies-DevPreviewNoUpgrade.crd.yaml
- payload-manifests/crds/0000_10_config-operator_01_imagepolicies-TechPreviewNoUpgrade.crd.yaml
- payload-manifests/featuregates/featureGate-Hypershift-DevPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-DevPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
Added a commit to drop down the SigstoreImageVerification the gate from all sets
---
6b81288182527d8b26212eee6aca0b217e016076: Added commit to drop down the SigstoreImageVerification to DevPreview
- Test the cluster can launch with and without specifying techpreview
```
launch 4.20.0-0.nightly-2025-07-15-083124,https://github.com/openshift/api/pull/2384,https://github.com/openshift/machine-config-operator/pull/5143,https://github.com/openshift/cluster-update-keys/pull/74 aws,techpreview
```
- CRD, openshift policy is not available after TechPreviewNoUpgrade is enabled.
---
891ea2a0ab6149003a07a092ca3dce48ffd7bdb5: Test this PR with https://github.com/openshift/machine-config-operator/pull/5143, https://github.com/openshift/cluster-update-keys/pull/74:
- Test the cluster can launch with …
> OCPNODE-3006:Add clusterimgepolicy/imagepolicy to payload

- features.md
- features/features.go
- payload-manifests/featuregates/featureGate-Hypershift-DevPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-DevPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
revert commit https://github.com/openshift/api/commit/60ac3d5f7f206f979af805fadf3225375fec7802, add back SigstoreImageVerification to techpreview.
This PR should be merged after
- https://github.com/openshift/machine-config-operator/pull/5143
- https://github.com/openshift/api/pull/2384
- https://github.com/openshift/origin/pull/29973
> OCPNODE-3006: add back SigstoreImageVerification to techPreview

- features.md
- features/features.go
- payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
SELinuxMount is Beta + disabled by default upstream. Move it to TechPreviewNoUpgrade, so users can test it easily and get CI coverage.
I removed SELinuxChangePolicy from this PR, it's enabled by default + cannot be disabled. We already run e2e tests for it, see `[FeatureGate:SELinuxChangePolicy]` tests in a -serial job (e.g. [e2e-aws-ovn-serial](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-release-master-nightly-4.20-e2e-aws-ovn-serial/1950807617412534272)).
> STOR-2481: Promote SELinuxMount feature gate

- machineconfiguration/v1/tests/machineosconfigs.machineconfiguration.openshift.io/AAA_ungated.yaml
- machineconfiguration/v1/types_machineosconfig.go
- machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineosconfigs.crd.yaml
- machineconfiguration/v1/zz_generated.featuregated-crd-manifests/machineosconfigs.machineconfiguration.openshift.io/AAA_ungated.yaml
- payload-manifests/crds/0000_80_machine-config_01_machineosconfigs.crd.yaml
Add a restriction where the name of the MachineOSConfig object must be the same as the MachineConfigPool it is created for. This will ensure that we only have one MOSC per MCP.
Fixes https://issues.redhat.com/browse/OCPBUGS-54287
> OCPBUGS-54287: MachineOSConfig name should match MachineConfigPool

- tools/codegen/cmd/featuregate-test-analyzer.go
The sippy variant is `single`, not `single-node`, for example see https://sippy.dptools.openshift.org/sippy-ng/tests/4.20/analysis?test=%5Bsig-cli%5D%5BOCPFeatureGate%3AUpgradeStatus%5D%20oc%20amd%20upgrade%20status%20never%20fails&filters=%7B%22items%22%3A%5B%7B%22columnField%22%3A%22name%22%2C%22operatorValue%22%3A%22equals%22%2C%22value%22%3A%22%5Bsig-cli%5D%5BOCPFeatureGate%3AUpgradeStatus%5D%20oc%20amd%20upgrade%20status%20never%20fails%22%7D%2C%7B%22columnField%22%3A%22variants%22%2C%22operatorValue%22%3A%22contains%22%2C%22value%22%3A%22Topology%3Asingle%22%7D%5D%2C%22linkOperator%22%3A%22and%22%7D
CC @petr-muller
> Fix feature promotion check single node variant name

- OWNERS
to include everettraven and remove deads2k.
I've been shadowing @JoelSpeed as an API reviewer for ~8 months now and have actively been contributing to reviews and API-related tooling to improve the API review process.
As per a conversation with Joel, I'm adding myself as an approver and removing David Eads as a reviewer
> OWNERS: update approvers/reviewers

- features.md
- features/features.go
- operator/v1alpha1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversionoperators-TechPreviewNoUpgrade.crd.yaml
- payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
This missed 4.19 because of incomplete testing and docs, all of which is remediated now, so this is ready for TechPreview.
> OTA-923: Promote `ClusterVersionOperatorConfiguration` to TechPreview

- machineconfiguration/v1/tests/machineosconfigs.machineconfiguration.openshift.io/OnClusterBuild.yaml
- machineconfiguration/v1/types_machineosconfig.go
- machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineosconfigs.crd.yaml
- machineconfiguration/v1/zz_generated.featuregated-crd-manifests/machineosconfigs.machineconfiguration.openshift.io/OnClusterBuild.yaml
- payload-manifests/crds/0000_80_machine-config_01_machineosconfigs.crd.yaml
Add a restriction where the name of the MachineOSConfig object must be the same as the MachineConfigPool it is created for. This will ensure that we only have one MOSC per MCP.
> [release-4.19] OCPBUGS-60414: MachineOSConfig name should match MachineConfigPool

- console/v1/types_console_link.go
- console/v1/zz_generated.crd-manifests/00_consolelinks.crd.yaml
- console/v1/zz_generated.featuregated-crd-manifests.yaml
- console/v1/zz_generated.featuregated-crd-manifests/consolelinks.console.openshift.io/AAA_ungated.yaml
The ConsoleLink CRD has an `additionalPrinterColumns` entry for `Menu` that is not valid. The correct column name is `Location`.
- name: Menu
type: string
jsonPath: .spec.menu
should be changed to
- name: Location
type: string
jsonPath: .spec.location
> OCPBUGS-59939: ConsoleLink CRD has incorrect additionalPrinterColumns entry
