- apps/v1/types.go
- image/v1/types.go
- project/v1/types.go
- route/v1/types.go
These caused client gen problems
> update types for k8s.io/api

- apps/v1/generated.proto
- apps/v1/types.go
- image/v1/generated.proto
- image/v1/types.go
- security/v1/generated.proto
- security/v1/types.go
For those people who just couldn't resist getting in one more change.....
> Api changes

- pkg/testing/deepcopy_test.go
@sttts fyi, since you asked for it in https://github.com/openshift/api/pull/20#discussion_r157748678
> Add DeepCopy fail test

- hack/update-deps.sh
Same thing as in openshift/client-go#19
@deads2k ptal
> Check glide version

- image/v1/types.go
imagestreamtags support list.  Update the metadata to generate a list method.
> update istag to generate a list

- security/v1/generated.proto
- security/v1/types.go
Related to https://github.com/openshift/origin/issues/19767
> SCC: mark AllowFlexVolumes as optional field

- authorization/install.go
- image/v1/types.go
fixing https://github.com/openshift/client-go/pull/55 (lgtmed) and a package typo.  I plan to merge on green.
> minor fixes for generator and package name

- network/v1/constants.go
moves annotation constants to openshift/api.
> add network annotation constants

- install.go
Found two groups missing from the list.  In other news, omg, it works for oc.
> pick up missing groups to install found when using in oc

- OWNERS
> clean up owners

- openshiftcontrolplane/v1/types.go
> remove config proto tags

- operator/v1/types.go
- operator/v1/zz_generated.swagger_doc_generated.go
bad tide status on https://github.com/openshift/api/pull/138
> add coarse grained logging desires to operator API

- config/v1/types_cluster_operator.go
- config/v1/zz_generated.swagger_doc_generated.go
The version of the operator must be reported.
/assign @smarterclayton
> require operator version reported

- operator/v1/types_kubeapiserver.go
- operator/v1/zz_generated.swagger_doc_generated.go
@deads2k I noticed this discrepancy while putting together PR for operator/v1/types_authentication.
> fixup kubeapiserver swagger

- openshiftcontrolplane/v1/types.go
- openshiftcontrolplane/v1/zz_generated.swagger_doc_generated.go
oapi is gone forever, lets remove this cruft.
/assign @sttts
> remove option for enabling oapi

- config/v1/types_feature.go
We are moving this to enabled for 4.1
cc @deads2k
> Remove Local storage from disabled features

- config/v1/types_feature.go
We had a carry to enable this by default.
/assign @sjenning
> supportpodpidslimit in features

- authorization/v1/generated.proto
- authorization/v1/types.go
required for this: https://github.com/openshift/cluster-config-operator/pull/32
> add nullable fields for RoleBindingRestriction

- .travis.yml
- apps/v1/zz_generated.swagger_doc_generated.go
- build/v1/zz_generated.swagger_doc_generated.go
- config/v1/types_feature.go
- config/v1/types_scheduling.go
- config/v1/zz_generated.swagger_doc_generated.go
- image/v1/zz_generated.swagger_doc_generated.go
- legacyconfig/v1/zz_generated.swagger_doc_generated.go
- openshiftcontrolplane/v1/zz_generated.swagger_doc_generated.go
- operator/v1/types_authentication.go
- operator/v1/types_console.go
- operator/v1/types_etcd.go
- operator/v1/types_openshiftapiserver.go
- operator/v1/types_openshiftcontrollermanager.go
- operator/v1/types_serviceca.go
- operator/v1/types_servicecatalogapiserver.go
- operator/v1/zz_generated.swagger_doc_generated.go
- operator/v1alpha1/zz_generated.swagger_doc_generated.go
- security/v1/zz_generated.swagger_doc_generated.go
- webconsole/v1/zz_generated.swagger_doc_generated.go
/assign @deads2k 
Requires https://github.com/openshift/release/pull/3416
> Switch openshift/api to go1.11

- config/v1/types_feature.go
Recent changes to features in #290 and #282 broke e2e runs.  Looks like the e2e tests need updating first.  
Reverting so we can keep bumping api.
@ravisantoshgudimetla next time have a go with a fake bump
> get back to working feature list

- security/v1/generated.proto
- security/v1/types.go
Adding nullable tags for SCCs to convert SCCs to CRD
see: https://github.com/openshift/cluster-config-operator/pull/41
> Add nullable tags for SCCs, take 2

- authorization/v1/generated.proto
- authorization/v1/types.go
> Add nullable tags to RBR

- config/v1/types_image.go
- config/v1/zz_generated.swagger_doc_generated.go
Change "SSL certificate" to "TLS certificates"
> config: Fix Image InsecureRegistries Doc

- image/v1/consts.go
- image/v1/types.go
These are part of our API and used across multiple binaries.
/assign @adambkaplan
> add constants for image annotations

- project/v1/types.go
> Add project annotation used by scheduler, apiserver and oc

- build/v1/consts.go
> Add build annotations used by controller and oc

- OWNERS
US is out on holiday and EU needs approvers.
> Add EU based owners

- project/v1/types.go
> add project annotation API

- config/v1/types_console.go
- config/v1/zz_generated.swagger_doc_generated.go
/assign @benjaminapetersen @bparees
> Bug 1732145: Improve console config resource description

- config/v1/types_scheduling.go
- config/v1/zz_generated.swagger_doc_generated.go
This adds a more unique description to the scheduler config, bz https://bugzilla.redhat.com/show_bug.cgi?id=1732150
> Bug 1732150: Update Scheduler config description

- config/v1/types_network.go
- config/v1/zz_generated.swagger_doc_generated.go
This PR addresses the bug report [1729311](https://bugzilla.redhat.com/show_bug.cgi?id=1729311)
This PR concerns only the documentation of the network resource.  
Please have a look at the wording as I am not sure that's what should be mentioned (@squeed )
/assign @squeed
> Updating the explanation for Network type

- config/v1/types_image.go
- config/v1/zz_generated.swagger_doc_generated.go
Adding further information to the API Image configuration struct.
> Bug 1732148: Properly documenting purpose of Image config.

- config/v1/types_feature.go
Adds CustomNoUpgrade and LatencySensitive to the Features map.
/cc @sjenning @deads2k
> [4.3] add CustomNoUpgrade to FeatureSets and LatencySensitive featuresets

- operator/v1/types_network.go
- operator/v1/zz_generated.deepcopy.go
- operator/v1/zz_generated.swagger_doc_generated.go
Jira: SDN-494
https://jira.coreos.com/browse/SDN-494
Signed-off-by: Phil Cameron <pcameron@redhat.com>
> OVN - add geneve port assignment

- network/v1/generated.proto
- network/v1/types.go
- network/v1/zz_generated.swagger_doc_generated.go
> Fixed a typo 'addressed -> addresses'

- Makefile
- operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml
- operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml-merge-patch
- operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml
- operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml-merge-patch
- operator/v1/0000_25_kube-scheduler-operator_01_config.crd.yaml
- operator/v1/0000_25_kube-scheduler-operator_01_config.crd.yaml-merge-patch
- operator/v1/0000_30_openshift-apiserver-operator_01_config.crd.yaml
- operator/v1/0000_50_cluster-authentication-operator_01_config.crd.yaml
- operator/v1/0000_50_cluster-openshift-controller-manager-operator_02_config.crd.yaml
- operator/v1/0000_50_cluster-svcat-apiserver-operator_02_config.crd.yaml
- operator/v1/0000_50_cluster-svcat-controller-manager-operator_02_config.crd.yaml
- operator/v1/0000_50_service-ca-operator_02_crd.yaml
- operator/v1/0000_70_cluster-network-operator_01_crd.yaml
- operator/v1/0000_70_dns-operator_00-custom-resource-definition.yaml
> Add operator crds

- operator/v1/0000_30_openshift-apiserver-operator_01_config.crd.yaml
- operator/v1/types_openshiftapiserver.go
- operator/v1/zz_generated.swagger_doc_generated.go
Needed for the encryption controllers.
> operator/v1: add latestAvailableRevision to OpenShiftAPIServerStatus

- operator/v1/0000_50_ingress-operator_00-custom-resource-definition.yaml
I missed that bit was missing in https://github.com/openshift/api/pull/487
/assign @sttts 
/cc @ironcladlou 
@damemi we definitely need that script verifying those
> Add missing preserveUnknownField marker for pruning

- config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
- config/v1/types_cluster_version.go
First half of the move of CRDs to openshift/api for CVO.
> config/v1: add clusterversions CRD from CVO

- config/v1/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
- config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
- config/v1/types_cluster_operator.go
Follow-up of https://github.com/openshift/api/pull/495. ClusterOperator is also part of CVO.
> config/v1: move ClusterOperator CRD from CVO

- console/v1/0000_10_consolelink.crd.yaml
- console/v1/types_console_link.go
- console/v1/zz_generated.deepcopy.go
- console/v1/zz_generated.swagger_doc_generated.go
Story: https://jira.coreos.com/browse/CONSOLE-1828
cc'ing @spadgett 
/assign @bparees
> Add label selector to namespace-scoped links

- apps/v1/generated.proto
- apps/v1/types.go
- authorization/v1/generated.proto
- authorization/v1/types.go
- authorization/v1/zz_generated.swagger_doc_generated.go
- build/v1/generated.proto
- build/v1/types.go
- route/v1/generated.proto
- route/v1/types.go
- template/v1/generated.proto
- template/v1/types.go
/assign @deads2k @sttts 
One of the steps to land openshift/oc#149
I wonder how much we are still missing, our API's description is not consistent :disappointed:
> Bug 1773682: Add missing optional tags

- hack/verify-crds.sh
- imageregistry/v1/00-crd.yaml
> Bug 1769008: Add missing preserveUnknownFields tags 

- config/v1/types_feature.go
Cherry pick of https://github.com/openshift/api/pull/550 for getting it in 4.3
> Bug 1785419: Allow sctp protocol with LatencySensitive FG

- hack/update-protobuf.sh
- third_party/protobuf/google/protobuf/descriptor.proto
> Fix protobuf generation

- build/v1/generated.proto
- build/v1/types.go
- build/v1/zz_generated.swagger_doc_generated.go
- network/v1/001-clusternetwork-crd.yaml
- network/v1/002-hostsubnet-crd.yaml
- network/v1/003-netnamespace-crd.yaml
- network/v1/004-egressnetworkpolicy-crd.yaml
In Docker strategy builds, the `from` field will replace the last FROM directive in a multi-stage Dockerfile build.
> Bug 1784532: Clarify FROM behavior in builds

- console/v1/0000_10_consoleclidownload.crd.yaml
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1794804
@benjaminapetersen
> Bug 1794804: Remove Description from CLI output to improve its display

- LICENSE
> Fixes #545: Fix copyright in LICENSE file

- imageregistry/v1/00-crd.yaml
- imageregistry/v1/types.go
- imageregistry/v1/zz_generated.swagger_doc_generated.go
https://issues.redhat.com/browse/DEVEXP-566
> Add VirtualHostedStyle to S3 configuration options

- operator/v1/0000_50_ingress-operator_00-custom-resource-definition.yaml
- operator/v1/types_ingress.go
- operator/v1/zz_generated.swagger_doc_generated.go
In support of the [Wildcard Admission Policy](https://github.com/openshift/enhancements/pull/252) enhancement proposal.
/assign @ironcladlou @knobunc 
/cc @Miciah @frobware
> Adds wildcardPolicy field to IngressController API

- authorization/v1/generated.proto
- authorization/v1/types.go
- build/v1/generated.proto
- build/v1/types.go
This PR is cleaning our API to be able to turn on client-side validation in https://github.com/openshift/oc/pull/359
/assign @sttts
> Update optional tags where needed

- security/v1/0000_03_security-openshift_01_scc.crd.yaml
- security/v1/generated.proto
- security/v1/types.go
> Bug 1784151: set additionalPrinterColumns for SCC

- config/v1/0000_10_config-operator_01_build.crd.yaml
- config/v1/types_build.go
- config/v1/zz_generated.deepcopy.go
- config/v1/zz_generated.swagger_doc_generated.go
https://issues.redhat.com/browse/BUILD-96
> Add ForcePull to BuildOverrides

- config/v1/0000_10_config-operator_01_apiserver.crd.yaml
- config/v1/types_apiserver.go
- config/v1/zz_generated.swagger_doc_generated.go
Updates after a request to review text from #681.
> Minor wording adjustments

- console/v1/0000_10_consoleclidownload.crd.yaml
- console/v1/0000_10_consoleexternalloglink.crd.yaml
- console/v1/0000_10_consolelink.crd.yaml
- console/v1/0000_10_consolenotification.crd.yaml
- console/v1/0000_10_consoleyamlsample.crd.yaml
- helm/v1beta1/0000_10-helm-chart-repository.crd.yaml
- operatoringress/v1/0000_50_dns-record.yaml
This is matches https://github.com/openshift/enhancements/pull/414 and doesn't change existing behavior
> bug 1871890: add current profile annotations to CVO manifests

- console/v1/0000_10_consolenotification.crd.yaml
- console/v1/types_console_notification.go
- console/v1/zz_generated.swagger_doc_generated.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1877487
> Bug 1877487: add valid values for ConsoleNotification location

- samples/v1/types_config.go
> samples: add ARMArchitecture

- imageregistry/v1/00-crd.yaml
- imageregistry/v1/01-crd.yaml
- samples/v1/0000_10_samplesconfig.crd.yaml
This is matches openshift/enhancements#510 and doesn't change existing behavior
> add current profile annotations to CVO manifests

- OWNERS
> Add spadgett as api approver(pillar lead)

- operator/v1/0000_70_cluster-network-operator_01_crd.yaml
- operator/v1/types_network.go
- operator/v1/zz_generated.swagger_doc_generated.go
Add flag to enable network diagnostics
> Add disableNetworkDiagnostics flag to CNO CRD

- authorization/v1/0000_03_authorization-openshift_01_rolebindingrestriction.crd.yaml
- config/v1/0000_03_config-operator_01_proxy.crd.yaml
- config/v1/0000_10_config-operator_01_authentication.crd.yaml
- config/v1/0000_10_config-operator_01_featuregate.crd.yaml
- config/v1/0000_10_config-operator_01_oauth.crd.yaml
- config/v1/0000_10_config-operator_01_project.crd.yaml
- config/v1/0000_10_config-operator_01_scheduler.crd.yaml
- security/v1/0000_03_security-openshift_01_scc.crd.yaml
> Bump CRDs to apiextensions.k8s.io/v1

- network/v1/001-clusternetwork-crd.yaml
- network/v1/002-hostsubnet-crd.yaml
- network/v1/003-netnamespace-crd.yaml
- security/v1/0000_03_security-openshift_01_scc.crd.yaml
> Fix additionalPrinterColumns CRDs

- route/v1/types.go
With this new annotation, the enhanced validation can be made optional for customers who rely on the old behavior.
> Bug 1896977: Enhance host name validation - annotation

- operator/v1/0000_40_cloud-credential-operator_00_config.crd.yaml
- operator/v1/types_cloudcredential.go
- operator/v1/zz_generated.swagger_doc_generated.go
Following up with the request for docs from https://github.com/openshift/api/pull/714#discussion_r474511703
> add some docs for the generated CRDs for the cloudcredentials type

- operator/v1/0000_12_etcd-operator_01_config.crd.yaml
- operator/v1/types_etcd.go
- operator/v1/zz_generated.swagger_doc_generated.go
- https://github.com/openshift/openshift-docs/issues/25781
I think this is correct?
> Etcd provides information to configure an operator to manage etcd.
> Update etcd CRD description

- operator/v1/0000_50_cluster-authentication-operator_01_config.crd.yaml
- operator/v1/types_authentication.go
- operator/v1/zz_generated.swagger_doc_generated.go
> Bug 1901535: Remove the ManagingOAuthAPIServer field from authentication.operator API 

- config/v1/types_feature.go
- config/v1/types_features_test.go
reverts https://github.com/openshift/api/pull/825 to realign to kubernetes.
> re-align selflink to kube

- cloudnetwork/v1/generated.proto
- cloudnetwork/v1/register.go
- cloudnetwork/v1/types.go
Some minor changes to complement PR: #859 
/assign @sttts
> Fix minor issues with cloud-network-config-controller API

- config/v1/0000_10_config-operator_01_console.crd.yaml
- console/v1/0000_10_consoleclidownload.crd.yaml
- console/v1/0000_10_consoleexternalloglink.crd.yaml
- console/v1/0000_10_consolelink.crd.yaml
- console/v1/0000_10_consolenotification.crd.yaml
- console/v1/0000_10_consolequickstart.crd.yaml
- console/v1/0000_10_consoleyamlsample.crd.yaml
- console/v1alpha1/0000_10_consoleplugin.crd.yaml
> Bug 1947789: Switch console releated CRDs to v1

- config/v1/0000_10_config-operator_01_build.crd.yaml
- samples/v1/0000_10_samplesconfig.crd.yaml
move to v1 since v1beta1 will be removed in 4.9
> Bug 1947793: Deprecated API in use

- config/v1/0000_03_config-operator_01_operatorhub.crd.yaml
Update the operatorhub config API to CRD v1
> Bug 1947794: Update operatorhub config object to v1

- build/v1/generated.proto
- build/v1/types.go
- build/v1/zz_generated.swagger_doc_generated.go
/assign @adambkaplan 
/assign @rolfedh 
Here is my pass at addressing your respective godoc comments that came in too late before https://github.com/openshift/api/pull/882 merged
FYI some of the detail that was requested to be pruned did stem from trying to address questions from others earlier during the review ... please see earlier review iterations in https://github.com/openshift/api/pull/882 if you need to full context.
> Bug 1957261: BuildConfigStatus.ImageChangeTriggers godoc cleanup

- networkoperator/v1/001-egressrouter.crd.yaml
- networkoperator/v1/001-egressrouter.crd.yaml-patch
Signed-off-by: Mohamed Mahmoud <mmahmoud@redhat.com>
modify egress router CNI to allow using CIDR ips for addresses instead of IP
> Bug 1951158: modify ip to use IP CIDR format

- build/v1/generated.proto
- build/v1/types.go
- build/v1/zz_generated.swagger_doc_generated.go
/assign @adambkaplan 
/assign @rolfedh
> Bug 1956826: add restriction note for docker strategy build args

- build/v1/generated.proto
- build/v1/types.go
Updating build types:
- added listType to appropriate fields
- added +required tag for required fields
> BUILD-87: Add support for build volumes

- config/v1/types_feature.go
CC @openshift/storage 
Epics:
https://issues.redhat.com/browse/STOR-577
https://issues.redhat.com/browse/STOR-576
> Add feature gates for tech preview CSI drivers: GCE and Azure

- operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml
- operator/v1/types_kubecontrollermanager.go
- operator/v1/zz_generated.swagger_doc_generated.go
part 2 of the four step plan in https://github.com/openshift/service-ca-operator/pull/167
> add field to make service-ca.crt more secure

- operator/v1/0000_12_etcd-operator_01_config.crd.yaml
- operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml
- operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml
- operator/v1/0000_25_kube-scheduler-operator_01_config.crd.yaml
- operator/v1/types.go
- operator/v1/zz_generated.swagger_doc_generated.go
Additional nodeStatus fields for https://github.com/openshift/enhancements/pull/833.
> operator/v1: add ladfailedReason to NodeStatus

- config/v1/types_infrastructure_test.go
- go.mod
- vendor/modules.txt
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>
> Bug 1982868: unit-test: verify no default for infrastructure CRD status

- config/v1/0000_10_config-operator_01_ingress.crd.yaml
- config/v1/types.go
+required and MinLength=1 is not enough, need to use +kubebuilder:validation:Required
> Bug 1993002: domainPatterns is required

- operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
- operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
- operator/v1/types_csi_cluster_driver.go
Azure File CSI driver will be shipped in OC 4.10. 
> Include Azure File CSI Driver in clustercsidrivers

- oauth/v1/generated.proto
- oauth/v1/types.go
- oauth/v1/zz_generated.swagger_doc_generated.go
https://bugzilla.redhat.com/show_bug.cgi?id=1986504
> Bug 1986504: update docs on tokens

- operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
- operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
- operator/v1/types_csi_cluster_driver.go
Alibaba Disk CSI driver should be part of upcoming OCP release.
> Add Alibaba Disk CSI driver

- config/v1/types_feature.go
Epics:
https://issues.redhat.com/browse/STOR-578
https://issues.redhat.com/browse/STOR-614
> Add feature gates for CSI migration (TP): vSphere and Azure File

- build/v1/consts.go
- build/v1/generated.proto
- build/v1/types.go
- build/v1/zz_generated.swagger_doc_generated.go
- config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
- config/v1/types_cluster_version.go
- config/v1/zz_generated.swagger_doc_generated.go
- image/v1/generated.proto
- image/v1/types.go
- image/v1/zz_generated.swagger_doc_generated.go
- kubecontrolplane/v1/types.go
- kubecontrolplane/v1/zz_generated.swagger_doc_generated.go
- legacyconfig/v1/types.go
- legacyconfig/v1/zz_generated.swagger_doc_generated.go
Done via
```
sed -i 's/\b\([a-z]\+\) \1\b/\1/' \
$(git grep -l '\b\([a-z]\+\) \1\b' build config image kubecontrolplane legacyconfig)
```
> janitorial: drop repeated words words

- config/v1/types_feature.go
> Bug 2045551: Azure Disk and vSphere CSI drivers are GA

- config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
- config/v1/types_cluster_version.go
Add cluster-baremetal-operator as a capability
> config/v1/types_cluster_version: Add CBO

- machine/v1/types_nutanixprovider.go
- machine/v1/zz_generated.deepcopy.go
- machine/v1/zz_generated.swagger_doc_generated.go
Change to NutanixMachineProviderConfig to allow to configure one or more subnets for a Machine VM.
> Change to NutanixMachineProviderConfig to allow to configure one or more subnets for a Machine VM

- operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
- operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
- operator/v1/types_csi_cluster_driver.go
Adding Power VS Block CSI Driver to the API.
> Add PowerVS Block CSI Driver to the config

- config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
- config/v1/types_cluster_version.go
make storage operator optional
> Add storage capability

- config/v1/0000_10_config-operator_01_imagedigestmirrorset.crd.yaml
- config/v1/0000_10_config-operator_01_imagetagmirrorset.crd.yaml
API was added: https://github.com/openshift/api/pull/1126
Signed-off-by: Qi Wang <qiwan@redhat.com>
> [OCPNODE-521]Register ImageDigest/TagMirrorSet CRDs

- Makefile
- config/v1alpha1/0000_10_config-operator_01_insightsdatagather.crd.yaml
I just found out that the `config/v1alpha1/0000_10_config-operator_01_insightsdatagather.crd.yaml` was not updated as expected.
> fix InsightsDataGather CRD

- config/v1/types_feature.go
- config/v1/types_features_test.go
PSa should be in enforcement mode in master
/assign @deads2k
> add OpenShift PSa featuregate to the default profile

- machine/v1beta1/types_gcpprovider.go
- machine/v1beta1/zz_generated.swagger_doc_generated.go
- openapi/generated_openapi/zz_generated.openapi.go
- openapi/openapi.json
Add ConfidentialCompute support on GCP
Feature link: https://issues.redhat.com/browse/OCPBU-142
> MGMT-12728: Add ConfidentialCompute to GCPMachineProviderSpec

- config/v1/types_feature.go
Backport of https://github.com/openshift/api/pull/1341
/cc @deads2k @ibihim
> [4.12] OCPBUGS-6789: add pod security admission enforcement to techpreview

- config/v1/types_feature.go
https://issues.redhat.com/browse/STOR-1077
/hold for some e2e test results after https://github.com/openshift/origin/pull/27682
> STOR-1077: promote CSIInlineVolumeAdmission feature gate to GA

- config/v1/0000_10_config-operator_01_apiserver-Default.crd.yaml
- config/v1/0000_10_config-operator_01_apiserver-TechPreviewNoUpgrade.crd.yaml
- config/v1/0000_10_config-operator_01_apiserver.crd.yaml
- config/v1/stable.apiserver.testsuite.yaml
- config/v1/techpreview.apiserver.testsuite.yaml
- config/v1/types_apiserver.go
fixed generation on https://github.com/openshift/api/pull/1407
/assign @dgrisonnet
> API-1509: Add aesgcm to encryption config

- config/v1/feature_gates.go
- config/v1/types_feature.go
also add code to panic if it happens again.
/assign @benluddy
> fix some not-so-awesome typos

- config/v1/feature_gates.go
- config/v1/types_feature.go
found in https://github.com/openshift/cluster-ingress-operator/pull/908 as I tried bringing it to current.
> add GatewayAPI featureset

- config/v1/feature_gates.go
- config/v1/types_feature.go
@deads2k @patrickdillon @gcs278 @Miciah ptal
> Add feature gate for AWS Private Hosted Zone support

- config/v1/feature_gates.go
- config/v1/types_feature.go
KEP Reference: https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/3386-kubelet-evented-pleg/README.md
Enhancement PR: https://github.com/openshift/enhancements/pull/1368
cc: @mrunalp @harche @deads2k
> Add Evented Pleg as a Tech Preview feature in the Openshift

- operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
- operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
- operator/v1/types_csi_cluster_driver.go
https://issues.redhat.com/browse/STOR-1308
> STOR-1308: Add Secrets Store CSI driver provider

- operator/v1/0000_70_console-operator.crd.yaml
- operator/v1/types_console.go
/assign @spadgett 
@rhamilto FYI
> OCPBUGS-14716: Add ROSA branding option in console-operator config

- config/v1/feature_gates.go
- config/v1/types_feature.go
tweaked names on https://github.com/openshift/api/pull/1511
> Add etcdbackup featuregate

- openshiftcontrolplane/v1/types.go
Needed by:
- https://github.com/openshift/cluster-openshift-controller-manager-operator/pull/291
- We can also use those contants in https://github.com/openshift/openshift-controller-manager/blob/80c4923e0b2014ec8b8a6845c21078e6cc036f91/pkg/cmd/controller/config.go#L3-L25
Ref: https://github.com/openshift/cluster-openshift-controller-manager-operator/pull/291#discussion_r1285259744
> WRKLDS-727: add controller names

- config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
- config/v1/types_cluster_version.go
This reverts commit 875552e62c0faf6709722142c31cb526aab6667f.
> OCPBUGS-17806: Revert "add ImageRegistry capability"

- config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
- config/v1/types_cluster_version.go
This reverts commit b17597dd9bb60d2e14acd04e47c8a8c81cfc4c5f.
> Add back ImageRegistry capability

- config/v1/types_feature.go
- hack/update-protobuf.sh
#1582 but with the protobuf fix that was recently merged to master
> [release-4.14] OCPBUGS-18798: Revert "Enable ValidatingAdmissionPolicy for tech preview."

- config/v1/feature_gates.go
- config/v1/types_feature.go
AdmissionWebhookMatchConditions is enabled by default starting k8s 1.28 as beta.
> Remove AdmissionWebhookMatchConditions feature gate

- Dockerfile.rhel8
Not sure how many places this ripples to.
> update to rhel9 for image build

- config/v1/feature_gates.go
Add Feature Gate for AWS SDK Installs
> Add AWS SDK Install Feature Gate

- Dockerfile.rhel8
- manifests/image-references
/hold
waiting for clean image build.  Then maybe e2e?
> bring openshift/api into the payload

- payload-command/render/renderassets/rendered_manifests.go
- payload-command/render/renderassets/rendered_manifests_test.go
> make the render read yaml properly

- payload-command/render/render.go
found in testing https://github.com/openshift/installer/pull/7666
tagging to get a retry tomorrow.
> fix improper cast in render

- config/v1/feature_gates.go
- config/v1/types_feature.go
Adding a feature gate to mixedCPUs feature.
The full enhancement proposal can be found here: https://github.com/openshift/enhancements/commit/76ea48a88bca15ef6157aacf90b8544a763e6075
> CNF-10474:feature-gate: add mixedCPUs to feature gate

- console/v1/90_consoleplugin.crd.yaml
- console/v1alpha1/90_consoleplugin.crd.yaml
Addressing https://issues.redhat.com/browse/CONSOLE-3652
cc'ing @spadgett
> CONSOLE-3652: Enable ConsolePlugin v1 CRD storage

- .ci-operator.yaml
- Dockerfile.rhel8
- go.mod
- go.sum
> OCPBUGS-24955: Updating ose-cluster-config-api-container image to be consistent with ART

- payload-command/cmd/render/main.go
- payload-command/render/render.go
- payload-command/render/renderassets/assets.go
- payload-command/render/renderassets/write.go
Adds argument to honor the clusterprofile set on manifests to be rendered.
/cc @sjenning
> OCPBUGS-27366: respect the cluster profile in rendering

- config/v1/feature_gates.go
- config/v1/types_feature.go
- payload-manifests/featuregates/featureGate-Default.yaml
- payload-manifests/featuregates/featureGate-LatencySensitive.yaml
- payload-manifests/featuregates/featureGate-TechPreviewNoUpgrade.yaml
> OCPBUGS-27468: features: enabled TranslateStreamCloseWebsocketRequests through TechPreviewNoUpgrade

- operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
- operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
- operator/v1/types_csi_cluster_driver.go
https://issues.redhat.com/browse/STOR-1724
> STOR-1724: Add Samba/CIFS CSI driver provider

- console/v1/00_consoleclidownload.crd.yaml
- console/v1/00_consoleexternalloglink.crd.yaml
- console/v1/00_consolelink.crd.yaml
- console/v1/00_consolenotification.crd.yaml
- console/v1/00_consolequickstart.crd.yaml
- console/v1/00_consolesample.crd.yaml
- console/v1/00_consoleyamlsample.crd.yaml
- console/v1/90_consoleplugin.crd.yaml
- console/v1/manual-override-crd-manifests/consoleplugins.console.openshift.io/AAA_ungated.yaml
- console/v1/types_console_cli_download.go
- console/v1/types_console_external_log_links.go
- console/v1/types_console_link.go
- console/v1/types_console_notification.go
- console/v1/types_console_plugin.go
- console/v1/types_console_quick_start.go
- console/v1/types_console_sample.go
- console/v1/types_console_yaml_sample.go
- console/v1/zz_generated.featuregated-crd-manifests.yaml
- console/v1/zz_generated.featuregated-crd-manifests/consoleclidownloads.console.openshift.io/AAA_ungated.yaml
- console/v1/zz_generated.featuregated-crd-manifests/consoleexternalloglinks.console.openshift.io/AAA_ungated.yaml
- console/v1/zz_generated.featuregated-crd-manifests/consolelinks.console.openshift.io/AAA_ungated.yaml
- console/v1/zz_generated.featuregated-crd-manifests/consolenotifications.console.openshift.io/AAA_ungated.yaml
- console/v1/zz_generated.featuregated-crd-manifests/consoleplugins.console.openshift.io/AAA_ungated.yaml
- console/v1/zz_generated.featuregated-crd-manifests/consolequickstarts.console.openshift.io/AAA_ungated.yaml
- console/v1/zz_generated.featuregated-crd-manifests/consolesamples.console.openshift.io/AAA_ungated.yaml
- console/v1/zz_generated.featuregated-crd-manifests/consoleyamlsamples.console.openshift.io/AAA_ungated.yaml
> updating console stragglers to by-feature-gate generation

- machineconfiguration/v1/0000_80_containerruntimeconfig.crd.yaml
- machineconfiguration/v1/0000_80_kubeletconfig.crd.yaml
- machineconfiguration/v1/0000_80_machineconfig.crd.yaml
- machineconfiguration/v1/0000_80_machineconfigpool.crd.yaml
- machineconfiguration/v1/types.go
- machineconfiguration/v1/zz_generated.featuregated-crd-manifests.yaml
- machineconfiguration/v1/zz_generated.featuregated-crd-manifests/containerruntimeconfigs.machineconfiguration.openshift.io/AAA_ungated.yaml
- machineconfiguration/v1/zz_generated.featuregated-crd-manifests/kubeletconfigs.machineconfiguration.openshift.io/AAA_ungated.yaml
- machineconfiguration/v1/zz_generated.featuregated-crd-manifests/machineconfigpools.machineconfiguration.openshift.io/AAA_ungated.yaml
- machineconfiguration/v1/zz_generated.featuregated-crd-manifests/machineconfigs.machineconfiguration.openshift.io/AAA_ungated.yaml
good timing in this area actually. I remember hearing rumors of more APIs here
> update machineconfiguration to use featuregated generation

- tools/codegen/pkg/manifestmerge/filters.go
- tools/codegen/pkg/manifestmerge/generator.go
> tighten up the useCRD interface

- cloudnetwork/v1/zz_generated.featuregated-crd-manifests.yaml
- config/v1/zz_generated.featuregated-crd-manifests.yaml
- console/v1/zz_generated.featuregated-crd-manifests.yaml
- example/v1/zz_generated.featuregated-crd-manifests.yaml
- example/v1alpha1/zz_generated.featuregated-crd-manifests.yaml
- insights/v1alpha1/zz_generated.featuregated-crd-manifests.yaml
- machine/v1/zz_generated.featuregated-crd-manifests.yaml
- machine/v1beta1/0000_10_machine.crd.yaml
- machine/v1beta1/0000_10_machinehealthcheck.yaml
- machine/v1beta1/0000_10_machineset.crd.yaml
- machine/v1beta1/manual-override-crd-manifests/machinesets.machine.openshift.io/AAA_ungated.yaml
- machine/v1beta1/types_machine.go
- machine/v1beta1/types_machinehealthcheck.go
- machine/v1beta1/types_machineset.go
- machine/v1beta1/zz_generated.featuregated-crd-manifests.yaml
- machine/v1beta1/zz_generated.featuregated-crd-manifests/machinehealthchecks.machine.openshift.io/AAA_ungated.yaml
- machine/v1beta1/zz_generated.featuregated-crd-manifests/machines.machine.openshift.io/AAA_ungated.yaml
- machine/v1beta1/zz_generated.featuregated-crd-manifests/machinesets.machine.openshift.io/AAA_ungated.yaml
- machineconfiguration/v1/zz_generated.featuregated-crd-manifests.yaml
- machineconfiguration/v1alpha1/zz_generated.featuregated-crd-manifests.yaml
- monitoring/v1alpha1/zz_generated.featuregated-crd-manifests.yaml
- network/v1alpha1/zz_generated.featuregated-crd-manifests.yaml
- operator/v1/zz_generated.featuregated-crd-manifests.yaml
- operatoringress/v1/zz_generated.featuregated-crd-manifests.yaml
- platform/v1alpha1/zz_generated.featuregated-crd-manifests.yaml
- route/v1/zz_generated.featuregated-crd-manifests.yaml
- sharedresource/v1alpha1/zz_generated.featuregated-crd-manifests.yaml
- tools/codegen/pkg/emptypartialschemas/content_creator.go
- tools/codegen/pkg/emptypartialschemas/partial_schemas.go
> update the machine group to use the featuregate generator

- payload-command/render/render.go
> skip rendering mutation of CustomNoUpgrade featuresets

- build/OWNERS
- Designate @gabemontero and @jim-minter  as "emeritus reviewers."
- Add @adambkaplan and @sayan-biswas as reviewers.
> BUILD-854: Updates to build API reviewers

- Makefile
> Add models-schema to make clean

- config/v1/feature_gates.go
- features.md
- payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
- payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
These features go to beta in 1.30.  Playing with them in 1.29 in techpreview is very convenient.
> NO-JIRA: enable the SA token node thing

- machineconfiguration/v1alpha1/types_machineosbuild.go
- machineconfiguration/v1alpha1/types_machineosconfig.go
- machineconfiguration/v1alpha1/zz_generated.crd-manifests/0000_80_machine-config_01_machineosbuilds-CustomNoUpgrade.crd.yaml
- machineconfiguration/v1alpha1/zz_generated.crd-manifests/0000_80_machine-config_01_machineosbuilds-TechPreviewNoUpgrade.crd.yaml
- machineconfiguration/v1alpha1/zz_generated.crd-manifests/0000_80_machine-config_01_machineosconfigs-CustomNoUpgrade.crd.yaml
- machineconfiguration/v1alpha1/zz_generated.crd-manifests/0000_80_machine-config_01_machineosconfigs-TechPreviewNoUpgrade.crd.yaml
- machineconfiguration/v1alpha1/zz_generated.featuregated-crd-manifests/machineosbuilds.machineconfiguration.openshift.io/OnClusterBuild.yaml
- machineconfiguration/v1alpha1/zz_generated.featuregated-crd-manifests/machineosconfigs.machineconfiguration.openshift.io/OnClusterBuild.yaml
- openapi/generated_openapi/zz_generated.openapi.go
- openapi/openapi.json
I noticed a stray +unionDiscriminator comment rather than +optional, fixed that. also noticed a type that should be optional, not required.
> MCO API Cleanup

- Makefile
- hack/verify-promoted-features-pass-tests.sh
- tools/codegen/cmd/featuregate-test-analyzer.go
- tools/codegen/cmd/featuregate-test-analyzer_test.go
- tools/codegen/cmd/featureset-markdown.go
- tools/codegen/pkg/sippy/json_types.go
- tools/codegen/pkg/utils/markdown.go
- tools/go.mod
- tools/go.sum
- tools/vendor/github.com/russross/blackfriday/.gitignore
- tools/vendor/github.com/russross/blackfriday/.travis.yml
- tools/vendor/github.com/russross/blackfriday/LICENSE.txt
- tools/vendor/github.com/russross/blackfriday/README.md
- tools/vendor/github.com/russross/blackfriday/block.go
- tools/vendor/github.com/russross/blackfriday/doc.go
- tools/vendor/github.com/russross/blackfriday/esc.go
- tools/vendor/github.com/russross/blackfriday/html.go
- tools/vendor/github.com/russross/blackfriday/inline.go
- tools/vendor/github.com/russross/blackfriday/markdown.go
- tools/vendor/github.com/russross/blackfriday/node.go
- tools/vendor/github.com/russross/blackfriday/smartypants.go
- tools/vendor/github.com/shurcooL/sanitized_anchor_name/.travis.yml
- tools/vendor/github.com/shurcooL/sanitized_anchor_name/LICENSE
- tools/vendor/github.com/shurcooL/sanitized_anchor_name/README.md
- tools/vendor/github.com/shurcooL/sanitized_anchor_name/main.go
- tools/vendor/modules.txt
I think I'll need to update this to match the crd-schema-checker
> NO-JIRA: add command to restrict features from promotion without tests

- machineconfiguration/v1alpha1/types_machineosbuild.go
- machineconfiguration/v1alpha1/zz_generated.crd-manifests/0000_80_machine-config_01_machineosbuilds-CustomNoUpgrade.crd.yaml
- machineconfiguration/v1alpha1/zz_generated.crd-manifests/0000_80_machine-config_01_machineosbuilds-DevPreviewNoUpgrade.crd.yaml
- machineconfiguration/v1alpha1/zz_generated.crd-manifests/0000_80_machine-config_01_machineosbuilds-TechPreviewNoUpgrade.crd.yaml
- machineconfiguration/v1alpha1/zz_generated.featuregated-crd-manifests.yaml
- machineconfiguration/v1alpha1/zz_generated.featuregated-crd-manifests/machineosbuilds.machineconfiguration.openshift.io/OnClusterBuild.yaml
The printer columns were not updated when the status string types were changed.
> fix MachineOSBuild printer columns

- tools/codegen/pkg/schemacheck/generator.go
Moving CRD schemas to subfolders meant that the logic here could no longer find them. The logic has been updated now to recurse and find CRDs in subfolders as well.
The logic is picking up both manual and partial CRD schemas, some of which do not have schemas. We are skipping any CRD where it does not have a valid schema, and dropping the old version if the old version doesn't have a schema, but the new version does.
> Recurse when loading CRD schemas to check

- imageregistry/v1/types.go
- imageregistry/v1/zz_generated.crd-manifests/00_configs.crd.yaml
- imageregistry/v1/zz_generated.featuregated-crd-manifests/configs.imageregistry.operator.openshift.io/AAA_ungated.yaml
Follow up https://github.com/openshift/api/pull/1864#issuecomment-2090941767 
/hold
> Update imageregistry component SSA tags

- features.md
- features/features.go
- payload-manifests/featuregates/featureGate-Hypershift-DevPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-DevPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
> CORS-3488: Add GCP CAPI installer to tech preview feature set.

- config/v1/types_network.go
- config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_networks.crd.yaml
- config/v1/zz_generated.featuregated-crd-manifests/networks.config.openshift.io/AAA_ungated.yaml
- config/v1/zz_generated.featuregated-crd-manifests/networks.config.openshift.io/NetworkDiagnosticsConfig.yaml
- config/v1/zz_generated.featuregated-crd-manifests/networks.config.openshift.io/NetworkLiveMigration.yaml
- openapi/generated_openapi/zz_generated.openapi.go
- openapi/openapi.json
- payload-manifests/crds/0000_10_config-operator_01_networks.crd.yaml
This is based on https://github.com/openshift/api/pull/1886 so there are no conflicts once #1886 merges.
> NO-JIRA: Set listType for .status.serviceNetwork and .status.clusterNetwork in networks.config

- tools/codegen/pkg/sippy/json_types.go
Once https://github.com/openshift/sippy/pull/1723 merges, these queries will need to be updated.
> Feature gate sippy queries to use variant registry

- tools/codegen/cmd/featuregate-test-analyzer.go
Ask Sippy for the latest release instead of hardcoding to 4.16.
> featuregate promotion: use latest release instead of hard coding

- features/features.go
Switch from stlaz to ibihim in PSA.
Switch from stlaz to liouk in external OIDC.
We are the current owners of the efforts.
> features: update psa and byoo owners

- features/features.go
- features/util.go
This doesn't (yet), mean the PR must be merged, but it does mean the PR needs to be open and GA graduation criteria need to be present.  Typically GA criteria include
1. which automated tests must exist so we know it works
2. how will we monitor this to ensure it functions correctly after we ship
3. what additional information needs to be present in must-gather to debug this
/cc @JoelSpeed 
/assign @sdodson @mrunalp
> NO-JIRA: add requirement for featuregate URL

- features.md
- features/features.go
- payload-manifests/featuregates/featureGate-Hypershift-DevPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-DevPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
Mark CAPI Install for IBM Cloud FG as TechPreview.
> IBMCloud: Add IBM Cloud CAPI install TechPreview FG

- features.md
- features/features.go
- payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
- payload-manifests/featuregates/featureGate-Hypershift-DevPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-DevPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
[SPLAT-2213](https://issues.redhat.com/browse/SPLAT-2213)
- Created new feature gate for vSphere mixed node env feature
> SPLAT-2213: Added vSphere mixed node env feature gate

- features.md
- features/features.go
- payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
- payload-manifests/featuregates/featureGate-Hypershift-DevPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-DevPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
As discussed in our arch call.
> CNTRLPLANE-371: Remove SELinuxChangePolicy gate 

- features.md
- features/features.go
- payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
- payload-manifests/featuregates/featureGate-Hypershift-DevPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-DevPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
https://issues.redhat.com/browse/STOR-2462
> STOR-2462: Add ExternalSnapshotMetadata FeatureGate

- features.md
- features/features.go
- payload-manifests/featuregates/featureGate-Hypershift-Default.yaml
- payload-manifests/featuregates/featureGate-Hypershift-DevPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-Hypershift-TechPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-Default.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-DevPreviewNoUpgrade.yaml
- payload-manifests/featuregates/featureGate-SelfManagedHA-TechPreviewNoUpgrade.yaml
This patch introduces the new `NoRegistryClusterOperations` feature
> AGENT-1262: add NoRegistryClusterOperations feature gate

- machineconfiguration/v1/types_machineconfignode.go
- machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfignodes-CustomNoUpgrade.crd.yaml
- machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfignodes-Default.crd.yaml
- machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfignodes-DevPreviewNoUpgrade.crd.yaml
- machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfignodes-TechPreviewNoUpgrade.crd.yaml
- machineconfiguration/v1/zz_generated.featuregated-crd-manifests.yaml
- machineconfiguration/v1/zz_generated.featuregated-crd-manifests/machineconfignodes.machineconfiguration.openshift.io/ImageModeStatusReporting.yaml
- machineconfiguration/v1/zz_generated.featuregated-crd-manifests/machineconfignodes.machineconfiguration.openshift.io/IrreconcilableMachineConfig.yaml
- machineconfiguration/v1/zz_generated.featuregated-crd-manifests/machineconfignodes.machineconfiguration.openshift.io/MachineConfigNodes.yaml
- payload-manifests/crds/0000_80_machine-config_01_machineconfignodes-CustomNoUpgrade.crd.yaml
- payload-manifests/crds/0000_80_machine-config_01_machineconfignodes-Default.crd.yaml
- payload-manifests/crds/0000_80_machine-config_01_machineconfignodes-DevPreviewNoUpgrade.crd.yaml
- payload-manifests/crds/0000_80_machine-config_01_machineconfignodes-TechPreviewNoUpgrade.crd.yaml
This adds a column called `AGE` to the output for the MachineConfigNode object.
**To test:**
1. Launch a 4.21 cluster with this PR.
2. Observe the MCN output.
```
$ oc get machineconfignode
NAME                                       POOLNAME   DESIREDCONFIG                                      CURRENTCONFIG                                      UPDATED   AGE
ci-ln-dks5l4k-72292-vt5jm-master-0         master     rendered-master-3b21be93539ffce4a129bbe5103468d6   rendered-master-3b21be93539ffce4a129bbe5103468d6   True      49m
ci-ln-dks5l4k-72292-vt5jm-master-1         master     rendered-master-3b21be93539ffce4a129bbe5103468d6   rendered-master-3b21be93539ffce4a129bbe5103468d6   True      49m
ci-ln-dks5l4k-72292-vt5jm-master-2         master …
```
> OCPBUGS-61689: Add 'AGE' print column to `MachineConfigNode` object

- machineconfiguration/v1/types_machineconfignode.go
- machineconfiguration/v1/zz_generated.crd-manifests/0000_80_machine-config_01_machineconfignodes.crd.yaml
- machineconfiguration/v1/zz_generated.featuregated-crd-manifests.yaml
- machineconfiguration/v1/zz_generated.featuregated-crd-manifests/machineconfignodes.machineconfiguration.openshift.io/MachineConfigNodes.yaml
- payload-manifests/crds/0000_80_machine-config_01_machineconfignodes.crd.yaml
This is a manual cherry-pick of #2497 since the [automated cherry-pick failed](https://github.com/openshift/api/pull/2497#issuecomment-3328259220).
> [release-4.19] OCPBUGS-62155: Add 'AGE' print column to MachineConfigNode object
